### ISSUE TITLE
onSetWrapperTransform not returning transform values on release

### ISSUE THREAD

**Issue by amasen** [nolimits4web/Swiper#1080]
$(function(){
  var mySwiper = $('#article_'+currentI).swiper({
    mode:'vertical',
    loop: false,
    cssWidthAndHeight: true,
    onSetWrapperTransform: function (swiper, translate) {
      console.log(translate);
    },
});
});

While dragging up/down the translate value is returned (as it is translating), but on release it only returns the end value rather than value as the object returns into position (looking for values every time the object changes position).

The reason I am looking for this value, is that I am looking for the objects within the slides to operate slightly differently than the slides themselves (while still maintaining the slides general movement).

**Comment by nolimits4web** [comment]
That is how CSS transforms/transition works, this function returns currently set transform/translate position, and there is no any between values, at least Swiper doesn't listen them, because they don't needed in 99.99% of cases. If you transform/translate some other objects during Swiper translate, you need to also watch for `onSetWrapperTransition` callback and set CSS transition on those objects

**Comment by amasen** [comment]
Ahh, I see.

I noticed the wrapper objects had transform's applied to them, but upon release would jump from the mouse cursor to the previous or next slides value. I just assumed this was being handled in javascript. Now I see it's set by the transition duration when the user isn't directly interacting with the object.

Thanks for the quick response and the awesome plugin!
