### ISSUE TITLE
Is it possible to build a horizontal nested Swiper inside another?

### ISSUE THREAD

**Issue by soupking** [nolimits4web/Swiper#1084]
Hi nolimits4web,

I'm trying to build a page where the first slide slides halfway upon swipe and subsequent slides swipe underneath the first slide all sliding left horizontally. I see you have a vertical slider inside your horizontal nested slider demo but when the mode is altered it doesn't recognize it separately from the main one. Is there another attribute I need to turn off/on for this to happen?

Also is it possible to have slide images stop fixed at a certain value? Those are the two things I need to sort out to build this thing.

Thanks for any suggestions.

**Comment by nolimits4web** [comment]
No, it is impossible to have nested horizontal in horizontal

**Comment by IllyaMoskvin** [comment]
Apparently, it is possible now? You have to set `nested: true` for the configuration of the inner slider. Here, I modified the [nested swiper demo](http://idangero.us/swiper/demos/11-nested.html) from the main site so that the inner slider is horizontal, not vertical. Check out this fiddle: https://jsfiddle.net/imoskvin/s0fm20m6/

**Comment by pkuczynski** [comment]
Another example of an alternative nested swiper: https://jsfiddle.net/imoskvin/s0fm20m6/

**Comment by but1head** [comment]
it is impossible for horizontal parent and freeMode nested?
