### ISSUE TITLE
Integrate mouseleave event to have proper cancel-animation on Desktop

### ISSUE THREAD

**Issue by cookiengineer** [nolimits4web/Swiper#1096]
Hey there,

by quick testing your library I found out that you don't bind the mouseleave event on Desktop.
If a user drags a slide from the demos (e.g. a vertical slide) and moves the mouse outside the container, it of course cancels. The issue here is that if the mouse gets in again (even if not pressing the mouse button) the animation still behaves like it's being dragged.

You can simply fix that by adding the same logic like mouseup, just for the mouseleave event here:
https://github.com/nolimits4web/Swiper/blob/master/src/js/core.js#L739

**Comment by nolimits4web** [comment]
I am not sure that we need it, it is only issue on demo page, and only because those demos are in iframe, mouse events are bind to document, so if you use it not in iframes, you will not have such issues

**Comment by martensms** [comment]
Simple use case: Two-monitor setup, move mouse outside window while dragging. Same issue, same behaviour.

**Comment by nolimits4web** [comment]
Ok, will take a look closer

**Comment by nolimits4web** [comment]
That is strange but why dragging (holding mouse pressed) "mouseleave" event doesn't get triggered, so if i move mouse outside of window everything work as expected. At least in any browser in OSX

**Comment by BenjaminBeck** [comment]
I noticed this also within a few seconds of testing the swiper-demos. 

This happens with Safari and Crome on OSX.
Firefox works as expected.

There should be a big red note on the top of the page so that people know this is not a bug.
Or some other solution ..

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
