### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by roman01la** [nolimits4web/Swiper#1130]
Integrating basic keyboard controls would be nice for some accessibility. Swiper still works on desktop and it will be used on desktop, so this makes sense:

- Make navigation controls focusable (arrows and bullets) with Tab, Shift + Tab.
- Provide visual feedback on focusable elements, so user can perceive current position on the page.
- Make navigation controls interactive via keyboard: Enter/Space key.

I can setup PR for this.

**Comment by goetsu** [comment]
there is a keyboard control demo : http://www.idangero.us/swiper/demos/19-keyboard-control.html but still missiong visual feedback at least

**Comment by roman01la** [comment]
@goetsu I see there's API call for enabling this, but this is implemented with keyboard hijacking and disabled by default.

What should be done is default behaviour, where all interactive elements should actually focusable and able to interact with via keyboard by default, as normal buttons and links within the slider.

**Comment by goetsu** [comment]
I agree it must be enable by default but regarding native keyboard focus on all interactive elements I don't think it's a good solution because it create multiple stops in keyboard navigations ( a mouse user don't get all the slide if he doesn't want them). 
I prefer something like that by default : 
- on focus of the slide get visual feedback and make a text like "to navigate use arrow keys" visible
- get graphic arrows and or navigation by default to let user understand that there is other slides
- hide all slides for screenreader except the current one
- on use of arrow keys or click on graphic arrows or navigation move focus on the new slide after the animation

You also may use some ARIA to improve the experience with screenreader

**Comment by roman01la** [comment]
@goetsu Yeah, it's another option I can think about. Also, ARIA would be nice for screen reader users, it can be used to warn users that cursor is within slider and to read out how user can navigate it. I think ARIA support deserves separate issue here.

**Comment by nolimits4web** [comment]
Guys, but we are talking about mobile-first touch slider, right? :) Do we really need this here?

**Comment by roman01la** [comment]
@nolimits4web Yeah, that's why I've mentioned desktop, there's also a mention in README. Looks like Swipers works on desktop, so I believe it will be used as a responsive slider for both desktop and mobile.
Also, for mobile, it requires some ARIA for screen reader users, but this is a separate issue.

**Comment by goetsu** [comment]
yes and : 
1) many android devices has a keyboard 
2) both android and ios device can be used with bluethoth keyboard (especially when you adress tablet too
3) can be used on desktop too
4) visibility of navigation and graphic arrows are needed anyway if you want let the user know that something can be swapped left or right or clicked to navigate

PS: ARIA is not only for mobile

**Comment by nolimits4web** [comment]
Right, but desktop in none-target platform for Swiper. Anyway, if you guys can make a PR for that, and it will not contain a lot of hundreds of code lines, i will merge it

**Comment by nolimits4web** [comment]
Guys any update on this with PR?

**Comment by roman01la** [comment]
@nolimits4web I'll prepare this one
