### ISSUE TITLE
Parallax in out

### ISSUE THREAD

**Issue by idelb** [nolimits4web/Swiper#1150]
Can you add different speed of in and out for the parallax effect?

**Comment by nolimits4web** [comment]
You mean like to have `data-swiper-parallax-duration-in` and `data-swiper-parallax-duration-out` ?

**Comment by idelb** [comment]
Yes, that's what I mean :)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
