### ISSUE TITLE
Feature request: Ratio

### ISSUE THREAD

**Issue by tcurdt** [nolimits4web/Swiper#1169]
In a responsive world it would be nice if I could give the slider a certain ratio.
So it's width would adjust to the parent width and the height would calculate accordingly.

Example: http://jsfiddle.net/tcurdt/hnud0jx6/

Resize to see what I mean.

**Comment by nolimits4web** [comment]
But if you use `<img>` in slides then Swiper should do the same if you set its height to 'auto'

**Comment by nolimits4web** [comment]
Here http://jsfiddle.net/gwyb0epa/

**Comment by tcurdt** [comment]
Hm. Intriguing.

This only works with images of the same width though. Granted the sizes of my original fiddle are certainly a bit unrealistic - and they raise the question of pagination. I guess I could have multiple images per page.

I guess I need to play with this a bit. I will report back.
Thanks for the fiddle!

**Comment by henrik** [comment]
I stuck elements with [responsive ratio](http://alistapart.com/article/creating-intrinsic-ratios-for-video) inside a slide and they seemed to just work. E.g.

``` html
<div class="swiper-slide">
  <div style="width:100%; padding-bottom: 75%; position: relative; height: 0"> <!-- proportions are 100 x 75 -->
    <div style="position: absolute; top: 0; right: 0; bottom: 0; left: 0">my content</div>
  </div>
</div>
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
