### ISSUE TITLE
swiper.update() doesn't work correctly after hiding some slides

### ISSUE THREAD

**Issue by cbxp** [nolimits4web/Swiper#1182]
In general, often we need to hide/show slides dynamically, but after calling swiper.update() it doesn't behave correctly.

It used to work with swiper 3.0.0, when swiper.slides would remain the same as before, but swiper-active class would be set to correct element.

Now, after upgrading to swiper 3.0.4 (and 3.0.5), in case some slides are hidden, swiper-active class is set to a wrong slide.

**Comment by nolimits4web** [comment]
Sorry, Swiper currenlty doesn't support hidden slides at all. If you need to remove slides, then you should to remove them from DOM

**Comment by angryziber** [comment]
Then it accidentally worked fine in 3.0.0.

I hope that current erratic behaviour can be fixed: it sets swiper-active class to a wrong slide, not the one that is currently visible.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
