### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by Gnative** [nolimits4web/Swiper#1227]
I found when trying to alter the swiper to do as i would like that a lot of functionality was already built in but not declared or not explained fully in the documentation such as adding custom transitions via onSetTranslate and onSetTransition. Also with the parallax and the data attribute data-swiper-parallax-duration which is super handy to help soften up the parralax effects.

**Comment by Gnative** [comment]
Also the plugin architecture.

**Comment by Gnative** [comment]
Awesome slider thou.. been using it for years.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
