### ISSUE TITLE
How to position image inside “swiper-wrapper”?

### ISSUE THREAD

**Issue by MIRAMAXED** [nolimits4web/Swiper#1274]
Hello! Please help me ) I need to position image inside “swiper-wrapper: (position: fixed) by center, that does not scroll with slides. For example: joxi.ru/JMAjol7HOMEzre
I use ”Centered Slides + Auto Slides Per View + Free mode"

**Comment by nolimits4web** [comment]
You can't position it inside swiper-wrapper, just put it inside of swiper-container, and it will not scroll

**Comment by MIRAMAXED** [comment]
I know about it, but need position it exactly inside swiper-wrapper for effect: each 2th slide has z-index biggest than fixed image, and image must hiding behind slide and shown again. Maybe there is a different solution?

**Comment by nolimits4web** [comment]
As i said, you can't do it, because you can't use `position:fixed` elements in "transformed" elements, it is just not supported by browsers. There only solution you can try to listen for the `onSetTranslate` and `onSetTransition` callbacks and to position this image by setting required transform to it

**Comment by MIRAMAXED** [comment]
Спасибо! Попробую разобраться)

**Comment by nolimits4web** [comment]
можете посмотреть принцип логики в эффектах https://github.com/nolimits4web/Swiper/blob/master/src/js/effects.js
