### ISSUE TITLE
Make 'namespace' available via data attributes

### ISSUE THREAD

**Issue by jonnyscholes** [nolimits4web/Swiper#1303]
Currently the namespace selectors _must_ be classes. We use data attributes in most of our projects now, would be great to be able to convert our Swiper usage to this pattern to.

I can submit a PR for this - the main question is how do we support implementations that used the old syntax? Make it a breaking change and notify? Create a whole new set of options? Or map the old ones to new option names (knowing to pass them in as classnames) and mark them as depreciated in the docs?

Thoughts?

**Comment by nolimits4web** [comment]
Ok, will do something, probably with new set of options, as it shouldn't do any breaking changes

**Comment by jonnyscholes** [comment]
Thanks - let me know if you run out of time and I can work on it and submit a PR.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
