### ISSUE TITLE
Wrong order calculation for multi-lines container

### ISSUE THREAD

**Issue by Oleksa** [nolimits4web/Swiper#1306]
In case if not all lines are full filled up the Swiper generate wrong source number. For example you can try 16 items, slidesPerColumn: 3, slidesPerColumnFill: 'column' in case if 6 columns are visible. Proposed fix is (core.js, starting in line 515:)
==============
            // Calc slides
            var slideSize;
            var slidesPerColumn = s.params.slidesPerColumn;
            var slidesPerRow = slidesNumberEvenToRows / slidesPerColumn;
            var numFullColumns = slidesPerRow - (s.params.slidesPerColumn * slidesPerRow - s.slides.length);
            for (i = 0; i < s.slides.length; i++) {
                slideSize = 0;
                var slide = s.slides.eq(i);
                if (s.params.slidesPerColumn > 1) {
                    // Set slides order
                    var newSlideOrderIndex;
                    var column, row;
                    if (s.params.slidesPerColumnFill === 'column') {
                        column = Math.floor(i / slidesPerColumn);
                        row = i - column * slidesPerColumn;
                        if (column > numFullColumns || (column==numFullColumns && row==slidesPerColumn-1)) {
                            if (++row>=slidesPerColumn) {
                                row=0;
                                column++;
                           }
                        }
                        newSlideOrderIndex = column + row * slidesPerRow;
                        slide
                            .css({
                                '-webkit-box-ordinal-group': newSlideOrderIndex,
                                '-moz-box-ordinal-group': newSlideOrderIndex,
                                '-ms-flex-order': newSlideOrderIndex,
                                '-webkit-order': newSlideOrderIndex,
                                'order': newSlideOrderIndex
                            });
                    }
                    else {
                        row = Math.floor(i / slidesPerRow);
                        column = i - row * slidesPerRow;
        
                    }
                    slide
                        .css({
                            'margin-top': (row !== 0 && s.params.spaceBetween) && (s.params.spaceBetween + 'px')
                        })
                        .attr('data-swiper-column', column)
                        .attr('data-swiper-row', row);
        
                }
 ....
==========================
Thank you,
-=A=-

**Comment by nolimits4web** [comment]
Do you have a live example or JSFiddle so i can understand better this problem?

**Comment by Oleksa** [comment]
Just try to display 16 slides in 3 columns with filling up by 'column'. Last two columns should  contains 2 slides only (not 3). According to the current code source-orders will be :
 0  1    2  3  4   5
 6   7   8  9  10
12 13 14 15 16

As you can see source order 11 is missed and second row is not properly filled up. Proper source order should be

 0    1   2  3   4   5
 6    7   8  9  10 11
12 13 14 15

**Comment by naeon** [comment]
Unfortunately, this issue does not seem to be fixed completely:

Using the fill methods "column" or "row" leads to similar behaviour but it should not. See [this fiddle](https://jsfiddle.net/gnsfd5vq/) with a 3x3 grid (3 slides per view, 3 slides per column), fill method "column" and 10 slides total. One would expect that the initial view has 9 slides visible, instead it has only 8.

It seems that this is due to the fill order which comes aparent when switching to a grid with 4 slides per view, 3 slides per column ([forked fiddle](https://jsfiddle.net/gnsfd5vq/1/)):

![swiper_fillorder](https://cloud.githubusercontent.com/assets/5183232/13728528/466c1b9a-e91c-11e5-860d-591a8dec79e1.png)

**Green arrows** mark the expected fill order (consistent to the slide numbers) and **red arrows** mark the actual fill order (inconsistent).

**Comment by kanon488** [comment]
Hi, i have a question, if a have 15 swiper-slides elements  want 3 slidesPerView and 3 slidesPerColumn,
how i can order these elements into a 2 Views each one with  9 slides grid? thanks.
Example:
1|2|3                 10|11|12
4|5|6   -------> 13|14|15
7|8|9

**Comment by petrusolofsson** [comment]
I have found a solution to this problem for my project. The problem seems to occur because of how CSS flexbox works with Swiper. It still fills the slides by row, and column is only simulated by using CSS order, so the last remaining items always show on the last row, instead of in the last column.

My solution is to calculate how many slides are missing to fill the whole grid, then append placeholder empty slides equal to number of missing slides to Swiper on init, and then Swiper will calculate and fill the columns correctly.

Code I’m using is here:
 
```
onInit: function (swiper) {
    // Slides per column
    console.log('slidesPerColumn: ' + swiper.params.slidesPerColumn);
    // Total number of slides
    console.log('totalNumberOfSlides: ' + swiper.slides.length);
    // Slides outside even grid
    var slidesOutsideEvenGrid = swiper.slides.length % swiper.params.slidesPerColumn;
    console.log('slidesOutsideEvenGrid: ' + slidesOutsideEvenGrid);
    // Check if grid is totally filled
    if (slidesOutsideEvenGrid != 0) {
        console.log('not even grid');
        // Grid not totally filled, calculate slides needed to fill grid
        var slidesNeededToFillGrid = swiper.params.slidesPerColumn - slidesOutsideEvenGrid;
        console.log('slidesNeededToFillGrid: ' + slidesNeededToFillGrid);
        // Append as many empty placeholder slides needed to fill grid
        for (var i = 0; i < slidesNeededToFillGrid; i++) {
            swiper.appendSlide('<div class="swiper-slide"></div>');
        }
    }
}
```

Hope something like this can be implemented in core to solve the problem with filling columns correctly.

Live example can be found here: https://www.myresjohus.se/inspiration/hall/

(_At the time this comment was written, the code above was not yet deployed for the live example above, so if order is still wrong for the thumbnails in the Swiper slideshow, check back at the live example in a couple of days to see it working_)
