### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by themellwood** [nolimits4web/Swiper#1307]
When selecting how many slides to view, there should be an option for different amounts on different screen sizes. For example on mobile I only want one "card" to be 100% of the small screen, but on desktop it should display 3 cards

**Comment by nolimits4web** [comment]
It could be done here with pure CSS solution using media queries

**Comment by vennamo** [comment]
You can use matchmedia (remember old ie polyfills) to set swiper slidesPerView setting based on it.
http://jsfiddle.net/r5fqwrfa/

**Comment by wgroenewold** [comment]
@vennamo You could even use Modernizr for it. Since it is included in all our projects that would lower the number of loaded libraries.

```
if(Modernizr.mq('only screen and (min-width: 1025px)')){
//do stuff
}
```

**Comment by vennamo** [comment]
Sure.

**Comment by leandroruel** [comment]
would be great a "breakpoint" to define slidesPerView based on screen width.

example: in 320px show only 1 slide and desktop 3.

**Comment by xipasduarte** [comment]
You can achieve a very good behaviour by setting `slidesPerView: 'auto'` and then using CSS to have your slides have width: 100%, 50%, 25%, etc. (1, 2, 4 slides).
Be careful to set `slidesPerGroup` to how many you display the smallest viewport (assuming this is where you have less), otherwise you will skip slides with navigation.

**Comment by nolimits4web** [comment]
I think i can close it as there is no further discussion and there are `breakpoints` support in latest Swiper
