### ISSUE TITLE
Using more than two controllers gives a "Uncaught RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by wgroenewold** [nolimits4web/Swiper#1322]
Hi,

I want to have three Swipers with the same amount of slides that run in sync. When 1 one of the Swiper is controlled the others should behave accordingly. I tried to do this with param.control, but it throws a RangeError on me. To verify the error, if I remove one of the control lines it works flawlessly, but only for two Swipers.

```
desktopSwiper.params.control = [iphoneSwiper, ipadSwiper];
iphoneSwiper.params.control  = [ipadSwiper, desktopSwiper];
ipadSwiper.params.control = [iphoneSwiper, desktopSwiper];
```

**Comment by wgroenewold** [comment]
Managed to "solve" it:
-Make an empty global variable swiperController.
-Give every swiper the following callback functions:
 -onTouchStart set the swiperController to the name of the current swiper
 -onSlideChangeStart check if the swiperController is the current swiper, if true slide the other swipers.
-onSlideChangeEnd unset the swiperController

This way the current touched swiper acts as as master and the other ones as slaves and only triggers the callbacks if the swiperController var is set as master.

Would be nice if this would function natively.

**Comment by nolimits4web** [comment]
Thanks, as i see there is a really issue with that. Will check it

**Comment by wgroenewold** [comment]
Cool!

**Comment by mayukojpn** [comment]
Hello! I have a same issue and trying to write same kind of codes, but It would be nice if anyone already fixed it natively. :)

**Comment by mayukojpn** [comment]
Anyway @wgroenewold 's way worked for me. Thanks!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
