### ISSUE TITLE
Thumbs Gallery With Two-way Control doesn't work with loop

### ISSUE THREAD

**Issue by ghost** [nolimits4web/Swiper#1379]
Is it possible to get this working with loop?
If I add loop = true it just breaks.

Thanks

**Comment by nolimits4web** [comment]
You have to enable loopedSlides parameter and specify the same parameter for both sliders there

**Comment by kireerik** [comment]
Thank you for submitting and replying this issue! It is really useful for me as well.

According to my experience we need to specify the half of the number of the slides for the `loopedSlides` parameters. So here is a calculation example which is using jQuery (which is not necessary of course, it can be calculated with pure JavaScript as well):
```JavaScript
loopedSlides: $('.gallery-top > .swiper-wrapper > .swiper-slide').length / 2
```

Although this works fine, there are still some (loading like) glitch sometime when you interact with the `.gallery-thumbs` part.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
