### ISSUE TITLE
No horizontal drag if dragging move trajectory accidentally starts with vertical(ish) move [desktop]

### ISSUE THREAD

**Issue by andreyvolokitin** [nolimits4web/Swiper#1425]
If we start to drag Swiper horizontally, but not strictly in "horizontal" manner (i.e. if we misdirect our mouse at the start of horizontal dragging move, and first will drag it more vertically than horizontally, or just plain vertically for a split second) - then the actual horizontal drag may not start at all. See screencast demo: https://www.dropbox.com/s/3orfww82uk196nz/2015-09-04_10-58-31.mp4?dl=0. Here every mouse move from top-right to the bottom-left is a drag attempt. As you can see not every attempt is successful. In real life scenario this case accidentally may happen pretty often. I did not check it on touch devices or in vertical mode but I think in those cases behavior might be similar.

**Comment by nolimits4web** [comment]
Mouse drag is actually just as a bonus, as navigation with mouse dragging is not what users expect on desktop/mouse devices. Such behavior is by design because on vertical drag (on touch devices) it works exactly like that, because with vertical dragging we have and expect page scrolling. You may play with `touchAngle` parameter to tweak it

**Comment by anrikun** [comment]
Why don't you accept this as a bug? No other slider has this problem with horizontal mouse drag. Can't we just try to fix it?
This is really an annoying issue because users end up clicking the slide when they expect to swipe it.
