### ISSUE TITLE
[FIX] Preloader CSS animation is CPU heavy

### ISSUE THREAD

**Issue by henrik** [nolimits4web/Swiper#1451]
I'm afraid I don't want to take the time to verify this against the latest Swiper (we use 3.0.6) or to make a proper PR, but:

We noticed a page using a lot of CPU (in Chrome's Task Manager). One of the culprits was `.swiper-lazy-preloader`. We did a small change that reduced CPU usage on my 2013 MacBook Pro by around 3 percentage points (from 3.5% to 0.5% on this page).

Before:

```
.swiper-lazy-preloader {
  // …
  animation: swiper-preloader-spin 1s steps(12, end) infinite;
}
```

After:

```
.swiper-lazy-preloader {
  // …
}

// Don't animate spinners in hidden slides. This reduces CPU usage significantly.
.swiper-slide-active .swiper-lazy-preloader {
  animation: swiper-preloader-spin 1s steps(12, end) infinite;
}
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
