### ISSUE TITLE
Custom id attribute

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [nolimits4web/Swiper#1469]
Hi, my swiper is integrated with my database, so I need to store on each slide a custom field called 'id' that will be the id of the photo on my database. Is there a way to add custom fields to slides? I'd have to eventually remove that slide later by it's id and not the slide index (0,1,2,3....)
Is there a workaround for this ?

**Comment by AlbertNowotny** [comment]
hi,
if you're not using `loop` option in swiper then it should be very easy, just add the respective 'id' attribute in each slide when you build the html of the slideshow (eg. in php: `echo '<div class="swiper-slide" id="`.$id-from-db.`"></div>'`)

Then in with jquery when you need to remove the slide: `swiper.removeSlide($('#your-slide-id').index());`
(in plain javascript is a bit more verbose since you need to loop through each slide to get the index)

In case you are using swiper `loop` option then it's better to use a data attribute instead of the reserved attribute 'id' (because there should not be duplicates of nodes with same id and `loop` duplicates slide nodes)

**Comment by shactdeveloper** [comment]
Hello! thanks for your help! 
I couldn't understad what does loop refers to by reading the docs, could you give me some explanation?
I'm using MeteorJS and building my slides like this:
Whenever a document (from mongo) is sent down from the server to the client, I use appendSlide.
When a document is removed, I must find out the index of that specific id on my array of slides, to remove the correct one. For that, im storing the relation between "slide index" and "id from db" on an array and I think it's pretty verbose... However, it's working. I would like to know if there is a shortcut

**Comment by nolimits4web** [comment]
> I must find out the index of that specific id on my array of slides

As @AlbertNowotny it should be easy, the index is just `$('#your-slide-id').index()`. You shouldn't pay a lot of efforts to it. But anyway, it would be good to see some code examples to better understand what problem do you have

**Comment by nolimits4web** [comment]
I think we can close it as there is no further discussion
