### ISSUE TITLE
Being able to customise pagination count

### ISSUE THREAD

**Issue by stephanebachelier** [nolimits4web/Swiper#1478]
Hi @nolimits4web ,

I've an issue when I need to display a slider with a pagination but with more than one slides per view. By default I will have the same number of pagination bullets than number of slides. 
In my case I need to have the number of pagination bullets to be not the slides.length but the number of pages.

Is there a simple way or do I need to make a PR ?

**Comment by nolimits4web** [comment]
Actually by default it is equal to number of "slide breakpoints" or "pages" (amount of how many times you can slide), not to number of slides, at least it is not always the same and depends on configuration

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
