### ISSUE TITLE
Adding parallax: true stops onSlideChangeEnd from firing depending on swipe

### ISSUE THREAD

**Issue by emilynewsom** [nolimits4web/Swiper#1484]
If you add parallax: true to a swiper, the onSlideChangeEnd callback won't get called depending on the type of swipe that is performed. I've tested this in FF, Chrome with mouse swipes and Mobile Safari with finger swipes and the bug exists in all.

Here's a pen where I added parallax: true to your first demo:
http://codepen.io/bfcam/pen/ZbRJmY

If you do a quick short swipe the callback gets called. Try dragging the next slide part way, then pausing for a split second, then releasing. The callback won't be called. I can reproduce this every time.

I haven't looked into a possible fix at all.

**Comment by nolimits4web** [comment]
It is because with `parallax` the `watchSlidesProgress` option will be also enabled, which changes slides during touchmove. You can use `onTransitionStart`/`onTransitionEnd` callbacks instead

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
