### ISSUE TITLE
polymer

### ISSUE THREAD

**Issue by joeblew99** [nolimits4web/Swiper#1506]
would be good to wrap with polymer 1.1
i saw in the past #581 issue someone tried to use the old polymer 0.5

**Comment by nolimits4web** [comment]
And what is the issue?

**Comment by joeblew99** [comment]
no issues. its a feature request

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue
