### ISSUE TITLE
Mousewheel event outside the container ?

### ISSUE THREAD

**Issue by acorb** [nolimits4web/Swiper#1524]
Hey,
Thank you for this great plugin.
I've searched and found an answer for this issue, but it looks like the code has changed in the meantime. Is it still possible to catch the mousewheel event on the whole page and not only while hovering the container ?
Thanks !

**Comment by nolimits4web** [comment]
No, it is not supported by default. You probably can modify source code by changing event assign from container to document or body at https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L3027

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue
