### ISSUE TITLE
Bug with Youtube videos

### ISSUE THREAD

**Issue by mabilbao** [nolimits4web/Swiper#1554]
Hi guys,

My name is Martin and I tried to make an example mixing Swiper and Youtube but I have a strange problem when I put a lot of videos in the same Swiper and I press the Youtube play button in the iframe (I know, is very strange).

Here you can look a very simple example: http://dev.shifteight.com/swiper-example/example.html

If you try clicking on the youtube button, you can see how the swiper takes you one or two slides to the right. This problem only happens if you press in the Youtube play button.

Here have a video with my problem: https://drive.google.com/file/d/0B78lwXNuLbR-V2tZbTJXaERsU1k/view

Thanks!

**Comment by nolimits4web** [comment]
Looks really weird, and only in Chrome. Looks like pure browser issue, as it is actually not really possible as this button is in iframe and click on it doesn't affect main window and scripts. Looks like pure Chrome issue

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
