### ISSUE TITLE
A bug, Conflict with zepto‘s tap event

### ISSUE THREAD

**Issue by xuetian120** [nolimits4web/Swiper#1562]
If the scroll area has a a link,  zepto with tap event, then conflict with zepto‘s tap event, Can't stop a click

**Comment by nolimits4web** [comment]
Need to see live example or JSFIddle

**Comment by xiguaaxigua** [comment]
You shoule replace Zepto`s tap event with **FastClick**. Google it!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
