### ISSUE TITLE
vertical mouse drag not working in chrome on windows

### ISSUE THREAD

**Issue by cMack87** [nolimits4web/Swiper#1575]
horizontal works great, vertical mouse interactions don't work.

if i mash both mouse buttons while moving the mouse it magically works for a moment here and there, very confusing!

tested in IE, works just fine.

var swiper = new Swiper('.swiper-container', {
        direction: 'vertical',
        freeMode: true,
        freeModeSticky: true,
        slidesPerView: 'auto'
    });

**Comment by iischwuerfl** [comment]
I'm having the same issue here! 

Also the demos don't work in Chrome, but they work as expected in Firefox

**Comment by naoyeye** [comment]
hi all, did you try to close the chrome tab then reopen again? that's worked for me.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
