### ISSUE TITLE
Jquery UI draggable inside swiper does not work in IE

### ISSUE THREAD

**Issue by tobbelindbom** [nolimits4web/Swiper#1578]
When making slides draggable with jQuery UI, the drag start event never triggers in Internet Explorer. This seems to be caused by Swiper use stopPropagation on touchstart/MSPointerDown unless it is a form element. In other browsers this works fine, may be events bubble in different order...
It is possible to set "touchMoveStopPropagation", but there is no such setting for "touchStartStopPropagation" in the API.
Not sure what the effect would be on a Windows touch device if the propagation is allowed, but for desktop it would solve the problem. Maybe there is another workaround?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
