### ISSUE TITLE
onSlideChangeStart event not fired after drag started and stopped

### ISSUE THREAD

**Issue by dhudec** [nolimits4web/Swiper#1579]
If you start to drag a slide but stop before the transition is fully triggered, the onSlideChangeStart event will not be fired on subsequent transitions to that page. 

I tracked this down to the following condition that checks if s.activeIndex !== s.previousIndex:

<pre>
if (s.activeIndex !== s.previousIndex) {
    s.emit('onSlideChangeStart', s);
    if (s.activeIndex > s.previousIndex) {
        s.emit('onSlideNextStart', s);
    }
    else {
      s.emit('onSlidePrevStart', s);
    }
}
</pre>

I observed that after starting to drag a slide but stopping, subsequent page transitions to this page have s.activeIndex == s.previousIndex, so the event is never emitted.

I suspect the bug is caused by the fact that the slideTo method updates the previousIndex to the activeIndex before calling onTransitionStart:

<pre>
// Update Index
if (typeof speed === 'undefined') speed = s.params.speed;
s.previousIndex = s.activeIndex || 0;
s.activeIndex = slideIndex;

if ((s.rtl && -translate === s.translate) || (!s.rtl && translate === s.translate)) {
    // Update Height
    if (s.params.autoHeight) {
        s.updateAutoHeight();
    }
    s.updateClasses();
    if (s.params.effect !== 'slide') {
        s.setWrapperTranslate(translate);
    }
    return false;
}
s.updateClasses();
s.onTransitionStart(runCallbacks);
</pre>

**Comment by nolimits4web** [comment]
It depends on Swiper settings but activeIndex can be changed during dragging, so the callback won't fire. You can use `onTranstionStart` instead in this case

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
