### ISSUE TITLE
Scrollwheel Not Working on IE 11

### ISSUE THREAD

**Issue by chrisdressler** [nolimits4web/Swiper#1586]
When implementing a standard vertical slider with the following code (this was using the default 03-vertical demo HTML code), the mouse wheel scrolling doesn't work properly in IE11:

`var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        direction: 'vertical',
        keyboardControl: true,
        mousewheelControl: true
    });`

The keyboard keys work (up and down), and I can drag the swiper between slides OK, but when trying to scroll with the mouse wheel nothing happens. Further, if I use the keyboard arrows to scroll down a couple of slides, then try and use the mouse wheel, it starts scrolling the slides, but only in the reverse direction (back towards slide 1) no matter which way you scroll the mouse wheel (up or down). Once you scroll back to slide 1, the mouse scroll wheel stops working again. I also verified this same behavior with the 03-vertical demo.

**Comment by davaipoka** [comment]
the same problem, anyone have a solution?

**Comment by nolimits4web** [comment]
Guys, it was fixed here https://github.com/nolimits4web/Swiper/commit/42c7b14568d29ed828c726a747aef9d574701857

You can grab dev version with this fix

**Comment by chrisdressler** [comment]
I built the dev version and it fixes this problem, thanks!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
