### ISSUE TITLE
slidesOffsetBefore so that first image is flush to the left while rest are centered?

### ISSUE THREAD

**Issue by cmpex** [nolimits4web/Swiper#1589]
Is there a way to have the first element be flush to the left while rest of the images are centered with `loop` is set to true?

Been tinkering around with the javascript and was able to "hack" the swiper so that even if `centeredSlides` is set to true, the first one is always at `slidePosition = 0` but then if I enable loop mode, the first image is centered again.

If anyone has any hints or suggestions on a good way to implement this, I'd appreciate it.

Thank you!

**Comment by nolimits4web** [comment]
Didn't really get what you are trying to achieve, do you have live example or JSFiddle?

**Comment by saurabhkohli** [comment]
Hi I too have a similar problem where I want the first and last slide to be fixed positioned based on the offset and rest should be center aligned. Below is the codepen for the same
Please check the pen in mobile / ipad view
https://codepen.io/saurabhkohli/pen/GEWORM

**Comment by tmeloliveira** [comment]
Did any of you managed to solve this in the end?
I'm also trying to achieve the same behavior...

**Comment by saurabhkohli** [comment]
Please check my post on https://github.com/nolimits4web/Swiper/issues/2078.
This will help you resolve your issue for now.

Thanks!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
