### ISSUE TITLE
How to use swiper in touch (mobile) when I want to "Pinch"(two fingers to zoom) and "move"(one finger to move around)

### ISSUE THREAD

**Issue by kk580kk** [nolimits4web/Swiper#1595]
How to use swiper in touch (mobile) when I want to "Pinch"(two fingers to zoom in) and "move"(one finger to move around) with picture

I found the swiper api will change the pages ,but not the move action ,when I already zoom in the pictrure and I want to see different place of the picture.

The zoom in is support by web broswer and it can be disable by 
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"  />`
but I don't have any option to alter this function(zoom in)

**Comment by kk580kk** [comment]
I use a baidu touch javascript library to solve this problem.
There are their website http://touch.code.baidu.com .

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
