### ISSUE TITLE
Swiper with next-/prev-buttons doesn't change slide correct in IE

### ISSUE THREAD

**Issue by halloalexkern** [nolimits4web/Swiper#1605]
The next/prev navigation buttons are not working in Internet Explorer (11 and Edge).
When clicking next it slides to the correct slide but then jumps back to the initial slide immediately.

Swiping with mousedrag however works.

(e.g. in Navigation Buttons Demo) 

:-) AK

**Comment by nolimits4web** [comment]
Can't replicate this issue, works fine for me. Would be good to know a bit more how to replicate it

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
