### ISSUE TITLE
Firefox overflow issue with cube

### ISSUE THREAD

**Issue by macsupport** [nolimits4web/Swiper#1613]
In Firefox (v44.0.2), using the cube setting, there is an overflow issue where the page scrolls the x and y axis endlessly. Here is a [Codepen](http://codepen.io/macsupport/full/jWJLjz/) using your swiper playground example.

**Comment by nolimits4web** [comment]
It is Firefox's issue. Caused by slides and cube's shadows. You can disable them or wrap cube with a div with `overflow:hidden`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
