### ISSUE TITLE
onSlideNextEnd in firefox not executed

### ISSUE THREAD

**Issue by desislavsd** [nolimits4web/Swiper#1617]
No matter which callback i use - onSlideChangeEnd or onSlideNextEnd, when sliding to the right the callback is not executed in Firefox. However, in the opposite direction it works fine. I don't have this problem with Chrome and IE, just in Firefox.

**Comment by nolimits4web** [comment]
Can't replicate it. Do you have live example or JSFiddle with the issue?

**Comment by sailorkoto** [comment]
Have absolutely the same issue. If I have time, I will try to prepare an example.

**Comment by nolimits4web** [comment]
But i still can't replicate it :) Need to see example with the issue

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
