### ISSUE TITLE
Expose method to end scrollbar drag.

### ISSUE THREAD

**Issue by tonytopper** [nolimits4web/Swiper#1622]
I am trying to end a scrollbar drag if the mouse pointer leaves the document.

I have some code that adds a class to swiper-scrollbar-drag when the user is currently dragging the scollbar.

```
function scrollBarEnhance(swiperObject) {
    $('.swiper-scrollbar', swiperObject.$).on('mousedown', function(event) {
      var $me = $(this);
      var $myDrag = $me.find('.swiper-scrollbar-drag');

      $myDrag.addClass('swiper-scrollbar-drag--active');
      $('body').one('mouseup.scrollbadDrag', function(event) {
        $myDrag.removeClass('swiper-scrollbar-drag--active');
        $(document).off('.scrollbadDrag');
      });
      $(document).one('mouseleave.scrollbadDrag', function(event) {
        $myDrag.removeClass('swiper-scrollbar-drag--active');
        $('body').off('.scrollbadDrag');
      });
    })
```

However the mouseleave event doesn't disengage the dragging and I can't figure out a way to do that with the Swiper API.   Would be great to have a method exposed in the API to do this.

**Comment by soldiercnorm** [comment]
+1

**Comment by jskorupski** [comment]
+1

**Comment by nolimits4web** [comment]
Sorry, didn't understand where is the problem. Can you explain it more detailed or maybe with examples or something else like video?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
