### ISSUE TITLE
"jumpy" behavior with slidesPerView:'auto', centeredSlides and loop: true

### ISSUE THREAD

**Issue by filipemerker** [nolimits4web/Swiper#1629]
I have a lot of swipers in my page, but one of them is baheving very weirdly. It look like it restart after every swipe the user does.

I'm using this configuration:

```
var a  = new Swiper('.slider-market-mobile', {
              slidesPerView: 'auto',
              spaceBetween: 20,
              loopedSlides: 1,
              centeredSlides: true,
              watchSlidesVisibility: true,
              parallax: false,
              loop: true,
              height: 'auto',
              paginationClickable: true,
              effect: 'slide'
            });
```

Swiper's default css and js are being added in codepen's settings, the version is 3.3.1.

This codepen is just a copy of my Drupal generated markup, so it's kind of a huge markup, but the behavior is very much isolated, so the error i'm getting in the website is the same in the pen.

To reproduce the error, follow the steps below:
1. Enter http://codepen.io/filipemerker/pen/PZMGNB
2. Use the cursor to drag and swipe the slides.
3. Note that it keep looping through the first and second slides.

**Comment by nolimits4web** [comment]
Can't really see anything wrong. But for `loop: true` and `slidesPerView: 'auto'`, `loopedSlides` parameter is mandatory! I can't see it code pen. Try adding `loopedSlides: 10`

**Comment by pruthvip** [comment]
is there any issue with loopedSlides as 1

**Comment by nolimits4web** [comment]
loopedSlides should be more than you have maximum amount of visible slides per screen

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
