### ISSUE TITLE
Autoplay option does not work in Safari

### ISSUE THREAD

**Issue by damhonglinh** [nolimits4web/Swiper#1633]
Reproduce step:
- Open a page with a Swiper with autoplaying.
- Open that page in a second tab.
- Play around with the second tab (click on the `nextButton` or `prevButton`).
- Go back to the first tab and the autoplay does not work anymore, neither the `nextButton` nor `prevButton` works. However, clicking on the pagination still works.

My swiper options are:

``` javascript
new Swiper('.selector',
  { autoplay: 3000,
    pagination: '.swiper-pagination',
    nextButton: '.swiper__next-btn',
    prevButton: '.swiper__prev-btn' }
```

After investigating, here is what I could find:
- `s.animating` is true when calling function `s.slideNext()`
- `s.animating` is true because it is set to true when calling function `s.slideTo()` (at the end of the function). `s.animating` is intended to set back to false in the `transitionEnd` event's callback. However, the callback for `transitionEnd` is not called when switching tab in Safari.

Additional info:
- Swiper version: `3.3.1`
- Safari version: `9.0.3 (10601.4.4)`

**Comment by damhonglinh** [comment]
My temporary solution is:
```javascript

var homeBanner = new Swiper('.selector', {/* some options */});
(function fixSafariSwitchingTab() {
      if (!homeBanner.isSafari) return;

      $(window).focus(function() {
        if (homeBanner.animating) {
          homeBanner.animating = false;
          homeBanner.stopAutoplay();
          homeBanner.startAutoplay();
        }
      });
    })();
```

**Comment by levani** [comment]
The same thing happens in chrome for me also.

This is my configuration:

```
loop: true,
slidesPerView: 3,
autoplay: 50,
breakpoints: {
	910: {
		slidesPerView: 1
	},
	1300: {
		slidesPerView: 2
	}
}
```

**Comment by nolimits4web** [comment]
Try to use forum search. There were few solutions. It happens because browser stops/slows down timeouts in hidden browser tabs. You may use Page Visibility API in your JS to stop or start autoplay when tab becomes hidden or visible https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by levani** [comment]
@nolimits4web I don't think slowing down timeouts isn't the reason in my case because I never switched tabs while testing this.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
