### ISSUE TITLE
Remove lazyload onerror.

### ISSUE THREAD

**Issue by greg-md** [nolimits4web/Swiper#1637]
You should remove this line `image.onerror = onReady;` because if image doesn't exists, i want to display the loading image. Or you can set up an option for this.

Link: https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L517

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
