### ISSUE TITLE
fade effect doesn't autoplay in version 3.3.1

### ISSUE THREAD

**Issue by japiera** [nolimits4web/Swiper#1639]
Hi!!

I'm encountering same problems than in #1177, but with version 3.3.1 of Swiper. Swiper only slides form the first to the second slide,  afer that, it stops without any error.

It's the same situation: I'm setting a value to autoplay and 'fade' to effect. Id I do'nt set the effect it works correctly.

Thanks

**Comment by nolimits4web** [comment]
everything works good here https://jsfiddle.net/4gtndbw1/

**Comment by japiera** [comment]
OK, thanks for your attention.

I'm trying to reproduce this issue in jsFiddle with all my options and i'm not getting it but with my code  in my server, there is it.

For now I'm going to disable fade option until I get time to spend with this. I'll return to try this later and report if I find the reason I'm having this issue

**Comment by azaleas** [comment]
Even though so much time has passed, I would like to add my 2 cents. I hade the same issue as @japiera on version 3.3.1. It turns out, in my case, it was speed parameter that was messing it up. I was passing the parameter as string (from html data attribute). Once I changed it to int (ith parseInt) it was working again. Anyways, hope it helps someone out there.
