### ISSUE TITLE
Trackpad issue with nested swipers

### ISSUE THREAD

**Issue by toru-sean** [nolimits4web/Swiper#1641]
If you nest swiper instances and don't set the nested swipers to move in a different direction (as the demo does) then they seem to got mixed up on which one should be advanced when you swipe to next/prev. 

See Codepen example...
http://codepen.io/toru-sean/pen/reMNGg

Every few sipes the cube rotates when it shouldn't. It only happens with trackpads, works fine with mouse or mobile. (that's Apple trackpads, I've not got a PC to test it on right now)

I've also posted to stack overflow just in case that might get answered quicker...
http://stackoverflow.com/questions/35940847/nested-swipers-on-the-same-axis-get-mixed-up-trackpad-only

**Comment by nolimits4web** [comment]
Ok, have the Apple MBP with trackpad as well, and can't really see the issue, actually there is no and shouldn't be difference between mouse/trackpad. Don't know maybe i didn't understand the issue, then some video screen capture would help more

**Comment by toru-sean** [comment]
![cube](https://cloud.githubusercontent.com/assets/8126322/13705203/aab7cfe4-e797-11e5-83b7-98f958ec159b.gif)

Hi, please see attached gif. I tried to swipe from A to H and then back again.

**Comment by nolimits4web** [comment]
Sorry, don't know what happens in your case but i still can't replicate it on MBP's trackpad

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
