### ISSUE TITLE
onSlideChangeEnd not called on Windows Mobile 8.1

### ISSUE THREAD

**Issue by makkeu** [nolimits4web/Swiper#1661]
Looks like this [commit](https://github.com/nolimits4web/Swiper/commit/42ca73e566e3f0e13e851ce92b564494fcb8237e) broke onSlideChangeEnd on Windows Phone 8.1 (tested on Lumia 630). This can be reproduced in demos/02-responsive.html by adding `swiper.on('onSlideChangeEnd', function(){alert('end')});`

I tried to revert s.setWrapperTransition/Translate line order and it fixes the issue. I'm not sure why this change causes that?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
