### ISSUE TITLE
Swiper thumb gallery bug

### ISSUE THREAD

**Issue by jasonweng** [nolimits4web/Swiper#1666]
If the thumbs list width < container width, it didn't swipe to next thumb, please see attached:

`swiper-slide-active` and `swiper-slide-next` class didn't change and click on thumb didn't work too.

<img width="993" alt="screen shot 2016-03-30 at 5 50 15 pm" src="https://cloud.githubusercontent.com/assets/84782/14138489/17e06f1a-f6a0-11e5-8614-534d41fbd9d8.png">

<img width="1078" alt="screen shot 2016-03-30 at 5 54 16 pm" src="https://cloud.githubusercontent.com/assets/84782/14138571/772ccacc-f6a0-11e5-8e5c-aa6b24608c9d.png">

But if thumbs list width > container width, it works well.

Please check it out. 

Here is my code

```
    var galleryTop = new Swiper('.products__gallery--top', {
              spaceBetween: 0
          });
          var galleryThumbs = new Swiper('.products__gallery--thumbs', {
              spaceBetween: 16,
              slidesPerView: 'auto',
              touchRatio: 0.2,
              slideToClickedSlide: true
          });
          galleryTop.params.control = galleryThumbs;
          galleryThumbs.params.control = galleryTop;
```

**Comment by nolimits4web** [comment]
Is it still relevant?

**Comment by intsitesdotru** [comment]
Да, если не сложно.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
