### ISSUE TITLE
Really buggy slide animation on winphone 8.1

### ISSUE THREAD

**Issue by Overpowered** [nolimits4web/Swiper#1671]
Hi,
first thx for this great PlugIn but on winphone it doesn´t works great any time longer. If I slide any of your slides, for example at your demo page, the slide animation will be cut and really jumpy. By sliding (touch) I only see that the div, that I want to slide, jumps back and the new div (the next one) will be shown. If I use the pagination or arrows, every second slide-div slides, the rest have the same problem. Thats confusing ;(. I have tested the different versions of swiper and found out that this happened till version 3.2.0 (3.1.7 all fine). I think there is maybe a connection between the new and great feature "breakpoints" and this animation cut?

I hope anybody can fix this!?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
