### ISSUE TITLE
Lazy / slidesPerView: auto / centeredSlides

### ISSUE THREAD

**Issue by PixelZombie** [nolimits4web/Swiper#1679]
Hey there,

I've got and i'm out of ideas how to solve it if even possible. Could you please have a look at my pen?
http://codepen.io/PixelZombie/pen/YqedZV

I'm trying to lazy load images (1 per slide). The first slide should be centered. Looping is also enabled and should show the duplicated slides left from the first. The images have different aspect ratios so I need `slidesPerView: 'auto'`. 

The settings are

```
slidesPerView: 'auto',
preloadImages: false,
lazyLoading: true,
lazyLoadingInPrevNext: true,
loop: true,
loopedSlides: 5,
watchSlidesVisibility: true,
centeredSlides: true,
```

I think i have tried a hundred combinations of options and i'm getting all kinds if issues like
- all images are loaded (not lazy) as soon as I enable `watchSlidesVisibility`
- every slide gets the class `swiper-slide-visible` even if they aren't visible.
- swiping resets the slider to the first slide sometimes
- slides disappear
- swiping is bumpy
- works a bit better after resize

Could you please point me in the right direction on how to setup this slider?

Thanks a million in advance and keep up the good work!

**Comment by nolimits4web** [comment]
Oh man, don't know even how to solve this. The problem here, is that all slides have no sizes at the startup, so it loads images in all slides considering them visible...

**Comment by amitcw** [comment]
@nolimits4web When we can get solution for this issue, can you update a code with solution of lazyload with slidesperview:'auto'

**Comment by a-zharkov** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
