### ISSUE TITLE
Source maps missing

### ISSUE THREAD

**Issue by alexVauch** [nolimits4web/Swiper#1683]
There is no source map files for non-minified versions. Next files are missing:
- maps/swiper.jquery.js.map
- maps/swiper.jquery.umd.js.map
- maps/swiper.js.map

**Comment by matthussey** [comment]
You don't need source maps for unminified code do you?

**Comment by alexVauch** [comment]
If so - _sourceMappingURL_ comments should be removed from those files.
`//# sourceMappingURL=maps/swiper.jquery.umd.js.map`

**Comment by yekver** [comment]
Let's remove this, guys?)

**Comment by julmot** [comment]
I'm also experiencing 404 messages when including Swiper using Webpack:

```bash
‼︎ 404: No matching route found for /compiled/maps/swiper.js.map
```

**Comment by julmot** [comment]
Ping @nolimits4web

**Comment by julmot** [comment]
For anyone interested in this issue and is using Webpack. Using string-replace-loader will work as a temporary workaround:

```javascript
    { // shim for libraries that are depending on a .map file (like Swiper)
      // github.com/nolimits4web/Swiper/issues/1683#issuecomment-316825698
      test: /\.js$/,
      loader: 'string-replace-loader',
      query: {
        search: '//# sourceMappingURL=(.*?).map',
        flags: 'gmi',
        replace: ''
      }
    }
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
