### ISSUE TITLE
Scrollbar not dragging

### ISSUE THREAD

**Issue by BenComicGraphics** [nolimits4web/Swiper#1684]
I have a site built with Swiper, but the scrollbar is not allowing draggability(Basically, I can click on the scrollbar's draggable area, but it doesn't actually manipulate the scroll of swiper).  

http://tango.steadfastlight.com/products/market-planning-site-selection/

Go here to see.  

`
 $(document).ready(function() {  
    var swiper = new Swiper('.swiper-container', {
        scrollbar: '.swiper-scrollbar',
        scrollbarDraggable: true,
        scrollbarHide: false,
        width: 225,
        centeredSlides: true,
        spaceBetween: 30,
        grabCursor: true
    });
});; 
`
is the code I'm using.  

EDIT: It does work on touch, but it does not work with a mouse.  
EDIT: it also works on IE, and Firefox.  Hmmm.... It appears to be only Chrome with this issue
EDIT: OK!  I know what it is!  On Chrome, on a Windows PC with a TOUCHSCREEN, the scrollbar will not be draggable via mouse, even if you are using a screen that isn't touch driven(external monitor).     

I guess, at this point, this is more of a feature request than a bug fix, since this is a very unique use-case.

**Comment by jskorupski** [comment]
I can confirm this issue - I am running Chrome + Windows 8.1 + Touchscreen laptop screen

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
