### ISSUE TITLE
[Feature Request] Different Speed values based on user input

### ISSUE THREAD

**Issue by thomas-dm** [nolimits4web/Swiper#1688]
Hello,

This issue is more of a feature request, as I do not believe it’s currently possible with the latest revision of Swiper.

I think it’d be really neat to allow developers to set different parameters based on the kind of user input (touch, nav click, mouse drag, keyboard...), particularly speed values. For instance, I think it would be really useful if we could set a higher speed value when the user swipes and a lower one when they use their keyboard keys, as a touch-based input usually implies a faster gesture. A 1000ms transition could feel nice when tapping a “Next” button but wrong and too slow after a swipe.

Granted, the `breakpoints` option already allows for such fine-tuning based on the viewport size, but as devices get more and more diverse every day, it is no longer safe to assume a touch-based input on smaller screens and vice-versa.

I also imagine this kind of settings could be achieved using callbacks, but it could get pretty messy pretty quickly. An option like the super convenient `breakpoints` would be perfect.

Anyway, this, I feel, is one of my main requests after having used Swiper on many projects over the years.

Thank you & keep up the amazing work!

**Comment by nolimits4web** [comment]
I will think about implementing it. But, at the moment, you can always change it by changing `speed` parameter whenever you want (in callbacks, when click something, etc.),  e.g. `swiper.params.speed = 2000`

**Comment by dgalef** [comment]
This featured would be amazing.

**Comment by nicmare** [comment]
i upvote and subscribe for it! i really need slow fading transitions when autoplaying. but fast slide transitions when swiping. in meantime try to use iOS-Slider if you really need different speed params. 
similar feature request: define different transitions effects. for instance: while autoplaying i need fading. but when swiping left/right, i need sliding instead of fading.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
