### ISSUE TITLE
Chrome console warning

### ISSUE THREAD

**Issue by A-limon** [nolimits4web/Swiper#1704]
With latest Chrome and Swipe, open the dev tools, In the console showed a warning: 
Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

**Comment by luck2011** [comment]
+1
this also freeze the chrome tab! see https://bugs.chromium.org/p/chromium/issues/detail?id=574343

**Comment by MadeInMoon** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
