### ISSUE TITLE
multi row + loop

### ISSUE THREAD

**Issue by ViktorChernyaev** [nolimits4web/Swiper#1711]
добрый день! использую ваш слайдер, очень нравится, нашел в нем баг(а может это и не баг).
при использовании опций  slidesPerView:  1, slidesPerColumn: 2 и loop: true слайдер себя ведет странно, у меня в проекте влево крутит исправно по петле, а вправо крутит только до конца слайдов. сделал jsfiddle(разметка, стили и скрипт с демо-примеров, только добавил loop):
https://jsfiddle.net/bagunok/zah3ppn4/

**Comment by nolimits4web** [comment]
Добрый! К сожалению, в данный момент эти опции не совместимы

**Comment by marcodussin** [comment]
up

**Comment by itoufo** [comment]
+1
using slidesPerColumn and loop:true cause invalid pagination.
i hope to be fixed.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
