### ISSUE TITLE
Double Clicking navigation buttons causes slideshow to stick

### ISSUE THREAD

**Issue by philipbjorge** [nolimits4web/Swiper#1714]
Visit http://idangero.us/swiper/demos/14-nav-arrows.html
Click the right arrow button
Before the slide has finished transitioning, click it again

Expected:
The slideshow progresses two images forward (or ignores the click and only progresses one)

Actual:
The slideshow gets stuck in the middle

**Comment by nolimits4web** [comment]
I guess Chrome + Windows?

**Comment by philipbjorge** [comment]
@nolimits4web -- Correct and sorry about omitting the browser and os, I assumed this affected all browsers.
I just verified that this is fine on Chrome on OSX.

Is this a known issue then?

**Comment by HADB** [comment]
Any updates? Still having the problem when using Chrome+Windows.

**Comment by JetLewis** [comment]
I confirm this bug is still triggering in Chrome + Windows, as of Swiper 3.4.1

**Comment by gogy27** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
