### ISSUE TITLE
coverflow effect not working in MS Edge

### ISSUE THREAD

**Issue by maulinpandya2006** [nolimits4web/Swiper#1715]
HI Vladimir,

This is a great plugin to use in as a multi purpose slider. Thank you for this build out.

While using Swiper 3 in my website I faced a critical issue in Windows 10 Edge V.25 latest browser (working fine in edge version 20). I have used Swiper 3 with coverflow sliding effect but when I show it on edge browser it looks weird. Slider images are getting blurred and when I tried to scroll it to next slide it will not working as it is in all other browsers.

You can check your own coverflow demo in same browser.

I request you to please check this issue from your side and suggest a solution to get it work in Edge browser properly.

Thanks,
Maulin

**Comment by mustdobetter** [comment]
HI Vladimir,

We're also experiencing the same issue. Any update on this?

Many thanks,

Jamie

**Comment by moosh74** [comment]
Same issue...
Any updates ?

**Comment by moosh74** [comment]
After few research on the web, it seems that preserve-3d is the problem.
No solution found at this time.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by sanderha** [comment]
@moosh74  Did you ever find a solution for this?
