### ISSUE TITLE
Touching with a second finger while dragging prevent sliding (iOS / UIWebview)

### ISSUE THREAD

**Issue by DjulLau** [nolimits4web/Swiper#1719]
First of all : great lib !
It working great on iOS / UIWebview.

However I have two small problems :
- If I start dragging and touch with a second finger and then release both fingers swiper will stay in this position (in between transition)
- If I start dragging with on finger and drag out the screen on the right it will stay in this position (in between transition). It will not do that if dragging out the screen on the left...

Any thoughts ?

Cheers,

Julien

**Comment by lemontree2000** [comment]
Me too. In the sliding process, another finger's touch will stick

**Comment by qiuzelct** [comment]
me too,when I slide page with two fingers,happen error

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
