### ISSUE TITLE
Thumbs Gallery With Two-way Control in Loop problem

### ISSUE THREAD

**Issue by candyshien** [nolimits4web/Swiper#1729]
I need help on " Thumbs Gallery With Two-way Control ", I add " loop: $(this).find('.swiper-slide').length > 1 ? true : false, " ... 

If only 1 images, the loop function still true... I want if only 1 images stop loopLfalse.....

https://jsfiddle.net/33rtLk4e/2/

If more then 2 images work fine, https://jsfiddle.net/33rtLk4e/3/

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
