### ISSUE TITLE
Problem with active pagination bulle

### ISSUE THREAD

**Issue by mtizziani** [nolimits4web/Swiper#1732]
Hello, i have problems with switching the active pagination bullet using Swiper 3.3.1 (Downloaded zip file from Homepage). Image swiping works perfect.

I am using the swiper.jquery.js from this bundle.

my HTML:

```
<!-- something before here -->
    <div id="swiperFrame" class="swiper-container">
        <div class="swiper-wrapper"></div>
        <div class="swiper-pagination"></div>
    </div>
<!-- something behind here -->
```

my Typescript:

```
class myClass {

    /**
     * @param: {Array<string>} input (Array of strings with the image url)
    */
    setSwiperItemsAndStart(input){

        // add all images as swiper slides
        for(var index in input) {
            $('.swiper-wrapper').append([
                $('<div>').addClass('swiper-slide').append([
                    $('<img>').attr('src', input[index])
                ])
            ]);
        }

        // set swiper options

        var mySwiperOptions = {
            pagination: '.swiper-pagination',
            paginationClickable: true,
            paginationHide: false,
            centeredSlides: true,
            loop: true
        };

        // start the swiper
        var mySwiper = new window['Swiper']('#swiperFrame', mySwiperOptions);
    }
}
```

I have to use jquery in version 1.11.3 because it is a cordova project with windows phone compilation (IE).

I found where the failure happens, swiper.jquery.js line 970: `$(this).index()` allways returns -1 and `current` is between 1 and n.

Do you have a fast workaround for me?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
