### ISSUE TITLE
mousewheel events triggering multiple times on FireFox

### ISSUE THREAD

**Issue by ndimatteo** [nolimits4web/Swiper#1735]
When I use the trackpad in conjunction with Firefox swiper slides are skipped over. The amount of slides that are skipped varies depending on how fast/long I scroll. This doesn't happen _as often_ on Safari or Chrome however.

You can see this in action here: http://dev.dcx.nickdimatteo.com

Source code is here: https://github.com/ndimatteo/dcx-theme

Any insight into why this is happening?

**Comment by ndimatteo** [comment]
Any input on this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
