### ISSUE TITLE
autoplay stops on Window Phone

### ISSUE THREAD

**Issue by jadedworks** [nolimits4web/Swiper#1751]
Hi,
on Window Phones with IE 11 autoplay stops working after the second slide.
I can reproduce this issue with the demo page.

Thank you!

**Comment by Hjsurk** [comment]
Issue still active in version 3.4.2 for Windows Phones. Autoplay works on the first slide but stops on the second one.

I'm using the following options on the slider:
slidesPerView: 1,
spaceBetween: 30,
grabCursor: true,
autoplay: 5000,
loop: true,
autoplayDisableOnInteraction: false,

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
