### ISSUE TITLE
In 3d Cube animation last slide image or first slide image dublicates.

### ISSUE THREAD

**Issue by Cyclops0571** [nolimits4web/Swiper#1752]
In saphari when i go back from first slider to last slider with sliding left to right first image shows up instead of last image.
In other browsers there is not such a problem.
Here is the sample for the problem.
http://www.galepress.com/banners/service_view/683

**Comment by datamann10** [comment]
i can second this
http://danian.website/photography/

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
