### ISSUE TITLE
Coverflow effect w/ bounding area problems on Chrome

### ISSUE THREAD

**Issue by kandebonfim** [nolimits4web/Swiper#1758]
Guys, I'm having trouble in chrome implementing swiper with coverflow effect. It seems like the prev/next slides got some weird boundaries when skewed and I'm not able to click on them in all its spots.
#### I added some background color on hover for demo purposes:

![swiper-issue](https://cloud.githubusercontent.com/assets/8906380/16271271/b5b52ee0-386f-11e6-995d-41f40b36e529.gif)

Any idea on how to fix this? I'm removing the effect anyway while I'm trying to fix it.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
