### ISSUE TITLE
[Bug] loop on cube effect

### ISSUE THREAD

**Issue by zhaoyao91** [nolimits4web/Swiper#1772]
If I set effect as cube and enable loop, and then slide it reversely, after the first image, the pagination and the 'inner mode' should be at the last image, but the displayed slide is the still the first image.

```
 this.swiper = new Swiper(this.refs.container, {
            pagination: this.refs.pagination,
            observer: true,
            autoplay: 5000,
            autoplayDisableOnInteraction: false,
            loop: true, // there is bug, see
            paginationClickable: true,
            preventClicks: false,
            effect: 'cube'
        })
```

![2016_07_05_15_48_42](https://cloud.githubusercontent.com/assets/3808838/16577481/1edcc0f6-42c8-11e6-943c-f7737b9b7186.gif)

**Comment by nolimits4web** [comment]
Hmm, can't replicate it. Can you please post link to example with the issue if it is still actual

**Comment by zhaoyao91** [comment]
sorry, this project has been updated for a long time, so I don't have any demo for now

**Comment by pe6o** [comment]
I entered the number of slides in the `loopedSlides` setting and it works. Without it, I have the same problem.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
