### ISSUE TITLE
Next & Pre button freeze the slider if click on them very fast 

### ISSUE THREAD

**Issue by dylannnn** [nolimits4web/Swiper#1780]
I've been told that my slider will stop working if the Next & Pre button been clicked fast, (3 times per second). Any ideas?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
