### ISSUE TITLE
Swiping left/right using 2 or more fingers do very wrong

### ISSUE THREAD

**Issue by gitlovenotwar** [nolimits4web/Swiper#1786]
The title says it all, when using 2 or more fingers while holding/dragging etc... it shows blinking things, it jumps from here to there.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
