### ISSUE TITLE
Z-index issues in latest IE (coverflow view)

### ISSUE THREAD

**Issue by K0ff33** [nolimits4web/Swiper#1789]
Hi, I have an issue with wrong z-indexes being applied to my slides in coverflow view in latest IE11.  They don't appear to be calculated correctly as slides to the right of the centred element overlap other slides. This doesn't happen in any other browsers (tested on Chrome, Firefox and Edge).

Here's my configuration:
`var swiper = new Swiper('.swiper-container', {
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    pagination: '.swiper-pagination',
    effect: 'coverflow',
    centeredSlides: true,
    slidesPerView: 2,
    mousewheelControl: true,
    mousewheelInvert: true,
    keyboardControl: true,
    spaceBetween: -500,
    coverflow: {
      rotate: 0,
      stretch: 0,
      depth: 600,
      modifier: 1,
      slideShadows: false
    }
  });`

I've also prepared a quick demo: [https://jsfiddle.net/LsKs/kqg02gjg/2/](https://jsfiddle.net/LsKs/kqg02gjg/2/).

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/8126512/16988574/bf8db5e8-4e88-11e6-8e66-a3adf61acf67.PNG)

IE11:
![ie11](https://cloud.githubusercontent.com/assets/8126512/16988576/c28ab412-4e88-11e6-85d4-a5214f664bc9.PNG)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
