### ISSUE TITLE
Swiper is hypersensitive on macBooks touchpad with horizontal inertial scrolling

### ISSUE THREAD

**Issue by jared83** [nolimits4web/Swiper#1791]
One "swipe", no matter how strong, should equal one slide. That is not the case on a MacBook's trackpad with inertial scroll, where one swipe often slides one than one slide.
You can see this behaviour on [this service ](http://deep-waves.com/)I am building right now.
The Swiper's documentation does not mention how to deal with inertial scrolling. 
The issue is so severe, that it is go or no go for Swiper on my service(s) / websites.
Cheers

**Comment by gmourasilva** [comment]
i think this is similar to #1810

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
