### ISSUE TITLE
Issues with a11y combined with centered slides and slidetoClicked

### ISSUE THREAD

**Issue by chrigi** [nolimits4web/Swiper#1795]
We use the swiper in a cordova application which we are trying to optimize for accessibility.
We enabled the a11y flag in the swiper parameters but have issues after selecting a tab on iOS.
The issue looks as follows:
Swiper with centered slides, showing 3 slides, total of 5 slides in swiper.
When we step through them using voiceover it works fine, the swiper scrolls through the slides but when I select e.g. the last slide, it shifts all the slides too much to the left and no slide is visible anymore. I can then also no longer scroll through them correctly and can't select them anymore.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
