### ISSUE TITLE
Nested swiper not working on ms edge

### ISSUE THREAD

**Issue by singlese** [nolimits4web/Swiper#1796]
We're using a nested swiper in our project. Works fine except on windows.
The Nested Swipers demo has the same problem. A vertical swipe by clicking works, but touch does not.
Any suggestions?
Thanks,
Sebastian

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
