### ISSUE TITLE
How to show part of the next slide

### ISSUE THREAD

**Issue by brightpixels** [nolimits4web/Swiper#1801]
I am showing 3 slides per view but I would like to show part of the fourth slide so the user knows there are more slides available. Is there an option for this?

**Comment by etuctida** [comment]
Via CSS, set your .swiper-slide width less than 33.3% (1/3) of container slide (because you want 3 slides). You can set 30% for your slide. So your three visible slides will takes 90% of the container. The 10% space will be show part of the next slide.
Then, change to slidePerView : 'auto'.
Hope it helps.
