### ISSUE TITLE
No mouse events (except click) on slides on IE10

### ISSUE THREAD

**Issue by 1le** [nolimits4web/Swiper#1809]
It appears that on IE10 slides don't receive mouse events, except for 'click'.

I was trying to add a handler that marks slides as selected on mousedown (I can't use click because the slides are cloned and can be dragged, i.e. I need the release event for other purposes). Unfortunately on IE10 the slide elements don't receive mouse/pointer down among other events.

Oddly enough - the same event from the right mouse button are detected.

Here is a fiddle:
http://codepen.io/ilianka/pen/Bzvygk

**Comment by 1le** [comment]
Issue seems to be related with "simulateTouch" setting. When set to false, the issue doesn't appear.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
