### ISSUE TITLE
slidesPer and spaceBetween problem

### ISSUE THREAD

**Issue by sinneren** [nolimits4web/Swiper#1812]
I set the slider with settings 

```
spaceBetween: 20,
slidesPerView: 2, \\3 for Desktop
slidesPerColumn: 5
```

And pagination. I have 37 slides. 
The problem is incorrect margin-top on some elements. Maybe it is becase Swiper calculate row and columns wrong. With 7 pages (1 page is 1 column and i thic it's bad) my data-swiper-column and -row id is:
`(column | row): 0|1 - 0|2 ... 0|0, 1|1 ... 1|0 etc.`

_And for every row = 0 is margin-top:0;_ 
wtf? 

Must I use only fixed number slides with my settings? How can I use any counts of slider and change it with type of device?

Не обратил внимания, что разработчик русскоговорящий . В общем, проблема с отображением колонок\строк. Если ставить 3 на строку и 5 на колонку, при этом слайдов не 15, а больше, то идёт 6 слайд идёт на следующую страницу, вместо переноса на колонку и у него убирается верхний отступ, как и у первого и так далее каждый 6. Можно решить если убрать его и навестить див на внутренний блок, но это в моём случае и не факт, что подойдёт другим и вообще костыль.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
