### ISSUE TITLE
Clicking next doesnt do anyithing if: slidesPerView: auto; direction: vertical; loop: true and container is higher than the sum height of slides

### ISSUE THREAD

**Issue by pilou** [nolimits4web/Swiper#1816]
config: {
  slidesPerView: 'auto',
  direction: 'vertical',
  loop: true,
}
Have 3 slides: 200, 100, 100 px height =>  SUM_HEIGHT = 400 = 200 + 100 + 100
- If container height is smaller or equals than SUM_HEIGHT it works as expected: http://codepen.io/anon/pen/kXqXdP
- If container height is bigger than SUM_HEIGHT loop wont start after last real slide: http://codepen.io/anon/pen/rLRrxZ

The diff of the two pens is only the .swiper-container {height: 400px vs 401px}

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
