### ISSUE TITLE
a bug about `effect`value is `coverflow`

### ISSUE THREAD

**Issue by semi-xi** [nolimits4web/Swiper#1830]
``` javascript
var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        effect: 'coverflow',
        grabCursor: true,
        centeredSlides: true,
        slidesPerView: 3,
        loop:true,
        coverflow: {
            rotate: 50,
            stretch: 0,
            depth: 100,
            modifier: 1,
            slideShadows : true
        }
    });
```

this is what i setting 。
the img length is 4。
i find a bug about that，when i slideright  for 3times， the left img is disappear，after slideright one more，the left pic is appear ，but if i only slideleft ， this situation can not find。

**Comment by nolimits4web** [comment]
Just try to increase `loopedSlides` parameter

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
