### ISSUE TITLE
Large .pack file slowing cloning and npm installing a fork

### ISSUE THREAD

**Issue by larrybotha** [nolimits4web/Swiper#1835]
There's a large .pack file sitting at `.git/objects/pack/*.pack` killing clone time, and making `npm i`ing a clone slow, too.

I'm not sure this is something that a collaborator can fork and fix, based on this discussion: https://github.com/gecube/opencaesar3/issues/95

http://stackoverflow.com/a/24693485/895007

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
