### ISSUE TITLE
loop not work correct with multirow

### ISSUE THREAD

**Issue by zorn-v** [nolimits4web/Swiper#1837]
You cannot swipe to the right at loop end and have strange effects with some combinations
e.g. 3x4 grid with 20 items

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
