### ISSUE TITLE
I hope make it to a component of React.

### ISSUE THREAD

**Issue by minooo** [nolimits4web/Swiper#1838]
I think it's will be cool,,,,,Don't you think so?

**Comment by nicholas-b-carter** [comment]
https://github.com/kidjp85/react-id-swiper

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
