### ISSUE TITLE
Slide and Rotate effect help

### ISSUE THREAD

**Issue by ndamofli** [nolimits4web/Swiper#1839]
Hi everybody. I've been trying to achieve create a custom effect for our beloved swiper slider, and i was hoping someone might have an idea to help me.
You can see the animated gif to see how it should be
![untitled-1](https://cloud.githubusercontent.com/assets/1918350/18206446/6b6e3bd0-712f-11e6-8e33-f94b77963bb9.gif)

Ideally the transition would be 3D (with perspective)
![comp-1_3](https://cloud.githubusercontent.com/assets/1918350/18208129/d6dbbc2e-7136-11e6-9433-aa72af995126.gif)

I've been trying to achieve this using both the onProgress and setTranslate methods .
I am trying to find the proper rotate3D and transform origin values.

mySwiper.on('onProgress', function (s,progress) {
   for (var a = 0; a < s.slides.length; a++) {
     var slide = s.slides[a];
     var slideProgress = slide.progress;

```
 if (slideProgress < 0) {
   var slideRotation = 90-(slideProgress *90);
   var slideOrigin= (100+(slideProgress*100));
 } else {
   var slideRotation = 90-(slideProgress *90);
   var slideOrigin= (100+(slideProgress*100))*-1;
 }
  slideOrigin=0; 

 $(slide).css({transform:'rotateY('+slideRotation+'deg)'}) 
```

  }
});
any help appreciated!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
