### ISSUE TITLE
Documentation not describing swiper-*-[black|white] modifiers

### ISSUE THREAD

**Issue by bettiolo** [nolimits4web/Swiper#1840]
Where should I write about these modifiers? 

I cannot seem to find the source of this page in the repository: http://idangero.us/swiper/get-started/
I would add the info to section 3 or to the API as well

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
