### ISSUE TITLE
When slidesPerView is the same as number of looped slides, the infinite loop creates a whitespace

### ISSUE THREAD

**Issue by sampurcell** [nolimits4web/Swiper#1842]
Hello,

I am trying to use swiper.js with the slidesPerView set as 3 and loop and centeredSlides set as true.   When I swipe back (from left to right), there is a point where the previous slide does not show up (the space where it should be appears white) until I drag the slide a bit more, then it appears.

If I have a number of looped slides that is more than slidesPerView, say 6 slides and slidesPerView is 3, then adding any number of loopAdditionalSlides will fix this issue. I can swipe left or right and the swiping will be fluid with no white space.

However, if the number of looped slides is 3 and the slidesPerView is 3, no matter what I set as loopAdditionalSlides value, there will always be a point when swiping the image from left to right where the previous slide will not show up.

There may be a solution but I am not sure what it would be.

**Comment by Sash-OK** [comment]
+1, I have the same problem

**Comment by huangfh** [comment]
+1

**Comment by lchreal6** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
