### ISSUE TITLE
[Suggestion]: Adding a list of sites using Swiper

### ISSUE THREAD

**Issue by sobolevn** [nolimits4web/Swiper#1849]
I have searched for a little bit for the same issues, no success. 

The library of the real sites using your technology might be a good inspiration for those who want to start using it.

**Comment by chittattoo** [comment]
👍

**Comment by chittattoo** [comment]
Good

**Comment by heavymery** [comment]
:metal:

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
