### ISSUE TITLE
Add support to trace multi-touch(Or not frozen in the case)?

### ISSUE THREAD

**Issue by yyjdelete** [nolimits4web/Swiper#1851]
1. Swiping with the 1st finger;
2. Tap with the 2rd finger while swiping;
3. Up the 1st finger;

And found swiper frozen between 2 pics.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
