### ISSUE TITLE
Active slide not exactly on center with custom width and height, unless window resize

### ISSUE THREAD

**Issue by etuctida** [nolimits4web/Swiper#1861]
I'm trying to set up Swiper like this. The active slide is exact on center with bigger size than other slide, with loop must be active. 
![ss-styling](https://cloud.githubusercontent.com/assets/7054320/18693147/24d0b4c6-7fd2-11e6-9646-e2e05f8b82c2.png)

My slide will be contain with text, not images. So i won't be using transform: scale() in css. 

My code is in [http://codepen.io/etuctida/pen/BLQNoO](http://codepen.io/etuctida/pen/BLQNoO). 
The first slides: slides is looping, but the active slide not exactly on center unless window is resize.
The second slides: the active slide is on center only after slide changes, because I use onSlideChangeEnd(). But with this setting won't work when loop:true, and the active slide moves with a bit before it got centered.

I'm new to jQuery and stuff.
- Is there any function to update slide when initialize slide?
- What should I do to set up swiper like I want?

Sorry for my english. Thank you for great plugin.

**Comment by nolimits4web** [comment]
This won't work as you are trying to change slides size on the fly, so the maximum you can get as the second example here ("jumpy"). To make this work as desired you have to hack in the core stuff or make a effect-like plugin with bunch of JS. Otherwise, it will be simpler to do this not with slides but with some slide's inner div, so the slide stays in same size but you just change size of some inner element, this won't affect swiper default logic

**Comment by andrestef** [comment]
Hello, I have your own problem, how did you solve it? thank
