### ISSUE TITLE
Add NPM install instructions to Getting Started

### ISSUE THREAD

**Issue by matt-oconnell** [nolimits4web/Swiper#1880]
http://idangero.us/swiper/get-started/ does not list `npm install swiper` as an option. Is this page open source? If so, I'm glad to open a PR to add it.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
