### ISSUE TITLE
my cellphone is vivo. when i use Siper plugin, page's a tag's tap and click event is not available.

### ISSUE THREAD

**Issue by wuxiaolan91** [nolimits4web/Swiper#1881]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Swiper Version: 3.0.3
- cellphone: vivo. android system: vivo rev 1.24.0
### What you did

just use swiper. and use a tag.
### Expected Behavior

tap and click is not avavilable.
### Actual Behavior

EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by CharlyCheng** [comment]
i has it
