### ISSUE TITLE
Groups of multiple slides should respect slideNextClass/slidePrevClass classes

### ISSUE THREAD

**Issue by jrefano** [nolimits4web/Swiper#1882]
This is a (multiple allowed):
- [x] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- Swiper Version: 3.3.1
- Platform/Target and Browser Versions: Chrome macOS, Firefox macOS
### What you did

initialized swiper with config:

```
slidesPerGroup: 3,
slidesPerView: 3,
slidesPerColumn: 2,
```
### Expected Behavior

`slideNextClass` and `slidePrevClass` to apply to all the slides in the next/prev "groups"
### Actual Behavior

`slideNextClass` is applied to the second slide in the group and `slidePrevClass` is applied to last slide in previous group

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
