### ISSUE TITLE
Loop not work to the right side

### ISSUE THREAD

**Issue by vdv73rus** [nolimits4web/Swiper#1883]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Swiper Version: 3.3.1.
- Platform/Target and Browser Versions: MacOS Sierra, Google Chrome 54.0.2840.59 (64-bit)
### What you did

I use loop + freeMode + slidesPerView: 'auto' settings.
But when summary slides width less then carousel viewport, there is no work dragging to right.
Here is fiddle https://jsfiddle.net/vdv73rus/uf0mu1t8/4/ (open on fullHD display & try swiping to right — the carousel stops. And left direction works well)

I tried use fixLoop calls on many callbacks, but it was no useful.
### Expected Behavior

There is loop dragging to the right side.

**Comment by romankierzkowski** [comment]
+2

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
