### ISSUE TITLE
Pagination is wrong w/ multiple slides per column

### ISSUE THREAD

**Issue by jrefano** [nolimits4web/Swiper#1884]
This is a (multiple allowed):
- [x] bug
- Swiper Version: 3.3.1
- Platform/Target and Browser Versions: chrome osx
### What you did

added `slidesPerColumn: 2, slidesPerView: 3` to config
### Expected Behavior

3 rows of slides, 2 slides per column, with correct pagination
### Actual Behavior

pagination shows as many bullets as slides, without taking into consideration 3 rows/2 columns.  so even though there are only 6 pages of slides, there are 12 bullets.  

tried increasing `slidesPerGroup` to match how many i see per group, and still isnt paginating correctly.  now it seems like a random amount

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
