### ISSUE TITLE
Callbacks are not fired when loop is set to false

### ISSUE THREAD

**Issue by marcelombc** [nolimits4web/Swiper#1887]
Callbacks are not fired when loop is set to false.
I think is an activeIndex/previousIndex issue.
This happens in version 3.4.0

**Comment by nolimits4web** [comment]
Please provide JSFiddle or another example with the issue

**Comment by marcelombc** [comment]
So, I've been testing and it seems to be a Blink issue. There are some container widths that prevent the callback from being fired.
You can find an example on the following [fiddle](https://jsfiddle.net/9hru8rf9/7/)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
