### ISSUE TITLE
Swiper navigation next and prev not run under tab(im using bootrap)

### ISSUE THREAD

**Issue by sethinh** [nolimits4web/Swiper#1890]
Im using bootrap to create tab 
my slides under tab.
When my tab become visible next and prev button not work
my script:
$(document).ready(function(){
  var swiper1 = new Swiper('.swiper-container-1', {
    slidesPerGroup  :4,
    slidesPerView   :4,
    nextButton: '.swiper-button-next-1',
    prevButton: '.swiper-button-prev-1',
  });
});
$(document).ready(function(){
  var swiper2 = new Swiper('.swiper-container-2', {
    slidesPerGroup  :4,
    slidesPerView   :4,
    nextButton: '.swiper-button-next-2',
    prevButton: '.swiper-button-prev-2',
  });
});
$(document).ready(function(){
  var swiper3 = new Swiper('.swiper-container-3', {
    slidesPerGroup  :4,
    slidesPerView   :4,
    nextButton: '.swiper-button-next-3',
    prevButton: '.swiper-button-prev-3',
  });
});
when im runing just first tab navigation run only
I founded a solved told using update() but not work(err:swiper update is not a function)
Thanks for help.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
