### ISSUE TITLE
Sliding stops halfway

### ISSUE THREAD

**Issue by marqusG** [nolimits4web/Swiper#1891]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Swiper Version: 3.3.1.
- Used in a Cordova Mobile app for Android 4.4.4

I'm developing a Cordova mobile app using Swiper and it works but sometimes, absolutely randomly, the transition suddenly stops halfwayand both previous  and net pages are visible per half.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
