### ISSUE TITLE
lockSwipeToNext() results in ability to swipe partially previous

### ISSUE THREAD

**Issue by Defcon0** [nolimits4web/Swiper#1902]
### This is a (multiple allowed): bug

Swiper Version: Latest tag
Platform/Target and Browser Versions: Ionic 1.3, cordova 6, Chrome
[swiper.zip](https://github.com/nolimits4web/Swiper/files/545770/swiper.zip)
### What you did

I want to achieve the following:

A slider implemented using Swiper (http://idangero.us/swiper) should have 4 slides. But the last one shouldn't be reachable by swiping but only programmatically if some condition is fulfilled.

Now I tried to use lockSwipeToNext() as said in https://github.com/nolimits4web/Swiper/issues/1876 . Unfortunately it doesn't work 100%. When locking by using the above function, I now am able to move the swiper partially previous (see [video](https://drive.google.com/open?id=0B4bH_zE8RVR7NmNBcHF3cXZOb00) for visualization of the problem).

Here's the code I use:

```
$scope.slider.on('slideChangeStart', function() {
    if ($scope.slider.activeIndex == 3)
    {
            $scope.slider.lockSwipeToNext();
    }
    else
    {
            $scope.slider.unlockSwipeToNext();
    }
});
```

Thanks.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
