### ISSUE TITLE
Partial view

### ISSUE THREAD

**Issue by Crunky** [nolimits4web/Swiper#1904]
Hi,

i need a centred carousel with partial views of next/prev images like [here](http://www.jssor.com/demos/nearby-image-partial-visible-slider.slider)

So the main Image should have 80% and the partial images 10% 10% width.

Is that possible?

Thanks Marco

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
