### ISSUE TITLE
Question: Loop and dynamic slide content changing

### ISSUE THREAD

**Issue by ganySA** [nolimits4web/Swiper#1905]
I have a scenario where i have 3 slides where i am updating the content dynamically. I have the loop function enabled however when i swipe left or right i update the content of the hidden slides, because of the way loop works and how it copies slides it displays old data on the "duplicate" slides which then is not really the "next" slide i want to display.

1) is there a method that can be used to refresh the "duplicate" slides at the end of a swipe? - refresh duplicate slides in use after completion of a task?
2) is it critical to have these duplicate slides in future releases?

Would love to know how people have solved this issue...
Thank you.

**Comment by duytrantps** [comment]
I'm meeting this issue too, and it's critical to me. Hope you guys can help this issue soon
Thank you

**Comment by jgamao** [comment]
Me too, I also have this issue, I hope someone can solve this. It's a great for all of us!

**Comment by nolan-m** [comment]
Same issue.  I display loading spinners for large images on the slide, but the duplicates do not update when the image has been loaded.  I have to manually duplicated slide content when the image load is complete.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by kamalakkanni** [comment]
@ganySA ,whether this issue got fixed or not.If fixed means pls help me.I am also facing this issue

**Comment by samuraiexx** [comment]
I also have this issue. Anyone know whether there is a workaround?
