### ISSUE TITLE
White space at end of slides when set width is used

### ISSUE THREAD

**Issue by boldfacedesign** [nolimits4web/Swiper#1906]
This is a (multiple allowed):
- [x] bug
- [x] enhancement
- Swiper Version: 3.4.0.
- Platform/Target and Browser Versions: All.
### What you did

Instantiate a Swiper instance with multiple slides. Set the `width` property via options.
### Expected Behavior

If there are insufficient slide to fill the container scrolling should be disabled.
If there are enough slides to enable scrolling, scrolling should end when the last slide in fully visible within the swiper-container. I.E. in a standard LTR carousel scrolling should end and next button disabled when the last slide is flush to the right-hand edge of the swiper-container.
### Actual Behavior

Scrolling continues until only the last slide is visible leaving a large amount of white space.

Fix could be achieved by calculating the combined width of all slides and updating a `remainingTransitionWidth` variable on scroll. This can then be used to calculate the distance of the last scroll before 0 is reached, at which point scrolling is disabled.

**Comment by uzumakinaruto123** [comment]
Any temporary workaround for this ?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
