### ISSUE TITLE
Still having the issue with srcset and Firefox

### ISSUE THREAD

**Issue by albi** [nolimits4web/Swiper#1907]
https://github.com/nolimits4web/Swiper/issues/1878

**Comment by katerlouis** [comment]
Maybe this is correlated with #1899

**Comment by albi** [comment]
Any news on this issue? I've just updated Swiper to 3.4.1 but still having the same issue. #1878

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
