### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by alexilin83** [nolimits4web/Swiper#1909]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Swiper Version: 3.4.0
- Platform/Target and Browser Versions: Windows 10, FIREFOX 49.

Pagination sometimes doesn't work correctly. When click on a pagination link, slide with different index becomes active.

**Comment by jrefano** [comment]
and `loop: true` makes it even worse.  pagination in general is very broken

**Comment by mtz** [comment]
it wont work if u set centeredSlides and slidesPerView in an direction 'vertical' too.

direction: 'vertical',
centeredSlides: true,
slidesPerView: 4

**Comment by Tusko** [comment]
+1

pagination active bullet doesn't sync with active slide

I have tried with/without loop

**Comment by caseyyee** [comment]
Also experiencing this same issue.   Seems to happen when `direction: 'vertical'` is set.

**Comment by andyinabox** [comment]
+1 

I have 6 slides, `slidesPerView: 4`:

 * On first load, fractional pagination reads `1 / 1`
 * When I slide to the next, `2 / 2`
 * When I slide to the next, `3 / 3`

**Comment by stoneshower** [comment]
In my case, when I change the selector with class to id, it worked correctly.

Before
`var swiperSlides = new Swiper('.swiper', { OPTIONS }`

After
`var swiperSlides = new Swiper('#swiper', { OPTIONS }`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
