### ISSUE TITLE
onSlideChangeEnd is not called when using the scrollbar to change slide

### ISSUE THREAD

**Issue by iwazaru** [nolimits4web/Swiper#1910]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Swiper Version: 3.4.0
- Platform/Target and Browser Versions: macOS 10.11.6, Chrome 54
### What you did

A simple swiper using draggable scrollbars. A message is logged to the console when `onSlideChangeEnd` is called.
Here's an example : https://jsfiddle.net/vfzex02h/4/
### Expected Behavior

`onSlideChangeEnd` should be called when the active slide is changed by dragging the scrollbar.
### Actual Behavior

`onSlideChangeEnd` is called when the active slide is changed by dragging a slide, but not when dragging the scrollbar.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
