### ISSUE TITLE
KeyboardControl not work well on RTL

### ISSUE THREAD

**Issue by heavymery** [nolimits4web/Swiper#1911]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Swiper Version: 3.4.0
- Platform/Target and Browser Versions: macOS 10.11.6, Chrome 54
### What you did

Set `keyboardControl: true` option with `<div class="swiper-container" dir="rtl">` container.
### Expected Behavior

Arrow key `←`, `→` event should be same behavior with `slideNext`, `slidePrev`.
### Actual Behavior

Arrow key work well on some slides, but not work on other slides.

**Comment by heavymery** [comment]
I think below code is not required. Is there any reason for change `swiperOffset.left`?

>https://github.com/nolimits4web/Swiper/blob/master/src/js/keyboard.js#L33
```js
if (s.rtl) swiperOffset.left = swiperOffset.left - s.container[0].scrollLeft;
```

When I removed this code, key event worked well even on RTL container 😄

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
