### ISSUE TITLE
当前slide使用lockSwipeToNext()，点击页面元素调用slideTo()失效。我只想禁止向后滑动切换，该怎么做？

### ISSUE THREAD

**Issue by luxiaowu** [nolimits4web/Swiper#1913]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.3.1 and 3.4.0
* Platform/Target and Browser Versions: macOS, Windows, IOS, ANDROID, CHROME, ETC.

### What you did
		var mySwiper = new Swiper('.swiper-container', {
			direction: 'vertical',
			effect: 'fade',
			onSlideChangeEnd: function(swiper) {
				if (swiper.activeIndex == 1) {
					swiper.lockSwipeToNext();
				} else {
					swiper.unlockSwipeToNext();
				}
			}
		});
		document.querySelectorAll('.swiper-slide')[1].addEventListener('click', function() {
			alert(1);
			mySwiper.slideNext();
		}, false);

### Expected Behavior
期望滑动不能翻页，但点击可以翻页

### Actual Behavior
现在滑动不能翻页，点击也不能翻页

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by RicoLiu** [comment]
哥们，你不翻译一下老外怎么看得懂

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
