### ISSUE TITLE
Cube effect with zoom

### ISSUE THREAD

**Issue by ndamofli** [nolimits4web/Swiper#1914]
Hi there,
congrats on swiper !  I believe there is a problem integrating the cube effect with the zoom functionality.
Image goes to random position when I try to pan after the initial zoom.
Best,
Nick

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
