### ISSUE TITLE
touchmove Event in 45 degree angle，swiper stopped halfway

### ISSUE THREAD

**Issue by gy134340** [nolimits4web/Swiper#1917]
maybe a bug;

When I scroll the window in 45 degree angle in the  Swiper Elements,it stopped at the half way ,not slide to the prev slide or the next slide . In Android and IOS.

**Comment by gy134340** [comment]
I do not know why,but when I remove the  CSS swiper-container overflow-x:visible ,it work properly;
the code before and after is below,Does anyone know why?
```
.swiper-container{
	padding-right: 50px;
	/*overflow-x:visible;*/
	width:100%;
	-webkit-box-sizing:border-box;
	box-sizing: border-box;
	box-shadow: none;
}
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
