### ISSUE TITLE
restore slide

### ISSUE THREAD

**Issue by andrestef** [nolimits4web/Swiper#1918]
Dear gurus swiper,
I'm using something like the demo "11-nested".
How do I reset the position slide 1 vertical when I change the horizontal slide?
thank you

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
