### ISSUE TITLE
Random slides with freeMode and autoplay

### ISSUE THREAD

**Issue by Tusko** [nolimits4web/Swiper#1920]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: **3.4.0**
* Platform/Target and Browser Versions: MacOS Sierra v10.12.1, Google Chrome v54.0.2840.71, jQuery v3.1.1

### What you did

    if($('.app-slides').length > 0) {
        $('.app-slides').each(function(){
            var t = this,
                WPApps = [];
            $(t).imagesLoaded(function(i) {
                WPApps[i] = new Swiper( t, {
                    pagination                  : '.app-pagination',
                    touchEventsTarget           : 'container',
                    slidesPerView               : 'auto',
                    paginationClickable         : true,
                    centeredSlides              : true,
                    freeMode                    : true,
                    observer                    : true,
                    observeParents              : true,
                    freeModeSticky              : true,
                    speed                       : 500,
                    autoplay                    : 6e3,
                    spaceBetween                : 30
                });
            });
        });
    }

### Expected Behavior
I want to use `freeMode` with `autoplay` + pagination
Here is design of my slides
https://cl.ly/i1Yv

### Actual Behavior
The autoplay set random slides after some interaction with slider (for ex dragging).

And pagination bullets does not sync with active slide.
It's just another problem, all sliders with pagination aren't syncing with active slide, it happened when I have updated swiper to 3.4.0

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
