### ISSUE TITLE
Problem with loop: true, slidesPerView: auto and loopedSlides

### ISSUE THREAD

**Issue by Saxtone** [nolimits4web/Swiper#1922]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.0
* Platform/Target and Browser Versions: Windows 10, Google Chrome v54.0.2840.71, Firefox 49.0.2, jQuery v.1.12.4

### What you did
I'm creating a slider into WordPress, where you create an image gallery and every image is a slide. Nothing special in the HTML - `swiper-container` followed by a `swiper-wrapper` and each `img` is in a `swiper-slide`. The options for the swiper are these:
```
var $swiperSlider = $('.swiper-container-fullscreen');
var swiperOptions = {
	speed: 600,
	// Optional parameters
	autoplay: 0,
	direction: 'horizontal',
	loop: 'true',
	slidesPerView: 'auto',
	spaceBetween: 15,
	// If we need pagination
	pagination: '.swiper-pagination',
	paginationType: 'bullets',
	paginationClickable: true,
	nextButton: '.swiper-button-next',
	prevButton: '.swiper-button-prev',
	keyboardControl: true,
	mousewheelControl: 'true',
	loopedSlides: 7,
}

var mySwiper = new Swiper ($swiperSlider, swiperOptions);
```

### Expected Behavior
I'm loading 7 images and want to loop through all of them. That's why I'm using `loop: true`, `slidesPerView: auto` and `loopedSlides: 7`.

### Actual Behavior
When the page is loaded, the slider is places somewhere in the 3rd image on Firefox, and on Chrome with each refresh of the page the swiper starts on a random slide. If I add this to the code:

```
setTimeout( function(){
	mySwiper.slideTo(0, 0);
}, 100);
```

The problem on Chrome is fixed.
As for firefox everything is working fine on hard refresh (ctrl+shift+F5), but when the page is refreshed normally with F5 it shows the first slide and when I try to move the slides it skips again to somewhere in the middle of the 3rd slide and everything breaks again.
Also the `loopedSlides: 7` parameter seems to not be doing anything at all. With or without it, there is no change in the behavior neither on Firefox nor on Chrome.
P.S I also tried using the `onInit `callback but the problem stays:
```
'onInit': function(Swiper){
	Swiper.slideTo(0, 0);
},
```

**Comment by Saxtone** [comment]
Update: Looks like there is something wrong with the slides indexes, because sometimes when the pagination is clicked it shows wrong slides. The update method for the swiper seems to fix all of the issues:
```
setTimeout(function(){
	mySwiper.update(true);
	mySwiper.slideTo(0, 0)
}, 100);
```
When I add this after the swiper is created everything seems to be working fine both on firefox on chrome.

**Comment by iDVB** [comment]
I get the feeling that questions about **slidesPerView:auto** and **loop:true** are deprioritized since there are notes in the docs about this. 

However, I've gone thru about 6-8 issues listed on this repo as well as the documentation and it seems pretty obvious that the documentation could be much better.

Specifically with regards to acquiring the proper **activeIndex** and what index to pass in to **swiper.slideTo()** in order to slide to the **nearest duplicate or original of that index**

Is there a reason that swiper does not handle this logic for you?

**Comment by anteksiler** [comment]
I am also seeing the same issue when two sliders are in control mode and looped. The slideTo goes to the wrong slide.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
