### ISSUE TITLE
Freemode stops at certain point when using Loop option.

### ISSUE THREAD

**Issue by nfq** [nolimits4web/Swiper#1924]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.0
* Platform/Target and Browser Versions: macOS and Windows, Safari 10, Firefox 49, Chrome 54. Tested on a 2012 MacBook Pro.

### What you did
I'm creating a vertical portfolio slide feature using Freemode and Loop. Here is a [demo](http://fuerst.queridodesign.net/swiper/demos/20-mousewheel-control.html). I've left in the nav dots purely to represent the scroll/freedmode getting 'stuck'.

```
var swiper = new Swiper('.swiper-container', {
    pagination: '.swiper-pagination',
    direction: 'vertical',
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',
    slidesPerView: 3,
    uniqueNavElements: true,
    spaceBetween: 1,
    mousewheelControl: true,
    loop: true,
    keyboardControl: true,
    freeMode: true,
});
```

### Expected Behavior
The slides should scroll and loop continuously, using Freemode and Loop. 

### Actual Behavior
The scroll/freemode behaviour eventually gets stuck. Basically trackpad scroll eventually stops working.

**Comment by nfq** [comment]
Bump. Any ideas @nolimits4web ?

**Comment by dogoku** [comment]
I have run into the same problem. You can check it out [here](http://codepen.io/dogoku/pen/egdGEq)

**Comment by nfq** [comment]
@dogoku lovely UI btw. I still haven't found out how to solve the issue.

**Comment by Waog** [comment]
same problem here

**Comment by StickNitro** [comment]
Can we have an update on this please? I am experiencing the same issue

**Comment by JoshMoxey** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
