### ISSUE TITLE
followFinger: false issue

### ISSUE THREAD

**Issue by juanmata09** [nolimits4web/Swiper#1926]
Hi

Just changed followFinger to false as I hated the jump feel when you scroll fast with you finger.

However, I noticed an issue with 6 or more slides.

On the first 5 slides, followFinger: false, is as expected, once you hit the 6th slide, the jump seems to reappear.

**Comment by juanmata09** [comment]
Looking more into this, I don't think it really matters how many slides you have, it seems to do it on loop, the part where you're on the last slide and loop to the first slide, just that horrible snap that occurs.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
