### ISSUE TITLE
Form element Select not working in IE11

### ISSUE THREAD

**Issue by ezhkov** [nolimits4web/Swiper#1927]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.0.
* Platform/Target and Browser Versions: Windows 10, Internet Explorer 11

### What you did
Place Form into slide. There is a Select in form.

### Expected Behavior
Select is working. I can select any option

### Actual Behavior
When Swiper is initialized Select not working. I can not select any option.

**Comment by tytydas** [comment]
and firefox has this question too

**Comment by rsiirak** [comment]
I've had a similar issue. What did the trick for me was adding 'swiper-no-swiping' class to the select element.

**Comment by NinsgVeen** [comment]
I can confirm that adding the class 'swiper-no-swiping' on the SELECT element solves the issue.

In my case I had a jquery onChange methode on this select, which didn't fire. Adding the class made it work (again).

**Comment by dotmagic** [comment]
I can also confirm the workaround above works. It seems this was reported long time ago #297. Still considering this is a bug, it shouldnt be necessary to add this class.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
