### ISSUE TITLE
CoverFlow 

### ISSUE THREAD

**Issue by gsgenerator** [nolimits4web/Swiper#1929]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4
* Platform/Target and Browser Versions: ALL.

### What you did
I made a Swipef fulldiv always responsible with fixed aspect ratio. And when I set up effect CoverFlow i don't see surrounding slides. Only when I swipe i see parts of them until animation is finished. I cant have fixed size and sort out problem line your example shows with top and bottom padding.

### Expected Behavior
I will like to have a coverflow parameter that will set and add keep along animations:

transform:translate3d(0px, 0px, -200px);

That 200px so i can zoom out with this rather padding top and bottom cause this doesn't work for me at all.

Cause parameter depth only effect the side slides not the main one. 

Adding slides per view creates a problem with height. Adding padding narrow and move my image but not affect the slide shadow.

I try a lot of solutions and only this css transform Z will do it but its lost at a moment that i start swiping :/

Can this be implemented at some point ???
Regards

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
