### ISSUE TITLE
onSlideChangeEnd does not get called when a slide is appended in onSlideChangeStart

### ISSUE THREAD

**Issue by brendler** [nolimits4web/Swiper#1931]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.9
* Platform/Target and Browser Versions: Mac OS 10.11.6, Chrome 54.0.2840

### What you did
Check code here => https://jsfiddle.net/f8op5obh/1/
I'm appending a slide during onSlideChangeStart as part of a preloading routine.

### Expected Behavior
I expect onSlideChangeEnd to run when I swipe to the next slide.

### Actual Behavior
It doesn't run onSlideChangeEnd. 
If I don't append a new slide during onSlideChangeStart, it works OK.

**Comment by cronoklee** [comment]
Just logged my own version of this bug here: https://github.com/nolimits4web/Framework7/issues/1628

Any fix or update since last Novemeber @nolimits4web?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
