### ISSUE TITLE
Fade Effect with Lazyload breaks

### ISSUE THREAD

**Issue by magic-77** [nolimits4web/Swiper#1932]
Hi,
i'm using the latest Swiper Version. I have two Slides that should crossfade using Lazyloading.
But somehow the Transition breaks with Lazyloading.
After all Images are loaded the Transition than works well.

Demo: http://eee-ltd.com/_proto2/

HTML:

    `<div class="header__swiper swiper-container">
        <div class="swiper-wrapper">
          <div class="swiper-slide">
            <div class="swiper__text">Begin Your Search <span class="swiper__text--color">Today</span></div>
            <div class="swiper__image swiper-lazy" data-background="userimages/desktop.jpg">
              <div class="swiper-lazy-preloader"></div>
            </div>
          </div>
          <div class="swiper-slide">
            <div class="swiper__text">This is a longer Demo Text <span class="swiper__text--color">with Color</span></div>
            <div class="swiper__image swiper-lazy" data-background="userimages/desktop-1.jpg">
              <div class="swiper-lazy-preloader"></div>
            </div>
          </div>
        </div>
      </div>`

JS

    `function swiperHeader() {
        swiperHeader = new Swiper('.header__swiper', {
          effect: 'fade',
          preloadImages: false,
          lazyLoading: true,
          autoplay: 8000,
          speed: 1000,
          loop: true
        });
     }`

**Comment by davidenco** [comment]
Still happening with 3.4.2. Is this issue ever going to get fixed?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
