### ISSUE TITLE
When slidesPerView is set to decimal, activeIndex for last slide isn't updated

### ISSUE THREAD

**Issue by salvisb** [nolimits4web/Swiper#1933]
When option slidesPerView is set to decimal e.g. 1.3 (which is really cool feature), activeIndex for last slide isn't updated and onSlideChangeEnd event isn't fired. Is there any workaround?

Thanks.

**Comment by dogansalman** [comment]
try  centeredSlides: true

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
