### ISSUE TITLE
sliderMove on horizontal swiper with mousewheelControl and freeMode doesn't fire

### ISSUE THREAD

**Issue by BrettGregson** [nolimits4web/Swiper#1934]
The `sliderMove` and `slideChangeStart` events do not fire when using a horizontal swiper with `mousewheelControl : true `and `freeMode: true`

I understand why `slideChangeStart` wouldn't fire since the slide technically isn't changing, but I would expect the `sliderMove` event to fire. Is this the expected behaviour?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
