### ISSUE TITLE
Support for index route with history?

### ISSUE THREAD

**Issue by nolan-m** [nolimits4web/Swiper#1935]
This is a:
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

I am using Swiper with the history option as the main way to navigate through my site.  The first slide should be the index page and the rest of the slides have unique id.  I could not get history working correctly with this setup.  I ended up modifying the library to get the desired solution.  I was wondering if there was any planned support for this use case?

**Comment by liampmccabe** [comment]
I also needed this.

Change:
`var value = this.slugify(slide.attr('data-history'))`

to:
`var value = this.slugify(slide.attr('data-history')) || '/';

in the `setHistory` method.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
