### ISSUE TITLE
problem with vertical slide

### ISSUE THREAD

**Issue by michael2043** [nolimits4web/Swiper#1939]
i want to use vertical slide and in each slider use overflow-y:auto,but in slider the content cannot scroll,how can set the property
*hanppened in safari

**Comment by gggg990** [comment]
I have the same problem.. I am using 3 horizontal slides, but on one of them I would like to have a scrollable longer text (not another vertical swipe), but the text gets cut-off at the bottom. Any suggestions?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
