### ISSUE TITLE
Remove space between slides with different widths

### ISSUE THREAD

**Issue by luciocorrea** [nolimits4web/Swiper#1940]
* [x] bug

* Swiper Version: 3.4.0

### What you did
Is it possible to remove spaces  between slides with different widths? I searched for other closed issues and in stackoverflow too,  but I didn't found a solution.

### Actual Behavior
I created a demo here: http://codepen.io/anon/pen/aBwJje

As you guys can see, there's always only one slider visible. I don't know if it's a bug or the default behavior. If it's, is there a way to do what I need?

Thanks in advance.

**Comment by Stankerne** [comment]
Hey luciocorrea,

I don't really understand what you want to do...
How many slide you want per view ? Just one without space between others ?

As I see, you used images with "no-repeat" property that's why you can see spaces between slides. There is no bug there and I don't think your problem is an issue.

Anyway, I recommend to check demos on http://idangero.us/swiper/demos/ and use these options.
Beside, I feel that the best demo to use ( for you ) is : https://github.com/nolimits4web/Swiper/blob/master/demos/08-centered-auto.html

Check the codepen I did: http://codepen.io/anon/pen/KNXrLd
Is that what you expected ?

Cheers!

**Comment by luciocorrea** [comment]
That's my problem: I have a gallery, with images of different widths. So, I'd like to show them in the container without any spaces between them. I thought that using   slidesPerView: 'auto' would solve that, but It didn't. 

In the codepen you did, you specified the width of the slides using nth-child and that worked. So I think it's a css problem in my code and not a bug in Swiper.

Thank you.
