### ISSUE TITLE
slidePerView > 1 with autoHeight: true

### ISSUE THREAD

**Issue by Stankerne** [nolimits4web/Swiper#1941]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: swiper: "^3.3.1",
* Platform/Target and Browser Versions: Every Platform

### What you did
Here is the swiper init options :
`var swiper = new Swiper('.product-ratings-slider', {
    nextButton: '.icon-arrowRight',
    prevButton: '.icon-arrowLeft',
    spaceBetween: 100,
    autoHeight: true,
    slidesPerView: 3
});` 

With these options, we can see that only the active slide set the height to the swiper-wrapper.
 
### Expected Behavior
The thing I expect is to have the height calc with the bigger visible slide even if that's not the first one (the active slide). 

### Actual Behavior
The active slide is only the first slide of these 3 visible slidesPerView.
So, the second and third visible slide are cropped.  That only when the bigger slide get the class "swiper-slide-active" that the swiper-wrapper get the right height.

**Comment by BabyDead** [comment]
Uhm, I'm not an author or anything, but autoHeight does exactly what it is supposed to do. It changes the height to wrap around each slide.

I actually used the function you're looking for by accident at first, and I can't find it now. Maybe it's just `autoHeight: false` ?

Either way, this is not a bug. This is a wrong interpretation by the user.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
