### ISSUE TITLE
Carousel rewinds when clicking next with slideToClickedSlide

### ISSUE THREAD

**Issue by cofetti** [nolimits4web/Swiper#1945]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.0
* Platform/Target and Browser Versions: Android 6.0 webview (cordova)

### What you did
Carousel settings:
~~~~
{
                freeModeMomentum: true,
                slidesPerView: 'auto',
                initialSlide: 0,
                centeredSlides: true,
                slideToClickedSlide: true
}
~~~~
Slide width is 33% so there are 3 slides shown at any time. Also tried `slidesPerView: 3`

### Expected Behavior
Clicking on the next slide to the right should correctly scroll the carousel to the right.

### Actual Behavior
Clicking on the next slide several times causes the carousel to visually rewind itself when it hits the "end". Doesn't happen every time, but about 2/3 of the times.
In Chrome I managed to reproduce the same bug only about 1/50 times.

This seems to be caused by some kind of race condition. I was able to fix it by editing `s.updateClickedSlide`. After fixLoop is called I changed timeout from 0 to 100 for Android and it fixes the issue. It's a dirty fix, I hope you can find a better solution.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
