### ISSUE TITLE
How to show an image is not loaded in swiper.js ? 

### ISSUE THREAD

**Issue by mynamestartswitha** [nolimits4web/Swiper#1947]
How to show a image in swiper.js slide if the binded image is not loaded example if the status of the image is 404, show 'no-image' images in that slide

**Comment by aweiher** [comment]
this is not a bug

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
