### ISSUE TITLE
Multi Row Slides has problem

### ISSUE THREAD

**Issue by leonardo1024** [nolimits4web/Swiper#1954]
Hi, there is showing magin-top: px styles on each odd or even item. 
 But on demo everything looks fine: http://idangero.us/swiper/demos/10-slides-per-column.html

**Comment by nolimits4web** [comment]
So what is the issue? Example with the issue would be good

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
