### ISSUE TITLE
Not set dynamic height

### ISSUE THREAD

**Issue by MrChe** [nolimits4web/Swiper#1957]
I have a lot of slides with different height. Some slides I have to scroll inside to create SVG animation scrolling.
Now swiper not correctly initialize the height of the slide
1 - Console - http://take.ms/2QYfE
2 - Styles - http://take.ms/0aTUi
3 - JS - http://take.ms/o6Sl6

Please help me with my problem

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
