### ISSUE TITLE
lazyload bug 

### ISSUE THREAD

**Issue by superchangme** [nolimits4web/Swiper#1961]
This is a (multiple allowed):
* [ ] bug

* Swiper Version:3.4.0
* Platform/Target and Browser Versions: windows chrome

when i use lazyload  slidesPerColumn=2,the lazyload broken.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

```
lazy-load.js
i changed   tow line --s.params.slidesPerView*s.params.slidesPerColumn
Then it works:-)
![Uploading image.png…]()
    var spv = s.params.slidesPerView*s.params.slidesPerColumn;
                        var maxIndex = Math.min(s.activeIndex*s.params.slidesPerColumn + spv + Math.max(amount, spv), s.slides.length);

```
Plz review the codes

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
