### ISSUE TITLE
Feature request: Add support changing swiper "effect" within one project

### ISSUE THREAD

**Issue by palewire** [nolimits4web/Swiper#1963]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did

I'm interested in making a swiper.js project that switches from the "fade" effect to the "slide" effect during the course of stack. While the ``update`` method allows for many other pieces of the configuration to be reset "on the fly," I do not believe this supported for transition effects. 

I've searched StackOverflow and failed to find a solution, other than implementing a custom transition outside of the framework.

If it's possible to do this, it seems like a good way to extend the existing ``update`` architecture to support another one of the libraries core features.

**Comment by Hexodus** [comment]
+1 for this feature

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
