### ISSUE TITLE
Progress bar doesn't work after refresh.

### ISSUE THREAD

**Issue by ghost** [nolimits4web/Swiper#1967]
Hi,
I'm facing progress bar issue.
it is works fine first time but when i refresh the page it's behave unexpected.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
