### ISSUE TITLE
adaptiveHeight slider

### ISSUE THREAD

**Issue by banegolubovic** [nolimits4web/Swiper#1971]
I'm using Swiper latest version.

Is there some way to make slider to be adaptiveHeight?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
