### ISSUE TITLE
slideDuplicated Classes options not working (duplicate vs duplicated)

### ISSUE THREAD

**Issue by AlexisTessier** [nolimits4web/Swiper#1974]
Hello, I'm using the version 3.4.1 of swiper and I want to rename the swiper classes.

The following options doesn't work as expected : 
slideDuplicatedActiveClass, slideDuplicatedNextClass, slideDuplicatedPrevClass

However,  it seems more like an error in the API documentation because these options - slideDuplicateActiveClass,  slideDuplicateNextClass, slideDuplicatePrevClass - work like a charm =)

(duplicate vs duplicated)

**Comment by sinneren** [comment]
Confirm it 3.4.2. And for the first time default duplicate active class not set.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
