### ISSUE TITLE
Disable swipe slide on image zoom

### ISSUE THREAD

**Issue by RichOnPeers** [nolimits4web/Swiper#1976]
I want to be able to pinch zoom on a device into an image embedded inside a Swiper within my ionic app.

With the code below I am able to zoom into the image but $scope.slider.lockSwipes() locks the X-axis from any kind of use and without it the next slide is triggered when attempting to scroll the X-axis with one finger.

Appreciate the help.

Template:
--
     <ion-slides options="options" slider="data.slider">
      <ion-slide-page ng-repeat="map in maps">
        <div class="callout {{map.name}}">
          <ion-scroll
            zooming="true"
            direction="xy"
            delegate-handle="zoom-pane"
            class="zoom-pane"
            min-zoom="1"
            max-zoom="15"
            overflow-scroll="false"
            on-release="onRelease()">
              <img src="{{map.image}}"></img>
        </div>
      </ion-slide-page>
    </ion-slides>

Script:
--
     $scope.options = {
      loop: true,
      effect: 'slide',
      speed: 500
     }

    $scope.onRelease = function(e) {
      var scrollDelegate = $ionicScrollDelegate.$getByHandle('zoom-pane');
      var view = scrollDelegate.getScrollView();
      var scale = view.__zoomLevel;
      // disable swiping between slides when zoom is active
      if (scale > 1){
        $scope.slider.lockSwipes();
      }
      else{
        $scope.slider.unlockSwipes();
      }
    }

    $scope.$on("$ionicSlides.sliderInitialized", function(event, data){
      // data.slider is the instance of Swiper
      $scope.slider = data.slider;
    });

**Comment by dielfilho** [comment]
I'm having the same problem

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
