### ISSUE TITLE
Nested scrollbar not working in Safari

### ISSUE THREAD

**Issue by ausiuming** [nolimits4web/Swiper#1977]
* [x] bug
* Swiper Version: 3.4.1.
* Browser Versions: Safari for Mac OS & iOS.

Individual scrollbar works as in demo, but stopped working when nested in slides. Problem only in Safari.

Please check the demo: https://jsfiddle.net/danduino168/6g9h0uzt/

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
