### ISSUE TITLE
touchReleaseOnEdges not work

### ISSUE THREAD

**Issue by leecz** [nolimits4web/Swiper#1978]
This is a (multiple allowed): [x] bug

Swiper Version: 3.4.1
Platform/Target and Browser Versions:  ios safari newest version.

touchReleaseOnEdges not work

i think this code in 'swiper.js' cause the problem:

```js
                if (!s.isHorizontal()) {
                    // Vertical
                    if (
                        (s.touches.currentY < s.touches.startY && s.translate <= s.maxTranslate()) ||
                        (s.touches.currentY > s.touches.startY && s.translate >= s.minTranslate())
                        ) {
                        return;
                    }
                }
```

i think this code `(s.touches.currentY < s.touches.startY && s.translate <= s.maxTranslate())`
should be `(s.touches.currentY < s.touches.startY && s.translate >= s.maxTranslate())`

**Comment by kemo89** [comment]
I have the same problem on safari and on ios device / simulator.
(In Chrome it works)

**Comment by kessyrocha** [comment]
Did you resolve the problem ?

**Comment by leecz** [comment]
@kessyrocha no，I didn't use this method，finally

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
