### ISSUE TITLE
Dynamic Content - Duplicate Slide Update

### ISSUE THREAD

**Issue by jgamao** [nolimits4web/Swiper#1980]
repost: (c) ganySA

I have a scenario where i have 3 slides where i am updating the content dynamically. I have the loop function enabled however when i swipe left or right i update the content of the hidden slides, because of the way loop works and how it copies slides it displays old data on the "duplicate" slides which then is not really the "next" slide i want to display.

is there a method that can be used to refresh the "duplicate" slides at the end of a swipe? - refresh duplicate slides in use after completion of a task?
is it critical to have these duplicate slides in future releases?
Would love to know how people have solved this issue...
Thank you.

**Comment by DjulLau** [comment]
Hi,

Also interested in a way to implement a swiper slide buffer of dynamic content...

Cheers

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by DanielRuf** [comment]
> because of the way loop works and how it copies slides it displays old data on the "duplicate" slides which then is not really the "next" slide i want to display.

The cloned / duplicated slides still have the duplicate prev / active / next classes which collides with the current real prev / active / next slides.

**Comment by kamalakkanni** [comment]
Hi,This issue exist for me also.pls help me to fix it
