### ISSUE TITLE
grabCursor target not affected with touchEventsTarget option

### ISSUE THREAD

**Issue by shrpne** [nolimits4web/Swiper#1982]
This is a bug

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Windows 10 x64, Firefox 50.1
### What you did
I set options `grabCursor: true` and `touchEventsTarget: 'wrapper'`

### Expected Behavior
`cursor: grab` should apply to wrapper element

### Actual Behavior
`cursor: grab` applies to container element

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
