### ISSUE TITLE
Zoom not working when using Fade effect

### ISSUE THREAD

**Issue by erikwood00** [nolimits4web/Swiper#1983]
Hello

it seems that when using { effect: fade, zoom: true } the pinch to zoom isn't working correctly: it zooms on double tap but when moving the zoomed image the positions are wrongly calculated (it seems that zoom functionality works only with default 'slide' effect).
Maybe when a slide is zoomed in, calculations should go to the ones of 'slide' effect, and when a slide is not zoomed in, swiper should apply the user selected effect, but I don't know how to force this behavior.

---
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1.
* Platform/Target and Browser Versions: Windows/Chrome.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
