### ISSUE TITLE
Bootstrap checkboxes or switches do not work when placed inside the  <div class="swiper-slide"></div>

### ISSUE THREAD

**Issue by CodeWorldIndustries** [nolimits4web/Swiper#1984]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version:  3.4.1
* Platform/Target and Browser Versions: Chrome

### What you did
I was testing to see if I can use checkboxes or switches inside the < div class="swiper-slide"><  /div>.
Although the html is rendered the functionality is not. Checkboxes are only getting checked if you set the direction to vertical

### Expected Behavior
Checkboxes and switches should function

### Actual Behavior
they are not being checked or switched (if using switches)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
