### ISSUE TITLE
Swiper displays last image as first image and jumps to 2nd image upon clicking next

### ISSUE THREAD

**Issue by davidenco** [nolimits4web/Swiper#1986]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Windows

### What you did
https://jsfiddle.net/jx2waxan/
I want to load Swiper in a Bootstrap Modal (see above link for a working demo). When the modal opens, clicking the left-side of the image should go to the previous image but nothing happens. If you have tried to click the left-side, then the right-side won't work either. Only if you open the modal and immediately click the right-side will it work, but even then it jumps from the last image to the 2nd image.

### Expected Behavior
Upon opening the modal, the first image is displayed by default according to the HTML.

### Actual Behavior
Upon opening the modal, the last image is displayed by default. Clicking the left-side of the image does nothing and subsequently clicking the right-side does nothing either. However if the modal is opened and you immediately click the right-side (next image), it works, but it skips the first image and jumps straight to the 2nd image. At this point, the previous and next areas work as they should do.

**Comment by ovaldi** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
