### ISSUE TITLE
Slider with offset (vertical & horizontal)

### ISSUE THREAD

**Issue by elalemanyo** [nolimits4web/Swiper#1987]
Hallo,
I am trying to build something like this:
![viewport](https://cloud.githubusercontent.com/assets/3856862/22102710/b18fd9b8-de38-11e6-9cc4-7ac47f1255d8.jpg)

The idea is to have one vertical slider to change between projects and on each project will be a horizontal slider to change between multiple images from the project.
The feature where I am not really sure how I can build it is with the vertical offset.

Is it possible to achieve something like this with swiper?

Thanks!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
