### ISSUE TITLE
Nodejs engine version on tag and master branches are different

### ISSUE THREAD

**Issue by maxorlovsky** [nolimits4web/Swiper#1990]
Hello.

Just wanted to say that packages.json on master branch is different from what we can see in 3.4.1 (latest) tag branch.
Important change is node engine being lowered down from 6.7.0 to 4.7.0.
Can this change be released as a patch please? One of website that I work on is relying on this and there is no way to upgrade nodejs version for now to version 6+ as this will mess up all other websites.

Thank you.

**Comment by aaronjudd** [comment]
This engine version also prevents use in older node instances, for instance in Meteor, which is still using Node 4.6.2...

**Comment by deanius** [comment]
Yes, please bump the version, and do a publish ASAP! `yarn --ignore-engines` is my workaround right now.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
