### ISSUE TITLE
Pagination via PHP possible?

### ISSUE THREAD

**Issue by goellner** [nolimits4web/Swiper#1992]
I am struggling with Tooltips on the bullet navigation. They are working fine until there is a window resize triggered. Then they get redrawn and the tooltips aren't working anymore. I am using tooltipster (iamceege.github.io/tooltipster/)
Since my Slides are coming from WordPress anyway it would be nice to just loop through them, because I need a custom data-tooltip="" attribute on my bullet points anyway. Is there a way to disable the swiper internal pagination renderer. I am using a few more iterations of the swiper on my page, so I can't disable them in the plugin source.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
