### ISSUE TITLE
Loop mode - slideTo method transition direction

### ISSUE THREAD

**Issue by lorenzomigliorero** [nolimits4web/Swiper#1993]
This is a:
* [x] bug

* Swiper Version: 3.4.1.
* Platform/Target and Browser Versions: Windows, CHROME.

### What you did

This is the Swiper params that I use:
```javascript

var params = {
	initialSlide: 0,
	direction                    : 'vertical',
	slidesPerView                : 2.5,
	loopedSlides                 : 4,
	threshold                    : 50,
	loop                         : true,
	control                      : another swiper instance,
	controlBy                    : 'container',
	prevButton                   : DOM Object,
	nextButton                   : DOM Object,
	touchMoveStopPropagation     : true,
	mousewheelControl            : true,
	speed                        : 800,
	centeredSlides               : true,
	autoplayDisableOnInteraction : false
}

```
### Expected Behavior
If I call slideTo() from 0 to 1 (from a number lower than another), transition direction should be left to right, or top to bottom.
If I call slideTo() from 1 to 0 (from a number greater than another), transition direction should be right to left, or bottom to top.

### Actual Behavior

In loop mode, if I call the slideTo method from slide 0 to slide 1, the transition direction is right to left, or bottom to top.
If I call slideNext(), transition direction works as expected (left to right, or top to bottom), and from my point of view this is the right behavior .

Thank you for your work!
It's an amazing project!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
