### ISSUE TITLE
[Bug] Wrong slide width calculation

### ISSUE THREAD

**Issue by yekver** [nolimits4web/Swiper#1994]
* Swiper Version: 3.4.1.
* Platform/Target and Browser Versions: IOS.

### What you did
I set swiper item width to be 65.6% of screen size, after this (during debug on my iPhone) I saw that item calculated width is 261.296875px.

### Expected Behavior
Swiper must take item real width without any rounding.

### Actual Behavior
Swiper think that item width is 262px and as a result items position on the screen is not correct.

**Comment by TomOne** [comment]
I noticed this issue too and created a demo to reproduce it on CodePen: https://codepen.io/anon/pen/NajYxp

In the demo the slider is contained in a 33 % width container and below there’s another div with 33 %. The widths of the slider and of the container below should be the same, but Swiper rounds the values to full pixels. Resize the browser window and try different viewport widths.

This doesn’t seem to happen if `slidesPerView` is greater than the default 1. Then the rounding doesn’t take place.

Here’s a zoomed screenshot of the width mismatch:
![nomacs_2017-09-28_14-36-52](https://user-images.githubusercontent.com/4357973/30966826-8718fe06-a45a-11e7-9e0a-3afd0b150ca7.png)

**Comment by TomOne** [comment]
I could figure out the root cause of this issue: The slide width is calculated with the `.offsetWidth` DOM element method which rounds the width to the next integer, see https://github.com/nolimits4web/Swiper/blob/21d2a1da5b9b2e9610ec4005aad337a4af4d729f/src/js/core.js#L802 (actually uses Dom7’s `.outerWidth` which internally uses `.offsetWidth`).

This should be rewritten to use `.getBoundingClientRect().width` to not be restricted to integers.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by DanielRuf** [comment]
Should I file a new issue?

This issue still exists because the values are casted ton integers and so the rounding gets lost and so browsers do not fill the 639.752 or 639.265 px width of the Swiper container and set the slides to 639 and this produces the gap.

https://github.com/nolimits4web/Swiper/blob/master/src/components/core/update/updateSize.js#L23-L24

**Comment by DanielRuf** [comment]
I tried to remove the parseInt calls but this breaks the whole Swiper.
Are there more changes needed?

I guess we need some precision mode to switch between or stop rounding the values completely.

**Comment by DanielRuf** [comment]
@nolimits4web `roundLengths` is not set but the slides still have round values.
