### ISSUE TITLE
First slide disappears in loop mode when I navigate from penult to the last

### ISSUE THREAD

**Issue by xahon** [nolimits4web/Swiper#1996]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.0
* Platform/Target and Browser Versions: chrome (Latest for linux)

### What you did
I have done simply looped swiper.

### Expected Behavior
I wanted to see my first slide after last

### Actual Behavior
When I navigate to the last slide there is no first slide after that shows

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
