### ISSUE TITLE
Allow to set min-width for slide

### ISSUE THREAD

**Issue by K4T** [nolimits4web/Swiper#1997]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement / question
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1

Hi,

is it possible to set somehow min-width for each slide?

My problem is that on certain devices (like iPhone 5) my slider has to small slides. I would like to have them bigger (there is space for it). Please, check my jsfiddle: https://jsfiddle.net/KAT_/u1k8b3u8/1/. As You can see I tried to limit slide width by setting max-width property to 280px on .swiper-item class. Unfortunatelly that solution will break whole slider. Resize jsfiddle viewport and You will see what is happening - slides will be not centered anymore on small viewport width. How I can solve my problem?

Thanks!

**Comment by Coffee-Themes** [comment]
Did You tried to set `variableWidth : true`? This option will allow You to control width of elements.

**Comment by Beatabout** [comment]
When using min-width Slider doesn't resizes and don't allow to go to the next slide

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
