### ISSUE TITLE
mousewheelControl param is not changing when using enableMousewheelControl & disableMousewheelControl methods

### ISSUE THREAD

**Issue by klojniewski** [nolimits4web/Swiper#1998]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Latest OSx, Latest Chrome.

### What you did
I've initialised slider with mousewheelControl: true param.
I had to disable mousewheel.
slider.disableMousewheelControl()

### Expected Behavior
slider.params.mousewheelControl value should be changed into false when using slider.disableMousewheelControl() or to true when using slider.enableMousewheelControl()

### Actual Behavior
slider.params.mousewheelControl  is not been changed 

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
