### ISSUE TITLE
[BUG] isEnd property isn't updates properly

### ISSUE THREAD

**Issue by yekver** [nolimits4web/Swiper#2000]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: ALL.

### What you did
```javascript
var swiperInstance = $('.swiper-container').swiper({
    slidesPerView: 'auto',
    centeredSlides: false,
    observer: true
});

//on swiperInstance.isEnd === true do the ajax request to get next slides
var slidesList = $(slidesHtml);
swiperInstance.appendSlide(slidesList);
// swiperInstance.isEnd = false;
```

### Expected Behavior
loaded portion of slides appends without scroll swiper carousel to the end.

### Actual Behavior
loaded portion of slides appends and swiper carousel unexpectedly scrolls to the end, because of this code: https://github.com/nolimits4web/Swiper/blob/decbe0d4f6c27a8fd7cf92c30f1d5428e7b7dd07/src/js/core.js#L1280

If uncomment the last line in my code, swiper will work properly!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
