### ISSUE TITLE
[Bug] loop does not work together with slidesPerColumn

### ISSUE THREAD

**Issue by claudiobmgrtnr** [nolimits4web/Swiper#2001]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Seems unrelated to Browser and OS (Same behaviour on Mac OSX Chrome 55 and Windows 10 Firefox 50)

### What you did
Copied example from demo
Set `loop:true`
http://codepen.io/claudiobmgrtnr/pen/JELzJR

### Expected Behavior
Works like demo just with looping

### Actual Behavior
Pagination has to many bullets.

**Comment by nolimits4web** [comment]
It is not supported with `slidesPerColumn`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
