### ISSUE TITLE
Continuous Looping Slider with Pause on Hover?

### ISSUE THREAD

**Issue by hartey11** [nolimits4web/Swiper#2004]
Hi,

I'm trying to create a slider that continuously slides without stopping between each slide. I also need it to pause when the mouse is hovering and then resume again if cursor moves off. Any idea what the combination of settings are to achieve this? At present I either get a small pause between slides and / or the sliding stops completely once I have interacted with it (doesn't resume sliding afterward)?

**Comment by gandhiselvarj** [comment]
$(".swiper-container").hover(function(){
		swiper.stopAutoplay();
	}, function(){
		swiper.startAutoplay();
	});

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
