### ISSUE TITLE
IE 10+ won't allow to attach events (mousedown) inside swiper container

### ISSUE THREAD

**Issue by tylik1** [nolimits4web/Swiper#2005]
* [x] bug

* Swiper Version:3.4.1
* Windows IE 10, 11, Edge

### What you did
Added zoom plugin, which attached mouse events to target image inside slider. Mouse events (mousedown) from other sources won't work on IE

### Expected Behavior
Events should be allowed in IE

### Actual Behavior

I removed the code bleow and it is working now. I'm not sure if it will effect some other IE functionality but on first glance works fine.  Could you please explain for what versions of IE was this check used? 

          if (s.browser.ie) {
                touchEventsTarget[action](s.touchEvents.start, s.onTouchStart, true);
                target[action](s.touchEvents.move, s.onTouchMove, moveCapture);
                target[action](s.touchEvents.end, s.onTouchEnd, true);
            }

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
