### ISSUE TITLE
Prepend functionality not working for me

### ISSUE THREAD

**Issue by touhid-rahman** [nolimits4web/Swiper#2007]
This is a (multiple allowed):
* [x] bug

Initially there is 2 slide empty space even when prepend value is zero; how can I fix this gap?
http://prntscr.com/e46f0a

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
