### ISSUE TITLE
IOS 10 clicking inside swiper slide makes slider navigate to different slide

### ISSUE THREAD

**Issue by tylik1** [nolimits4web/Swiper#2009]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: IOS 10

### What you did
Go to example page on ios 10 iphone 6 or later.
http://idangero.us/swiper/demos/#.WJhh4bZ94UE
Use second example.
Click on second page navigation roundel. Then click inside slide area. Click triggers swiper to go to the previous slide. It doesn't happen on every click, but happens pretty often.

### Expected Behavior
Click without drag shouldn't cause swiper to navigate to another slide.

### Actual Behavior
Clicking inside slide shouldn't cause swiper navigate to different slide.

**Comment by tylik1** [comment]
UPD. I think this may be connected to simulateTouch: true property. When i disable it on localhost, i couldn't reproduce the problem.

**Comment by TomasPangzi** [comment]
face the same issue

**Comment by TomasPangzi** [comment]
i create two swiper in one page, and cpu usage come up to 100%

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
