### ISSUE TITLE
When programatically adding pages to the swiper, pages themselves are not initialized properly.

### ISSUE THREAD

**Issue by rprimora** [nolimits4web/Swiper#2012]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Windows, CHROME.

### What you did
Initialize swiper as shown in various examples and demos. On post success I add a page to the swiper via one of the exposed methods: mySwiper.appendSlide(slides);

### Expected Behavior
Page should be added properly and the navigation bullets should appear. Further more, page clicks should work and swiping in general should work.

### Actual Behavior
Pagination is missing, swiping doesn't work. I can swipe images but they are not exchanged accordingly. Funny enough, if I press F12 which enters the debugg mode for Chrome the swiper instantly get initialized properly and everything works just fine. From that point on appending slides to the swiper works fine.

**Comment by nolimits4web** [comment]
Would be good to see live example, looks like you are doing something wrong

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
