### ISSUE TITLE
Img overlap

### ISSUE THREAD

**Issue by nam-co** [nolimits4web/Swiper#2013]
This is a (multiple allowed):
* [x] bug

Hello, hope somebody can help me, I using the fade effect but Im getting this overlap of images, how can I fix this? I tried this css but it didn't work, appreciate any help

![img_9602](https://cloud.githubusercontent.com/assets/3951529/22844922/5f2d9692-efae-11e6-978f-a3d915c30c13.JPG)

.swiper-slide {
	min-height: 100%;
	background-color: white !important;
}

**Comment by JacobDB** [comment]
I'm guessing that photo is supposed to rotated 90 degrees, right? If so, it's not working because each slide is only the height of it's contents. To adjust for this, add this to your CSS:

    .swiper-slide {
        flex-grow: 1;
    }

That should allow you to set a background color on `.swiper-slide` as you're trying to do.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by ockle** [comment]
@nam-co I know this is a year old, but I had the same issue and found this bug, so in case you or anyone else who finds this wants to make this work as expected, you need to set:
```js
fadeEffect: {
  crossFade: true
}
```
(see http://idangero.us/swiper/api/#fade-effect)
