### ISSUE TITLE
Slides height is set to 240px when page loads

### ISSUE THREAD

**Issue by LeonardoMinatiCrispyBacon** [nolimits4web/Swiper#2014]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: macOS, Chrome

### What you did
Following the vertical slides + responsive / fullscreen demo i created a simple html structure with swiper and initialized it. When the page first loads slides have a height of 240px. When i resize the window height is set to make slides occupy the fulle screen (as i want).

JS: 

```
var mySwiper = new Swiper('.swiper-container', {
        // Optional parameters
        direction: 'vertical',
        loop: false,
        initialSlide: 0,
        speed: 800,
        mousewheelControl: true,
    });
```

HTML:

```
.swiper-container
    .swiper-wrapper
        .swiper-slide
            h1 slide 1
        .swiper-slide
            h1 slide 2
        .swiper-slide
            h1 slide 3
```

CSS:

```
.swiper-container {
    width : 100%;
    height: 100%;
}
```

### Expected Behavior
Slides should occupy the full screen.

### Actual Behavior
Slides are initialized with 240px height.

**Comment by nolimits4web** [comment]
Would be good to see live link or JSFiddle with the issue. But looks like error on your side with layout

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
