### ISSUE TITLE
Slide height calculated incorrectly in vertical mode

### ISSUE THREAD

**Issue by janein** [nolimits4web/Swiper#2017]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Chrome 56.0.2924.87

### What you did
I initialized a vertical Swiper like this:
```
var swiper = new Swiper($sliderContainer, {
   direction: 'vertical'
});
```

### Expected Behavior
I expect the swiper to be as high as the highest single slide. I do not want do set a fixed height, as the content should define its height.

### Actual Behavior
The swiper and each swipe gets an inline-height set, which equals the height of all slides together.
i.e. if I have 2 slides of a natural height of 500px they get a height set to 1000px, width 3 slides it's 1500px, etc.
If I set the direction to `horizontal`, it works fine.

You can see the behaviour in this fiddle: https://jsfiddle.net/y1f5z4uo/1/

**Comment by janein** [comment]
I used a workaround for now, where I get the curernt slide, calculate its height and apply it to the wrapper.

**Comment by krzysiek1507** [comment]
Hi @janein Try to set max height for `swiper-container`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
