### ISSUE TITLE
Mouse wheel sensitivity for non freeMode

### ISSUE THREAD

**Issue by nr1q** [nolimits4web/Swiper#2018]
Hello! well, actually I'm not reporting a bug, but just asking about the possibility to have mousewheel sensitivity when the freeMode is set to false. I tried to modify your code but had no success.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
