### ISSUE TITLE
slideVisibleClass added for wrong slides, if slide's width isn't integer

### ISSUE THREAD

**Issue by sharkerator** [nolimits4web/Swiper#2020]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.1.
* Platform/Target and Browser Versions: Windows 10, Chrome 56.

Set parameters for slider: 
'slidesPerView: 7,
 centeredSlides: true,
 loop: true,
 watchSlidesVisibility: true'.

Class 'swiper-slide-visible' added to visible slides, but it also added to non-visivle slides, if slide's width isn't integer.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
