### ISSUE TITLE
Lighthouse PWA Debugger doesn't like the use of Date.now(), recommends performance.now() instead

### ISSUE THREAD

**Issue by JacobDB** [nolimits4web/Swiper#2023]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: v3.4.1
* Platform/Target and Browser Versions: Mac OS 10.12.2, Chrome 56.0.2924.87 (64-bit)

### What you did
Ran Google's [Lighthouse progressive web app debugger](https://github.com/GoogleChrome/lighthouse) against Swiper.

### Expected Behavior
A perfect score should be met.

### Actual Behavior
Pretty good overall, the only thing that jumps out as something I can't fix without modifying your code is "Avoids `Date.now()` in its own scripts". Google recommends using `performance.now()` instead. [Here's some information as to why.](https://developers.google.com/web/tools/lighthouse/audits/date-now)

Could you consider updating your one use of `Date.now()` to this, so that Lighthouse will stop complaining? Thanks much :)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
