### ISSUE TITLE
[Bug] Autoplay works only when swiping first manually and setting autoplayDisableOnInteraction to false.

### ISSUE THREAD

**Issue by 1BJK903** [nolimits4web/Swiper#2025]
This is a (multiple allowed):
* [x] **bug**
* Swiper Version: **Swiper version 3.2.7 with Ionic 1**
* Platform/Target and Browser Versions: **Every platform + browsers**

[Bug] Autoplay works only when swiping first manually and setting autoplayDisableOnInteraction to false.

Hi all,

The problem is that I can't get autoplay work automatically (!). I have to slide manually at first to get the autoplay working... it automatically slides through the slides ONLY when I manually move the first slide first...

I noticed that the above only works when: I set `autoplayDisableOnInteraction: false `, btw.

All options:

    $scope.options = {
      autoplay: 2500,
      autoplayDisableOnInteraction: false,
      loop: false,
      speed: 500,
      paginationType: 'progress',
    };

Is this a bug or whatsoever?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
