### ISSUE TITLE
its not working in ng-repeat

### ISSUE THREAD

**Issue by manojkumar7488** [nolimits4web/Swiper#2029]
its not working in ng-repeat in angulrjs. any idea how to working with it

**Comment by CFlop** [comment]
It is hard to say why it does not work because we cannot see how it is implementet. Mostly there is problem with the initialization. I got the following scenario in my head: first of all you initialize Swiper then your ng-repeat get finished. There is a problem because Swiper does not know the new rendered items by angular.
Please take look here: http://stackoverflow.com/a/15208347/7324839
It will show you how its possible to call a function when the ng-repeat is done.
Otherwise show us the way of your implementation this might help.

**Comment by ErvinLlojku** [comment]
@manojkumar7488 It is not an issue of the slider, the slider is being initialized before the dom is ready 
you can use this easy fix or init the slider and add the images dynamically..Check the api documentation
`setTimeout(function(){
 // carousel initialization
}, 1)`
Enjoy coding!
