### ISSUE TITLE
Callbacks like "onSlideChangeStart" not working for touch transitions

### ISSUE THREAD

**Issue by CorySchulz** [nolimits4web/Swiper#2033]
I'm having an issue with this callback (and others) not working when moving to a new slide.
The issue looks like this:
- I move to a specific slide by clicking a pagination element
- If I drag across the slider it will transition to the next slide triggered by the touch events, the pagination will update, but the onSlideChangeStart callback won't get called
- I've found using the onTransitionStart callback will still trigger every time, so I'm using that instead, which looks like it gets called before onSlideChangeStart, so maybe it's faster / better

I can try and package this up and post it for you to look at if you want.

**Comment by viet241** [comment]
same issue :(

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
