### ISSUE TITLE
watchSlidesVisibility does not include the initial image

### ISSUE THREAD

**Issue by thaicyn** [nolimits4web/Swiper#2042]
This is a (multiple allowed):
* [x] bug
* [X] enhancement

* Swiper Version: 3.4.1
* Platform/Target and Browser Versions: Windows

Swiper initialize with lazy load something like this:
```
var swiperObjects = new Swiper($(".swiper-top100"), {
		        slidesPerView: 4,
		        slidesPerGroup: 2,
		        spaceBetween: 0,
                        preloadImages:true,
                        lazyLoading: true,
		        watchSlidesVisibility: true,
		        nextButton: '.arrow-nav .li_next',
		        prevButton: '.arrow-nav .li_prev',
                        onLazyImageReady(swiper, slide, image){
                              console.log(image);
                        }
});
```
Maybe related to this issue: https://github.com/nolimits4web/Swiper/issues/1618

The setting "watchSlidesVisibility" only works for other images but not the first 4 images. I was expecting when browser load a page, when the swiper is not in viewport yet, the first 4 image will not trigger the callback until the user scroll down and the swiper reach into browser viewport. Any work around to this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
