### ISSUE TITLE
Everything blurry in Chrome only

### ISSUE THREAD

**Issue by TomDeSmet** [nolimits4web/Swiper#2043]
I know this has been said a lot and a few work arounds have been posted,  but it seems that this is in Chrome only (so maybe it's completely browser dependend).

You can even see it on the swiper on the homepage of http://idangero.us/swiper. The texts in the blue bar on top are not sharp. In Firefox, Edge and Safari it's all fine.

So, any recent new ideas how to fix this.

**Comment by Tusko** [comment]
`roundLengths : true` will fix it :)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
