### ISSUE TITLE
Allow direction "vertical-reverse"

### ISSUE THREAD

**Issue by indus** [nolimits4web/Swiper#2044]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows, CHROME

I want to have a slide with the first slide at the bottom and others on top. "slideToClickedSlide" should then work as one would expect.

I tried setting:
``` CSS
    flex-direction: column-reverse;
```
but then duplicated slides are on the wrong side.

**Comment by indus** [comment]
BTW: This is one of the most commented feature requests in slick: https://github.com/kenwheeler/slick/issues/818

**Comment by Efflamm** [comment]
Did you tried this ?

`       slidesToScroll: -1,
`

[Slick carousel right to left](https://stackoverflow.com/questions/29770969/slick-carousel-right-to-left)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
