### ISSUE TITLE
Pagination on coverflow effect does not work

### ISSUE THREAD

**Issue by moabi** [nolimits4web/Swiper#2054]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Windows // Chrome 56.0.2924.87
* uri: http://idangero.us/swiper/demos/18-effect-coverflow.html

### What you did
tried to use pagination on a coverflow

### Expected Behavior
pagination should work, click on the dot to get the desired slide

### Actual Behavior
the hand grabs the slide,and it is not possible to click on pagination dots, pagination is useless.

**Comment by psiclonehi** [comment]
Have you tried using CSS to put the .swiper-pagination indices to a higher number?

**Comment by moabi** [comment]
Yes, z-index won't fix it.

**Comment by nebo6** [comment]
it's look like event.preventDefault() on click function

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
