### ISSUE TITLE
slide-effect like from apple

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Swiper#2055]
This is a (multiple allowed):
* [] bug
* [] enhancement
* [x] feature-discussion (RFC)

Would be nice to add a slider transistion (from one slide to another) such as the slider from the homepage of apple.com. It shrinks the last slider from top to background while the next slider comes from left to right with a calm effect like a book. Please add such a slider effect and maybe the kind of parralax effect.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
