### ISSUE TITLE
Zoom : Cursor is not changed to drag while zoomed state

### ISSUE THREAD

**Issue by kumaravel95** [nolimits4web/Swiper#2063]
* [ ] enhancement

* Swiper Version:V 3.4.2
* Platform : macOS, Windows , CHROME (All desktop browsers).

### Expected Behavior
Cursor need to change to drag while zoomed state. and if the zoomed state changed to normal state then cursor need to changed to normal cursor.

### Actual Behavior
Cursor is always in normal cursor.

Attachemnt:
http://www.screencast.com/t/SQZl2BB3J

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
