### ISSUE TITLE
Coverflow effect is not functioning properly on page load.

### ISSUE THREAD

**Issue by depz** [nolimits4web/Swiper#2070]
This is a (multiple allowed):
* [x] bug(maybe, maybe not)
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2.
* Platform/Target and Browser Versions: Chrome, Mozilla, Ie.

### What you did
I'm not exactly sure what to do actually, I googled it, but nothing popped out, so i figured i ask here.

### Expected Behavior
Coverflow effect should work properly, but it isn't. 

### Actual Behavior
Coverflow effect is not working when i load the page, it starts working when i even slightly resize my browser. On mobile, everything is okay, so i'm not really sure what exactly i'm doing wrong. Keep in mind that i've copied coverflow js and css code 1:1

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by ejrudy** [comment]
Having the same issue, the transition doesn't start unless the page is resized.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
