### ISSUE TITLE
CPU overhead in iOS 10

### ISSUE THREAD

**Issue by TomasPangzi** [nolimits4web/Swiper#2074]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions:  CORDOVA, IOS, iOS10

### What you did
Two swiper in one view,  autoplay fire or swipe by user
### Expected Behavior
smooth, and scroll

### Actual Behavior
CPU will overhead, Usage: 100%

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
