### ISSUE TITLE
Default backgnoud ou swipe

### ISSUE THREAD

**Issue by Gidaa** [nolimits4web/Swiper#2076]
Hey everybody !

I have a little problem with a JS gallery so I leave it to you, after 6 hours of research I do not think I will find the solution of myself.
Fact ; I would just put a gallery (with png img) JS ahead another animated JS. But the gallery has a background by default and I really can not figure out how to remove it. I searched HTLM, CSS and JS, div placements, changes in background values, nothing work...
The two JS are:
• http://vincentgarreau.com/particles.js/ in the background
• http://idangero.us/swiper/demos/#.WPKdXqKkKUk from above
I think that someone would help me in the depths of this code to remove this damn gray background by default or at least hide it or make it quite transparent.

Thank you in advance ! 
And sorry for my english.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
