### ISSUE TITLE
Swiper autoplay not working after `removeAllSlides` and then `appendSlide`

### ISSUE THREAD

**Issue by cmal** [nolimits4web/Swiper#2077]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: mac 10.11.6  Chrome 57.0.2987.133 (64-bit)

### What you did
var sw = new Swiper({autoplay: 2000});
sw.appendSlide(slide);
sw.removeAllSlides(); // or remove the only one left slide with sw.removeSlide(the_only_slide_left);
sw.appendSlide(slide1);
sw.appendSlide(slide2);

### Expected Behavior
slide1, slide2 is autoplaying now.

### Actual Behavior
slide2 is showing forever.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by cmal** [comment]
I asked this question on stackoverflow, and someone tell me I should call .update to force update after call .remove. So close.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
