### ISSUE TITLE
Looping doesn't work with loop:true and slidesPerColumn > 1

### ISSUE THREAD

**Issue by piotr-sobczyk** [nolimits4web/Swiper#2079]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: tested CHROME (but probably any platform).

### What you did
See this fiddle: https://jsfiddle.net/sobczyk_peter/ggyofvnw/

### Expected Behavior
When reaching the last slide and scrolling right, I would expect the first slide to appear again.

### Actual Behavior
When you scroll right to the last slide and try to scroll right again, it won't be possible, despite loop:true setting. Interestingly looping works correctly when scrolling left.

This happens only for slidesPerColumn > 1. When you change slidesPerColumn to 1, you'll notice that the looping works correctly when scrolling right.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
