### ISSUE TITLE
bug, the text appears without a transition

### ISSUE THREAD

**Issue by andrestef** [nolimits4web/Swiper#2083]
[x] bug
[ ] enhancement
[ ] feature-discussion (RFC)

Swiper Version: Swiper 3.4.2
Platform/Target and Browser Versions: Iphone 6 - chrome mobile - safari mobile

Dear, how do you fix the bug that appears by demo 28 (28-parallax.html) with a mobile device (iphone 6 with safari and chrome)?
It happens that at the swipe the text appears without a transition, often I also happen with the images.

thank you

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
