### ISSUE TITLE
slideChangeEnd not fired from slideTo/pagination

### ISSUE THREAD

**Issue by Pilen** [nolimits4web/Swiper#2088]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Linux, Chromium 57.0.2987.98

### What you did
So I found that when clicking on pagination bullets to change slides, the `slideChangeStart` event is fired, but `slideChangeEnd` is not.
I poked around in swiper.jquery.js in `slideTo` where
```
            s.previousIndex = s.activeIndex || 0;
            s.activeIndex = slideIndex;
            console.log("indexes:", s.previousIndex, s.activeIndex);
```
I can see the indexes printed twice in the log.
First it is correct with different values for the indexes, then I can see the logging from the `onSlideChangeStart` event handler.
Then the same part of the code is apparently executed again, but this time the both the indexes are the same as the new activeIndex.
Thus when the following is executed
```
                    s.wrapper.transitionEnd(function () {
                        if (!s) return;
                        console.log("before onTransitionEnd:", s.previousIndex, s.activeIndex);
                        s.onTransitionEnd(runCallbacks);
                    });
```

The indexes are the same and with `s.activeIndex` being equal to `s.previousIndex`, and thus in `s.onTransitionEnd` never emits the `onSlideChangeEnd` event.

### Expected Behavior
The slideChangeEnd event should always be emitted at the end of a change

### Actual Behavior
It is not fired

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
