### ISSUE TITLE
onSlideChangeEnd making illegal behavior

### ISSUE THREAD

**Issue by AminulBD** [nolimits4web/Swiper#2097]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Google Chrome Version 58.0.3029.81 (64-bit)  and Windows 10 CU.

### What you did
````
settings.onSlideChangeEnd = function(swiper) {
    console.log('Slide Changed');
}
````

### Expected Behavior
The log will come if the slide changed.

### Actual Behavior
The log comes every time if slide changed or not while I'm trying to move the slide.

### Additional Information
You can check [this video](http://d.aminul.net/fC7Kc/p7Ny353D) what happening actually.

But, it's working fine as I expected with 3.2.7 version of Swiper.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
