### ISSUE TITLE
Autoplay still not working with 3.4.2 update

### ISSUE THREAD

**Issue by 1BJK903** [nolimits4web/Swiper#2100]
**Autoplay still not working with 3.4.2 update.** 

Problem: autoplay ONLY works when you _MANUALLY_ slide the first slide.... after that, it starts the autoplay, but that's not what we want.

What do I want: to start the autoplay as it's supposed to start, namely: without having to slide it manually first, but start it **directly**!

 ```
 $scope.options = {
    autoplay: 2500,
    effect: 'coverflow',
    autoplayDisableOnInteraction: false,
    loop: false,
    paginationType: 'progress',
    coverflow: {
      rotate: 50,
      stretch: 0,
      depth: 100,
      modifier: 1,
      slideShadows: true
    }
  };
```

I tried setting `loop: true`, but that does not work either...

Question: how to solve this?

**Comment by webappcreations** [comment]
I don't experience that behavior with Swiper. For me, autoplay: 4000 works nicely in the 3.4.2 version.
Maybe it has to do with Angular? Like it is not properly initialized yet or something?  

You can see a working Autoplay-Swiper here for eg. [diessbacher-babl.de](http://diessbacher-babl.de/)

I use the jquery-Version of the Swiper here though (Maybe there are some unwanted differences?)

Cheers, 
Robin

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by 1BJK903** [comment]
I fixed this. The problem was that the images I was loading (external), were before the slider was initialized. This resulted into a slider that was not picking up the options I defined. Fixed now.
