### ISSUE TITLE
Error on working with containers of CSS frameworks

### ISSUE THREAD

**Issue by hansthinhle** [nolimits4web/Swiper#2101]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2.
* Platform/Target and Browser Versions: macOS, CHROME.

### What you did
I just wanna wrap the Swiper content in a container with Bootstrap or Bulma, or any other CSS Frameworks

### Expected Behavior
Of course, my expectation is the layout could be like the demos:
[http://idangero.us/swiper/demos/](http://idangero.us/swiper/demos/)

### Actual Behavior
But the layout is broken after placing the Swiper content into the containers:

1. on using with Bootstrap: https://codepen.io/x1angel/pen/qmoNZW
2. on using with Bulma: https://codepen.io/x1angel/pen/rmdeor

**Comment by 7iomka** [comment]
```
.swiper-wrapper {
    box-sizing: border-box;
}
```
This solves for me the problem of working with nested containers in bootstrap 4

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
