### ISSUE TITLE
clickedIndex/clickedSlide undefined when using nested swiper

### ISSUE THREAD

**Issue by bektasozer** [nolimits4web/Swiper#2102]
Bug. 
Version 3.4.2.

swiper.clickedIndex and swiper.clickedSlide seem to be _undefined_ on click of the parent swiper when a nested swiper is being used. Though it is fine when clicking a slide without a nested swiper.

Refer to this [fiddle](https://jsfiddle.net/8e964Lhb/).

Thanks :)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
