### ISSUE TITLE
onImagesReady is not called on Firefox 53.0.2

### ISSUE THREAD

**Issue by MaxInMoon** [nolimits4web/Swiper#2105]
* [x] bug

* Swiper Version:  3.4.2
* Platform:  osX Sierra, Firefox 53.0.2 (64 bits)

`onImagesReady` event callback is not called on Firefox, but works on CHrome & Safari

any ideas?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
