### ISSUE TITLE
Add a static method of destroy all instances

### ISSUE THREAD

**Issue by bq-hentai** [nolimits4web/Swiper#2108]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

### What you did

Add a static method `Swiper.destroyAll` to destroy all instances.

I push an instance to `__swipers` after created in closure. And support a destroyAll method to clear.

A `destroyAll` is like
```
Swiper.detroyAll = function() {
    __swipers.forEach(i => {
       i && i.destroy(true, true);
    });
});
```

### Expected Behavior

Just like the name `destroyAll`, we can use Swiper to clear all instances when we need this.

**Comment by bq-hentai** [comment]
btw,
When we init, we can push instance to __swipers, just like ` __swipers.push(s)`
when we destroy, clear instance in __swipers, just like `__swipers.splice(__swipers.indexOf(s), 1)`

**Comment by xdemocle** [comment]
I can't even destroy a single swiper :D 
Wondering why I can't use destroy() in my swiper instance like:
mySwiper.destroy()

**Comment by bq-hentai** [comment]
@xdemocle what do you mean ? You can't destroy one ? or you don't need destroy instance?

**Comment by xdemocle** [comment]
@bq-hentai in the end I gave up, because in my swiper instance I was receiving errors that destroy() method was not a function.

**Comment by bq-hentai** [comment]
@xdemocle maybe sth. wrong in ur codes.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
