### ISSUE TITLE
pagination working incorrectly while using slideTo

### ISSUE THREAD

**Issue by guillaumebaeriswyl** [nolimits4web/Swiper#2132]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Chrome and mobile

### What you did
The idea is that when you click on an image from an index of thumbnails, it should swipe to the correct image. 

### Expected Behavior
This works. But :

### Actual Behavior
The pagination is a bit laggy. It doesn't refresh. 
For instance, if you click on the thumbnail number 2, it goes to the image number 2, but the pagination stays at 0. Then if you want to change the slide with the arrow key, instead of going to slide 3, it will go to slide 1, because the pagination was stuck at 0.

Live version : www.dianedeschenaux.ch/beta -> section "selected works"

Thanks

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
