### ISSUE TITLE
Infinite loop with 4 slides

### ISSUE THREAD

**Issue by awsomedesigner** [nolimits4web/Swiper#2134]
Hello swiper,

I user your slider in my blog and i want infinite loop in my slider. My options are given below
```
pagination: '.swiper-pagination',
slidesPerView: 4,
autoplay: 5000,
autoplayDisableOnInteraction: false,
paginationClickable: true,
loop: true,
loopAdditionalSlides: 4,
spaceBetween: 30,
nextButton: '.swiper-button-next',
prevButton: '.swiper-button-prev'
```
but my loop is not working. so how i can set loop in my slider?

**Comment by aplblpsil** [comment]
`loop: true,
loopedSlides: 4,
slidesPerView: 'auto'`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
