### ISSUE TITLE
Syntax error in Edge browser

### ISSUE THREAD

**Issue by AlexWayfer** [nolimits4web/Swiper#2136]
This is a bug.

* Swiper Version: 3.4.2.
* Platform/Target and Browser Versions: Edge 15.15063, Windows 10.

### What you did

I don't know, this error from our [Sentry](https://sentry.io/).

### Expected Behavior

No errors :)

### Actual Behavior

Error: __Syntax error__ on 719 line of `swiper.jquery.js`

```
if (typeof s.params.width !== 'undefined') {
```

I didn't found similar issues.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
