### ISSUE TITLE
Autoplay Video on Mobile

### ISSUE THREAD

**Issue by Exposian** [nolimits4web/Swiper#2153]
Hello all!
I am trying to make the video to Autoplay on Mobile. Autoplay video works fine on Desktop but not on IOS devices.
Has anyone been able to make this work on Mobile?
Kind regards

**Comment by alejandroiglesias** [comment]
That is related to restrictions applied by browser vendors on mobile devices. More info:

- https://webkit.org/blog/6784/new-video-policies-for-ios/
- https://developers.google.com/web/updates/2016/07/autoplay

**Comment by julmot** [comment]
@alejandroiglesias From my testing results this is a restriction of Swiper and not iOS. iOS autoplaying works on iOS10+ if the video is the first slide in a full width slideshow. However, if the video is not the first slide (so it's initially hidden), iOS detects that and won't play the video since it thinks it's hidden.
