### ISSUE TITLE
Loop not working when multiple rows/columns

### ISSUE THREAD

**Issue by followthemadhat** [nolimits4web/Swiper#2155]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: MAC OS X

When slidesPerColumn > 1 (e.g. multiple rows/columns) the loop mode doesn't work. When there's only one row everything works fine. Also, the next button doesn't work, while the previous button works fine.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
