### ISSUE TITLE
swiper exists a bug?

### ISSUE THREAD

**Issue by ChinaDragonHunter** [nolimits4web/Swiper#2157]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by ChinaDragonHunter** [comment]
in PC,in chrome.There will be a blank on the right side of the period.for example,http://123.207.179.129:8080/mars/
in mobile,there is no problem.

**Comment by hacknug** [comment]
@ChinaDragonHunter you can probably solve your issue using the `loopAdditionalSlides` parameter. This will tell Swiper how many slides it should clone when using `loop: true`.

**Comment by ChinaDragonHunter** [comment]
It is not work。
I found scroll forward or back ,both exists the white block。
Here is the code：
var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        effect: 'coverflow',
        grabCursor: true,
        centeredSlides: true,
        slidesPerView: 'auto',
        coverflow: {
            rotate: 50,
            stretch: 0,
            depth: 100,
            modifier: 1,
            slideShadows : true
        },
        loopedSlides: 3,
        loopAdditionalSlides: 9,
        spaceBetween: 5,
        loop: true,
        autoplay: 1500,
        autoplayDisableOnInteraction: false
    });
The value of loopAdditionalSlides,I tryed to use ‘0’，‘1’，‘3’，‘9’。it was not work.

**Comment by hacknug** [comment]
I think there's something wrong with the way `loopAdditionalSlides` and `loopedSlides` work. But I just took a look at your demo and I think it will get fixed as soon as you have a few more slides. If you need to make it work when there's only three of them, you could add them twice.

I also saw you're adding both versions of Swiper (vanilla and jQuery) and since you also have jQuery in your scripts, you could get rid of the vanilla version to save your users an extra unnecessary download.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
