### ISSUE TITLE
jQuery conflict with Semantic UI

### ISSUE THREAD

**Issue by tmikaeld** [nolimits4web/Swiper#2163]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Any

### What you did
Include the jQuery version of Swiper.

### Expected Behavior
Animations to work.

### Actual Behavior
Animations not working due to conflict.

Non-jQuery version works, so jQuery Swiper seems to trigger Semantic UI animations which it shouldn't.

Example: https://jsfiddle.net/0mtt2phe/2/

**Comment by mogholito** [comment]
+1
that's right, this bug exist for a long time ago, but there is no problem to use the vanilla javascript version.

**Comment by mogholito** [comment]
Agree! Especially as jQuery already weighs about 90kb. 
Semantic-UI is fairly used today, it relies on jQuery and its javascript is huge, so every kilobyte saved is welcome. I hope this bug will be corrected soon. All my support to the team

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by nolimits4web** [comment]
There is no more jQuery version of Swiper
