### ISSUE TITLE
"slideToClickedSlide" option is failed on Coverflow effect

### ISSUE THREAD

**Issue by TechQuery** [nolimits4web/swiper#2180]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: **3.4.2**
* Platform/Target and Browser Versions: **Windows 7 + Chrome 55** (my development environment)

### What you did
```JavaScript
new Swiper('.swiper-container', {
    centeredSlides:         true,
    slidesPerView:          'auto',
    slideToClickedSlide:    true,
    grabCursor:             true,
    loop:                   true,
    pagination:             '.swiper-pagination',
    paginationClickable:    true,
    effect:                 'coverflow',
    coverflow:              {
        rotate:     0,
        stretch:    300,
        depth:      300
    },
    onClick:                function (swiper) {

        console.log(swiper.clickedIndex, swiper.clickedSlide);

        //  These two properties will be undefined
        //  as clicking on slides behind the current slide
        //  in coverflow effect.
    }
});
```

### Expected Behavior
Slide to the slide which is clicked on.

### Actual Behavior
There's no difference between `true` or `false` value of `slideToClickedSlide`, no sliding on click.

**Comment by slaby93** [comment]
@TechQuery I was working with a similar slider on Friday. I had a similar problem because the content of slide was a lot smaller than actual slide ( it had margins ). I fixed it by adding pointer-events: none to slide and pointer-events: all to underlying dom and attached custom function to trigger slideTo function :) So basically events ignored .swiper-slide element.
