### ISSUE TITLE
Responsive slides 

### ISSUE THREAD

**Issue by MrAndrianos** [nolimits4web/Swiper#2181]
I need a direction! I use the latest swiper API version into an opencart template. The issue is the height of the swiper-container. When i resize the screen the slides are cutting off ! Any tip ?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
