### ISSUE TITLE
slideOffSetAfter is not working on multirow swiper

### ISSUE THREAD

**Issue by ext-rafael-ximenes** [nolimits4web/swiper#2220]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.3.1.
* Platform/Target and Browser Versions: Chrome 61, Linux (ubuntu)

Codepen with live example: https://codepen.io/anon/pen/eGWYeb
Base code from Demos Gallery.

### What you did
I need a swiper multirow (2 rows) with one element  having all rows as its height. 
Could not accomplish since this taller element forces the entire row to be taller, like a table would do.

Looking in the API, slidesOffsetBefore and slidesOffsetAfter, by its descriptions, could set my desired effect, since the bigger slide need to be placed at the end of all slides. 

### Expected Behavior
slidesOffsetBefore is expected to create an Offeset before all Slides.(like Api docs suggest)
slidesOffsetAfter is expected to create an Offeset after all Slides. (like Api docs suggest)

### Actual Behavior
- [x] slidesOffsetBefore works like a charm.
- [ ] **slidesOffsetAfter is completely ignored**

### Extra: 
With 1 row it slidesOffsetAfter works fine. Is it a Multirow limitation? Did I made a mistake with something?

**Comment by ajschmidt8** [comment]
I'm having the same issue. I can't even get it working with a single row. I forked your CodePen and made some changes to show my issue (below). I'm trying to show one slide at a time but have the two adjacent slides "peek in" so to speak. Hopefully we can get this resolved soon!

https://codepen.io/anon/pen/NwvvNJ

**Comment by tobias47n9e** [comment]
When I use:

```
new Swiper('.container', {
    slidesOffsetBefore: 40,
    slidesOffsetAfter: 40,
}
```

the `slidesOffsetBefore` works but `slidesOffsetAfter` is ignored (`swiper-wrapper` class has `translate3d(40px, 0px, 0px)`).

But when I then drag the slider to the left it will settle back into a position where `slidesOffsetAfter` works but `slidesOffsetBefore` is ignored (`swiper-wrapper` class has `translate3d(-40px, 0px, 0px)`). So it seems the code can currently only do 1 of those 2 transforms, which is not really the desired result when using both of these settings together.

**Comment by tobias47n9e** [comment]
@nolimits4web Can you take a look at this use case? I would like to use `slidesOffsetAfter` and `slidesOffsetBefore` to center the slides within the wrapper. The reason is, that the shadows of the individual slides should be cut off at the edge of the screen and not in the middle where it leads to a undesired visuell effect:

![bad_shadow_cut_off](https://user-images.githubusercontent.com/6953323/33162870-10069a3c-d02c-11e7-84d8-a1d6b24db1fa.png)

Here is a pen showing the issue:
https://codepen.io/anon/pen/JOvBPR

Maybe you could advise how this could be implemented or fixed if it is an issue?

**Comment by DexGuru** [comment]
It's caused by delayed response from the main script, but here's the solution...
wrap your initialization code in a time out function... like this
setTimeout(function(){
new Swiper(".swiper-container", {
//options here...
});
}, 100); //time can be any number the lower the better
This solution can solve almost all the problems with the slider.
enjoy...

**Comment by DexGuru** [comment]
try wrapping your initialization code in a time out function... like this
setTimeout(function(){
new Swiper(".swiper-container", {
//options here...
});
}, 100); //time can be any number
This solution can solve almost all the problems with the slider.
enjoy...
