### ISSUE TITLE
Swiping on a slide does not update the pagination active state on iOS Devices

### ISSUE THREAD

**Issue by rgracia** [nolimits4web/Swiper#2252]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: iOS 10 and 11

### What you did
We have a slider with the following basic settings:
      effect: 'slide',
      speed: 500,
      spaceBetween: 0,
      pagination: '.swiper-pagination',
      paginationClickable: true,
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev'

### Expected Behavior
When swiping on an iOS device, the pagination buttons should register an active class state change for the correct bullet.

### Actual Behavior
Swiping on a slide does not update the pagination active state. This only happens when swiping (touch). When a next or prev link are provided, the pagination is updated correctly. Emulating touch on Chrome works but real devices or emulators for iOS show the bug.

**Comment by nolimits4web** [comment]
I can't replicate your issue in iOS Safari. Probably issue somewhere on your side as all default setups work fine http://idangero.us/swiper/demos/030-pagination.html. And make sure you are using latest v4 version. If this issue is still happens for you in latest version. Create new issue and provide live example link to JSFiddle/Codepan or any link to preview it
