### ISSUE TITLE
thumbnail direction issue

### ISSUE THREAD

**Issue by cvaraj** [nolimits4web/Swiper#2253]
Hi @nolimits4web 

       Thanks for great plugin i'am really impressed but i have small doubt on thumbnail slider. if i set gallery image slide direction to rtl the thumbnail direction also changed i need image gallery alone move to rtl direction thumbnail want act as normal direction, is there any solution for this 

Thank You!

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.

It will save a lot of time for other contributors to check your issue and fix it.
