### ISSUE TITLE
slideNextTransitionEnd and slidePrevTransitionEnd events don't get triggered correctly in loop mode

### ISSUE THREAD

**Issue by daviddelusenet** [nolimits4web/Swiper#2298]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.3
* Platform/Target and Browser Versions: Mac Google Chrome Version 61.0.3163.100

### What you did
I just setup a slider with the `slidePrevTransitionEnd` and `slideNextTransitionEnd` bound to it. The slider has autoplay enabled and is looping. It has 4 slides.

### Expected Behavior
When I would log `next` or `prev` in the corresponding events I would expect 4x `next` in the console since the slider is going the next slide every time in autoplay.

### Actual Behavior
When going from the last slide to the first slide `prev` gets logged, which is wrong. Also, when you go back from the first to the last slide `next` gets logged, which is also wrong. See the screenshot below (just letting the slider run on autoplay).

![screen shot 2017-10-31 at 15 55 25](https://user-images.githubusercontent.com/1398418/32230685-0a05eb40-be54-11e7-968f-a2f90a0e96d4.png)

@nolimits4web can you please look into this?

**Comment by nolimits4web** [comment]
It is based on active and previous slide indexes, it is by design. Otherwise you can track previously active DOM elements manually and do the decision

**Comment by daviart** [comment]
At 2017-10-31 21:56:32, "David de Lusenet" <notifications@github.com> wrote:


This is a (multiple allowed):

bug

enhancement

feature-discussion (RFC)

Swiper Version: 4.0.2.

Platform/Target and Browser Versions: Mac Google Chrome Version 61.0.3163.100

What you did

I just setup a slider with the slidePrevTransitionEnd and slideNextTransitionEnd bound to it. The slider has autoplay enabled and is looping. It has 4 slides.

Expected Behavior

When I would log next or prev in the corresponding events I would expect 4x next in the console since the slider is going the next slide every time in autoplay.

Actual Behavior

When going from the last slide to the first slide prev gets logged, which is wrong. Also, when you go back from the first to the last slide next gets logged, which is also wrong. See the screenshot below (just letting the slider run on autoplay).

@nolimits4web can you please look into this?
