### ISSUE TITLE
选择cube切换特效的时候第四个元素里的gif图不能播放

### ISSUE THREAD

**Issue by 1977474741** [nolimits4web/swiper#2324]
选择cube切换特效的时候第四个元素里的gif图不能播放，其他都可以播，就第四个元素里的不会动，实测，pc和移动端都有这个问题。

**Comment by 1977474741** [comment]
Select the cube effect, and the GIF diagram in the fourth element cannot be played

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
