### ISSUE TITLE
Slide index ends up corrupt when updating 'slidesperview' dynamically and using loop

### ISSUE THREAD

**Issue by hfrid** [nolimits4web/Swiper#2338]
Seems like the slide index becomes corrupt if you change 'slidesperview' dynamically. I initially set slidesperview: 2 and update it to 4 when user devices switches orientation to landscape. The pagination breaks and it skips a few slides. If I set initial slidesperview to 4, landscape works fine but portrait is affected. 

`        
        var mySwiper = new Swiper('.swiper-container', {
          pagination: '.swiper-pagination',
          slidesPerView: 2,
          loop: true,
          centeredSlides: true,
          paginationClickable: true,
          autoplay: {
            delay: 5000,
          },
          spaceBetween: 0,
  // Navigation arrows
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev'
        });
`

Then update it:
`var mySwiper = $('.swiper-container')[0].swiper;
        mySwiper.params.slidesPerView = 4;
        mySwiper.update();
`

Reproduced on lastest 4.0.6 but I'm using 3.4.2.

**Comment by nolimits4web** [comment]
It is better to use breakpoints if you change number of slides per view depending on window size. Otherwise, loop must be recreated, you can check what to call to recreate the loop in such case at https://github.com/nolimits4web/Swiper/blob/master/src/components/core/breakpoints/setBreakpoint.js#L24-L29
