### ISSUE TITLE
How to disable style inline on element swiper-wrapper and swiper-slide

### ISSUE THREAD

**Issue by mrtuvn** [nolimits4web/swiper#2369]
I have noticed this problem when my slide display not nice. Maybe some style conflicts but i want to know if possible to disable styles by javascript apply on swiper-wrapper and swiper-slide. I have checked
I expected slide will have 100% size width but it fixed width by inline styles you can see in below
You can see in image below
![screenshot 2017-12-03 21 18 15](https://user-images.githubusercontent.com/1908873/33526294-5f7a1e3e-d871-11e7-9434-ab80e9048d2e.png)
I am using swiper v3. Effected in Slide mode, Loop false autoHeight true

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper (v4), please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by glemiere** [comment]
I agree with this. The feature would be needed because the width of the slides is wrong at first loading, until you resize the page manually.
