### ISSUE TITLE
Bug gallery in landscape mode

### ISSUE THREAD

**Issue by andrestef** [nolimits4web/swiper#2382]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: any mobile browser, fullscreen macOs mode.

Swiper in Thumbs Gallery mode loses correspondence between gallery and thumbnail when it suddenly switches from landscape to portrait mode and portrait to landscape mode.
The same situation occurs when switching from the windows view to the extended view of macOs.
Probably the code does not update sudden changes in size and proportion of the viewport.
How can i fix this issue?

[gallery](http://idangero.us/swiper/demos/300-thumbs-gallery.html)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
