### ISSUE TITLE
(IE 10) Object doesn't support property or method 'use'

### ISSUE THREAD

**Issue by Warptimer** [nolimits4web/Swiper#2383]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Internet explorer 10

Not working in ie 10

**Comment by Mudassir-23** [comment]
@Warptimer we were facing the exact same issue in IE10. The source of the problem is __proto__ on the function which is not available in IE 10.
<img width="668" alt="screen shot 2017-12-12 at 3 42 43 pm" src="https://user-images.githubusercontent.com/34403479/33879063-482febee-df53-11e7-9854-98378eb82ed0.png">
We were able to resolve this by adding __proto__ polyfill for IE10 
[Proto polyfill](https://www.npmjs.com/package/proto-polyfill)
Hope it helps!

**Comment by Warptimer** [comment]
@Mudassir-23 thank you so much. You are rock!
