### ISSUE TITLE
Thumb Gallery Loop Working Incorrectly

### ISSUE THREAD

**Issue by bariskrdrl** [nolimits4web/swiper#2454]
if you encounter this problem and solve it, show me how you did it.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

**Comment by DanielRuf** [comment]
What exactly doe snot work? Please be more specific.

**Comment by DanielRuf** [comment]
At least we gave the issue that loop produces some weird transitions when an end is reached.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by bariskrdrl** [comment]
I'm sorry. There was a problem.
You can see the bottom line here.

Codepen link is here: https://codepen.io/bariskaraderili/pen/ZvdJMm

That's the code I wrote. Is something like this possible

var galleryTop = new Swiper('.gallery-top', {
      loop: true,
      spaceBetween: 10,
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
    var galleryThumbs = new Swiper('.gallery-thumbs', {
      loop: true,
      spaceBetween: 10,
      slidesPerView: 3,
      touchRatio: 0.2,
      slideToClickedSlide: true,
    });
    galleryTop.controller.control = galleryThumbs;
    galleryThumbs.controller.control = galleryTop;
