### ISSUE TITLE
ipad vertical swiper issue

### ISSUE THREAD

**Issue by cvaraj** [nolimits4web/swiper#2470]
hi @nolimits4web 

     I have used swiper vertical direction slider in desktop its working fine but in particularly ipad 9.3.5 vertical direction not working, any solution for this one?
   Thanks

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
