### ISSUE TITLE
how to set img to full content of the page

### ISSUE THREAD

**Issue by weebnoobi** [nolimits4web/swiper#2522]
i have a problem on desktop version/ larger resolution. i'm having trouble to set it to width 100%

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
