### ISSUE TITLE
centeredSlides interferes with watchOverflow behavior

### ISSUE THREAD

**Issue by mlegait** [nolimits4web/swiper#2581]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.2.2
* Platform/Target and Browser Versions: Chrome, Firefox, IE10+, Edge, iOS, Android
* Codepen : https://codepen.io/mlegait/pen/KoEJEK

### What you did
We would like to have a Swiper with 7 slides, 5 slides visible and the active slide in the middle.
```
var mySwiper = new Swiper ('.swiper-container', {
    slidesPerView: 5,
    spaceBetween: 0,
    initialSlide: 3,
    watchOverflow: true,
    centeredSlides: true,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    }
  })
```

### Expected Behavior
We don't want to have blank space before/after the first/last selectable slide.  We thought that thanks to `watchOverflow` it would be possible.

### Actual Behavior
The active slide is centered but if we slide to the first/last selectable slide, we have blank space.

**Comment by nolimits4web** [comment]
From `watchOverflow`  docs description:

> When enabled Swiper will be disabled and hide navigation buttons on case there are not enough slides for sliding

It is in case if you have total slides less than `slidesPerView` value.

Centered slides has empty space on sides by design - to make slides, obviously, centered. If you need to disable, you can probably set `allowSlidePrev = false` when you are on slide with index `2` and `allowSlideNext = false` when on slide with index `4` according to your example

**Comment by mlegait** [comment]
Hello,

Thank you for your answer 😄 

I made a new CodePen to test it : https://codepen.io/mlegait/pen/XqjXGE
It works when we use the arrows to slide but I don't find how to prevent having this blank space when swiping with the finger. I have looked at `touchMove` but I have no idea on how to use it for my use case.
