### ISSUE TITLE
Mousewheel Failing?

### ISSUE THREAD

**Issue by dejardine** [nolimits4web/swiper#2624]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.2.6
* Platform/Target and Browser Versions: macOS Chrome  66.0.3359.139
* Live Link or JSFiddle/Codepen or website with isssue: http://jsfiddle.net/Grafik/7t1oshxw/embedded/result/

### What you did
Refresh the page, and try to mouse scroll. The mousewheel scrolling fails intermittently. Once it fails if you switch to a new tab then back again it works.

### Expected Behavior
Free scroll with mousewheel

### Actual Behavior
Mousewheel slider control does not function

**Comment by hattamsoyunov** [comment]
I am also trying to solve it, I also ((found a solution? Thank you!

**Comment by miela** [comment]
I have the same issue. @dejardine did you solve this?

**Comment by hanoii** [comment]
Interesting, this is a very similar thing to something that's happening to me as well. Basically is like when as long as the arrow doesn't move or is there, swiper is in "no swipping" mode.

You don't need to go to a new tab, just move your mouse around a bit and it starts working again.

A similar thing can be reproduced here: http://idangero.us/swiper/demos/270-mousewheel-control.html

**Comment by hanoii** [comment]
The jsfiddle is very good actually, when you refresh, you even see that the cursor is plain. once you move it it goes to grab mode.

**Comment by hanoii** [comment]
Hmmm, I seem to have found a fix/workaround, although semantically is not quite right.

if you set releaseOnEdges to true, this kind of fixes it, see http://jsfiddle.net/Grafik/7t1oshxw/6/embedded/result/

Looking at the code I see a couple of things, first

https://github.com/nolimits4web/swiper/blob/8ef232e635cadda3f75da12ae6b9bd17816de57a/src/components/mousewheel/mousewheel.js#L113

If `!swiper.mouseEntered` the mousewheel doesn't work. The issue is that when you refresh the page, mouseenter has not triggered yet, so that's why it doesn;'t work.

On my use case, I also noticed that if you click on another window while keeping your swiper window on the back, attempting to scroll it also doesn't work because the mouse "left". I didn't want that to happen either and because of that line, I could remove the mouseenter/mouseleave validation.

Looking further along the code, on

https://github.com/nolimits4web/swiper/blob/8ef232e635cadda3f75da12ae6b9bd17816de57a/src/components/mousewheel/mousewheel.js#L141
and
https://github.com/nolimits4web/swiper/blob/8ef232e635cadda3f75da12ae6b9bd17816de57a/src/components/mousewheel/mousewheel.js#L145

releaseOnEdges seems to only affect swiper when freeMode is false, which is not my case, nor the fiddle, but this is not evident from the documentation. 

So I got my fix, although probably not in the right way. I wonder why `swiper.mouseEntered`is needed at all and it could be good to be able to disable it somehow, kind of what releaseOnEdges allows me to do but with a proper param name?
