### ISSUE TITLE
**slideNextTransitionStart** and **slidePrevTransitionStart** events are not working as expected

### ISSUE THREAD

**Issue by github-mayur** [nolimits4web/swiper#2743]
Thanks for great slider.

I have an issue while using events in slider. Specially Events for **slideNextTransitionStart** and **slidePrevTransitionStart** as I want to toggle something when slider start transition to Next/Prev direction.

But, here when I start dragging my slider with cursor, it does not fire event until I release cursor. It should execute event when I start dragging, I have tried **slideNextTransitionEnd** & **slidePrevTransitionEnd** too but it's not working as expected.

Can somebody help in this?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
