### ISSUE TITLE
Achieving 3d card stack effect

### ISSUE THREAD

**Issue by arjunmenon** [nolimits4web/swiper#2751]
This is a (multiple allowed):
* [] bug
* [ ] enhancement
* [X] feature-discussion (RFC)

There was a discussion [here](https://github.com/nolimits4web/Swiper/issues/1928). It would be better to open a new request for feature which is now most common on mobile devices. Card stack

Something like this would be really good. 
How can we achieve slider like this?
![fc5ir](https://user-images.githubusercontent.com/953959/44176138-41c36400-a106-11e8-9bd9-d9c43055ec06.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
