### ISSUE TITLE
Add horizontal scrolling to swiper (Feature Request)

### ISSUE THREAD

**Issue by Jonathan002** [nolimits4web/swiper#2752]
This is a (multiple allowed):
* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
- "angular2-useful-swiper": "^5.0.1"

* Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.
* Live Link or JSFiddle/Codepen or website with isssue: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_.

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.
Used the swiper in accordance with the angular2 wrapper package here: https://www.npmjs.com/package/angular2-useful-swiper

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.
I have a swiper-div with a large table that causes horizontal scrolling. The table cannot be scrolled horizontally within the swiper div and instead swipes to the next slide. I'm hoping an option/default behavior can be added where the div is scrolled all the way to the scroll bounds (e.g. fully horizontally scrolled to the end of the table before having swiper engage in swiping again for the next slide). 

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
Swiper does not allow horizontal scroll

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
