### ISSUE TITLE
When you do a vertical full-screen page with swiper, there is an input box in the page, and when you type text, the page is out of order.

### ISSUE THREAD

**Issue by Kennersky** [nolimits4web/swiper#2785]
When I do a vertical full-screen page with swiper, there is an input box in the page, and when you type text, the page is out of order

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
