### ISSUE TITLE
使用 swiper 4时候，swiper-slide 设置宽度时，比如100px，滑动时，可以一直向右滑动

### ISSUE THREAD

**Issue by sm0210** [nolimits4web/swiper#2806]
使用 swiper 4时候，swiper-slide 设置宽度时，比如100px，滑动时，可以一直向右滑动

#### html：
````
<div class="swiper-container" >
     <div class="swiper-wrapper">
        <div  class="swiper-slide">slide 1</div>
        <div  class="swiper-slide">slide 2</div>
        <div  class="swiper-slide">slide 3</div>
        <div  class="swiper-slide">slide 4</div>
        <div  class="swiper-slide">slide 5</div>
        <div  class="swiper-slide">slide 6</div>
     </div>
 </div> 
````

#### JS：
````
var mySwiper = new Swiper('.swiper-container');
````

#### CSS：
````
 .swiper-slide {
    width: 120px !important;
    height: 50px;
  }
````

![swiper](https://user-images.githubusercontent.com/10410886/45633899-9bd39280-bad3-11e8-806e-981a1e3f5a22.png)

**Comment by nolimits4web** [comment]
In English?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
