### ISSUE TITLE
Setting simulateTouch to false breaks scroll bar in Safari

### ISSUE THREAD

**Issue by jsheffers** [nolimits4web/swiper#2840]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.1
* Platform/Target and Browser Versions: macOS, Safari
* Live Link or JSFiddle/Codepen or website with isssue:  https://jsfiddle.net/pcwudrmc/61182/

### What you did
Enable a scroll bar with the default settings.  Set simulateTouch to false.  This stops the use of the scroll bar in Safari only.  Still works in Chrome.

```
var mySwiper = new Swiper ('.swiper-container', {
  direction: 'horizontal',
  loop: true,
  scrollbar: {
    el: '.swiper-scrollbar',
    hide: false,
    draggable: true,
    snapOnRelease: true
  },
  simulateTouch: false  // Breaks scroll bar in safari
});
```

### Expected Behavior
I would expect the scroll bar to still work.

### Actual Behavior
Scroll bar won't drag

**Comment by hanoii** [comment]
I debugged this down to:

https://github.com/nolimits4web/swiper/blob/aef21b8e6add21c86cc8681be83ac4647dc23c7a/src/components/scrollbar/scrollbar.js#L222-L237

With `simulateTouch` disabled and because webkit doesn't support pointerEvents safari ends up not registering `any` event at all. I tried to come up with a PR, but still haven't gotten it properly yet. It seems as that logic should not depends on simulateTouch at all. And even more, just by following the code, it looks like under certain circumstances both the mouse* events and touch* events will be registered but not really wanted (thinking like a touch desktop or the like?)

We (me and @jsheffers) disabled simulateTouch as some events of the application were lost on desktop, but as a temporary workaround I found out that by disabling `touchStartPreventDefault` I was able to work around our initial problem. 

Will report back if we found more issues.
