### ISSUE TITLE
Duplicate image loading at Chrome

### ISSUE THREAD

**Issue by AuthorProxy** [nolimits4web/swiper#3017]
This is a (multiple allowed):
* [x] bug

Duplicate image loading on first init and on every swipe, checked with lazy load: true
You can see it here at chrome network console: codesandbox.io/s/j27960ry75 or http://idangero.us/swiper/demos/370-lazy-load-images.html

Copied from https://github.com/kidjp85/react-id-swiper/issues/266

**Comment by ntucakovic** [comment]
Did you manage to find a solution?

Pen using react lib, https://codesandbox.io/s/0xr0rprx10 (bugs only in Chrome, FF works fine)

**Comment by nolimits4web** [comment]
Issue because of disabled caching on server with those placeholder images, so once image is preloaded and set as img src, it will be reloaded again because caching on that server is disabled. 

Closing as not related to Swiper

**Comment by 2078421** [comment]
It feels wrong that Swiper can request the same image more than once even when the server does not support caching.  When using an image that is externally hosted there may not be the option to change the cache headers and Swiper would be making extra unnecessary requests. It would be good to see a fix for this issue.

**Comment by AuthorProxy** [comment]
I use some cdn that block because instead of 30 images I request 90 at once.

30 - is base page size
30 more - my app bug which I will fix
30 - swiper bug

It's not chrome bug because simple img tag doesn't request images twice, so I think it is critical, because because for single user you should request twice more data and wait twice more time, cdn and browser should process twice more requests. What will be if there 1000 user requests instead of one

**Comment by sebcharrot** [comment]
I think this clearly is related to Swiper -- it's not default Chrome behaviour to download uncached images twice, so it must be something happening in the library.

**Comment by ntucakovic** [comment]
I've been debugging the issue, got to [this line](https://github.com/nolimits4web/swiper/blob/6b16107359b9e2e523eb03cc75bf4569940a22dd/src/components/lazy/lazy.js#L46):
```js
if (src) {
  $imageEl.attr('src', src);
  $imageEl.removeAttr('data-src');
}
```

Just a bit of background to cover author's comment. 

The line that sets src attribute, will cause additional load in case the original image doesn't have that exact same src attribute set (and it doesn't). On firefox, on that same line, additional network request isn't made.

## Problem
The problem lies in Lazy implementation, which calls `loadImage` function which will make one request by creating an image and attaching its `src` attribute, and then in it's onReady callback, it makes another request, by updating `src` with `data-src`.

## Solution
This issue could be solved by changing the `loadInSlide` function to not call the loadImage method, but rely on HTML API which will make a download by simply switching between `data-src` and `src` (or by passing a flag to the loadImage function to skip creating new image element). That way we'd lose the onload callback, which needs to be implemented differently somehow. So I see why the author made this decision.

I'm not sure what's the best way to solve this, and I think we should wait for the author to send additional details as the plugin overall is extremely reliable and well made. I'm sure this issue can be solved.
