### ISSUE TITLE
Fade Effect on Thumbs Gallery

### ISSUE THREAD

**Issue by yudiarnanda** [nolimits4web/swiper#3043]
How I can have a fade effect on the thumbs gallery?
https://idangero.us/swiper/demos/300-thumbs-gallery.html

I try to add:

`effect: 'fade'`

But the problem is thumbnail no clickable.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
