### ISSUE TITLE
How to loop when the slide has two lines

### ISSUE THREAD

**Issue by leonardop21** [nolimits4web/swiper#3044]
I have a project where I use the carousel with 2 lines, however, when it arrives at the end the slide locks and does not return to the first one. How can I do to leave in infinite loop?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
