### ISSUE TITLE
Syntax error: class Dom7

### ISSUE THREAD

**Issue by catamphetamine** [nolimits4web/swiper#3047]
So, it's funny how you ignore and close all issues without any reasons.

The error is the same as in this one: https://github.com/nolimits4web/swiper/issues/2670

The original screenshot from that issue is:

![N9mzUid](https://user-images.githubusercontent.com/477167/56297738-9574ca00-6139-11e9-81e0-a51424779d91.png)

The error is: your code imports the non-transpiled `dom7` thing somewhere.
You have to correct the import to import a transpiled `dom7` thing instead.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
