### ISSUE TITLE
ESM is not trully ESM

### ISSUE THREAD

**Issue by Antonio-Laguna** [nolimits4web/swiper#3073]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.5.0
* Platform/Target and Browser Versions: n/a

I had rollup set up but we're switching to Webpack that led me to a path of discovery around formats on JavaScript. Perhaps I'm wrong but what I can see on the `.esm` bundle is not trully ESM and, in fact, rollup[ is not doing](https://github.com/nolimits4web/swiper/blob/master/scripts/build-js.js#L38) `esm` but `es`. It does have untranspiled code.

Rollup does transpile node_modules whereas webpack does not and the two worlds collide. What I found is that providing a `module` on `package.json` pointing to a real `esm` bundle should be ideal. 

Right now I'm solving by doing `import 'swiper/dist/js/swiper.js';` but that breaks tree-shaking .

Perhaps I'm missing something here but would it hurt to switch `es` to `esm` on the `esm` bundles?

**Comment by nolimits4web** [comment]
ESM is ES module = contains `import` and `export` statements. Transpiling to ES5 syntax is not a job of Rollup or Webpack. It is a job of libs like Babel or Buble. Closing as not related to Swiper

**Comment by Antonio-Laguna** [comment]
ESM would leave imports and exports but would not use arrow functions nor let/const.

To me is counter intuitive that you're naming .esm but rollup is set up as es instead.

**Comment by slorber** [comment]
@nolimits4web problem is that in web/browserland, we expect libs to already be transpiled when published on npm, so that we can just consume the lib without requiring transpiling the /node_modules content

In this case, you have ESM output with ES6 imports/exports (which is fine) but the syntax is not transpiled, so importing this makes it painful for those wanting to support IE11/Edge which says "syntax error".
