### ISSUE TITLE
内嵌video标签，安卓微信浏览器小窗下白屏只有声音

### ISSUE THREAD

**Issue by zhangmeng0929** [nolimits4web/swiper#3132]
内嵌video标签，安卓微信浏览器小窗下白屏只有声音

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
