### ISSUE TITLE
Slider mouse-wheel freeze after usig slideTo() method

### ISSUE THREAD

**Issue by buglessir** [nolimits4web/swiper#3138]
When I use :

`mySwiper.slideTo(index, speed, runCallbacks);`

My slider freezes and mouse-wheel doesn't work for that !

But when an drag that, again mouse-wheel works right ...

It's really amazing

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
