### ISSUE TITLE
fade-effect navigation fast click

### ISSUE THREAD

**Issue by destimon** [nolimits4web/swiper#3140]
Hello.
I faced the problem with fade effect & navigation. Is it possible to change slide immediately when i clicking on the navigation button? There is problem, that i always must wait change-delay to be able to click to change to the next slide. I spotted that there isn't problem with standard effect, but with fade. I trying to do this with slidePerView: 1; . Maybe is there any parameter to solve this?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
