### ISSUE TITLE
Swiper slider does not work in tab 

### ISSUE THREAD

**Issue by mikij1029** [nolimits4web/swiper#3145]
It doesn't work in tabs(tab two).. help me 
https://mikij1029.github.io/web/020-navigation.html

**Comment by renatodeleao** [comment]
@mikij1029 and @nolimits4web have a possible similar issue.

### Context:
- I have menu that shows simply shows and hides swipers (similar to tabs) with `hidden` attribute which is equivalent to `display: none`. What I know is that In my situation is related with `autoplay`, because if i remove it from the config, everything works fine.
- version: `Swiper@4.5.0`

### Reproducible scenario:
1. toggle second tab before autoplay kicks in (delay). 
2. wait for autoplay to loop 1 slide
3. toggle back to the first tab
4. Swiper buttons don't work

Here's a video demoing: https://cl.ly/1c1e2831bb0e
Here's a reproducible example: https://ysoe2.csb.app/

#### Additional Notes 
- despite buttons not working, if drag is enabled after a first swiper, the slide comes back to work, and only then the buttons work, so it must be something related with updates and the buttons event listeners.

### How i've workaround it:
- manually triggering `swiper.slideTo(0,0)` does the trick, but it has unwanted sideffects: 
  - if autoplay was enabled, it's now disabled because of `disableOnInteraction`; 
  - i have to manually track current slide of each swiper, so when we get back to a tab, swiper is at the same position.

Hope it helps debugging, and thanks for swiper!
☮️

**Comment by Franky5831** [comment]
I had the same issue, i fixed it by setting the slides per view to 6 (in my case that is more or less how many slides there will be at the same time) and then overriding it with css setting the width of the slides to "auto", if you won't set the number of slidesPerView then no new slides will be added to create a loop.
