### ISSUE TITLE
Question: How to disable swiper for certain breakpoint only?

### ISSUE THREAD

**Issue by oneezy** [nolimits4web/swiper#3175]
I only want to allow swiper to work when it's between `0 - 768px` and not work in any resolution above that. Is there an easy way to achieve this?

**Comment by oneezy** [comment]
I actually found out about the `init()` and `destroy()` methods and by adding `init: false` to the swiper variable.. but how can i continuously init and destroy? right now it only allows me to do it once. here's what i currently have. https://codepen.io/oneezy/pen/eYOZzWY

**Comment by EHFVF** [comment]
Hi oneezy,
the problem is probably that the function init(); does not instantiate the swiper object with the same settings again.
A solution could be to replace the init() function call by a 'new' instantiation (on first call or after destroy() ). I quickly modified your js code accordingly, it should work (html and css unchanged), please check: 
[https://codepen.io/EFX/pen/xxKOwLw](https://codepen.io/EFX/pen/xxKOwLw)
Best,

**Comment by oneezy** [comment]
Thanks @EHFVF ! That's a perfect solution

**Comment by EHFVF** [comment]
Hi oneezy,
thank you for your reply.
Please be warned that it is not a perfect solution, it is a prototype.
To get it perfect, you should prevent potential js errors, e.g. if the user starts in desktop mode, then the call "swiper.destroy();" will throw an error, because the "swiper" object has not be instantiated, yet etc.
All the best,
