### ISSUE TITLE
When swiper nesting is used, text flipping occurs

### ISSUE THREAD

**Issue by zr9883** [nolimits4web/swiper#3176]
There will be problems with the following version of the browser:
In Sogou Browser 8.5.10.30798 version.
At Google Browser 74 version.
Adding a background can solve the problem.
Upgrading Google Browser to 75.0.3770.142 is also a solution.
---------------------------------------------------------------------------------------
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
    	
    		<link href="https://cdn.bootcss.com/Swiper/4.5.0/css/swiper.css" rel="stylesheet">
	</head>
	<style>
		.swiper-container {
		    width: 600px;
		    height: 300px;
		} 
	</style>
	<body>
		<div class="swiper-container one" >
		    <div class="swiper-wrapper">
		        <div class="swiper-slide" style="border: 1px green solid;">Slide 1</div>
		        <div class="swiper-slide">
		        	
		        	<div class="swiper-container two" >
					    <div class="swiper-wrapper">
					        <div class="swiper-slide" >two 1</div>
					        <div class="swiper-slide" >two 2</div>
					    </div>
					</div>
		        	
		        </div>
		        <div class="swiper-slide">Slide 3</div>
		    </div>
		</div>
	</body>
    
    <script src="https://cdn.bootcss.com/Swiper/4.5.0/js/swiper.js"></script>
    <script>        
	  var mySwiper = new Swiper ('.one', {
		effect: 'flip', //cube 3D  
			showLabel: false,
			grabCursor: true,
			observer: true, //修改swiper自己或子元素时，自动初始化swiper
			observeParents: true, //修改swiper的父元素时，自动初始化swiper
			spaceBetween: 30,
			centeredSlides: true,
			preventClicks: false, //默认true
			preventLinksPropagation: false,
			loop: true, //循环播放
			autoplay: 0,
		
	  })
	  
	  var mySwiper2 = new Swiper ('.two', {
		direction: 'vertical',
		loop: true,
		speed: 1000,
		autoplay: {
			delay: 1000,
			disableOnInteraction: false //就算触摸了也继续滚动
		},
	  })
	  
	</script>
</html>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
