### ISSUE TITLE
Drag Image cannot change slide in Firefox

### ISSUE THREAD

**Issue by ebadgh** [nolimits4web/swiper#3186]
Swiper drag not work fine in Firefox when cursor drag image in slide.
If you drag on image, and when swipe, mouse drag is locked on image and image move by mouse pointer until click somewhere else.

![image](https://user-images.githubusercontent.com/4308030/63637677-5250d780-c694-11e9-9d5d-194480bb9d85.png)

**Comment by mhshakouri** [comment]
provide a live link so we can investigate what you are going through

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
