### ISSUE TITLE
Strange rewind animation when loop is active

### ISSUE THREAD

**Issue by csimpi** [nolimits4web/swiper#3213]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Newest
* Platform/Target and Browser Versions: Windows 10, Chrome newest
* Live Link or JSFiddle/Codepen or website with isssue: I can't share my local dev server

### What you did
I've tried these and these combinations:
```
{
      slidesPerView: 3,
      //spaceBetween: 30,
      //centeredSlides: true,
      autoplay: {
        delay: 2000,
        stopOnLastSlide: false,
        reverseDirection: false,
        disableOnInteraction: false
      },
      loop: true,
      loopFillGroupWithBlank: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      /*navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },*/
    },
    index:0
  }
```

### Expected Behavior
Like on the Loop example on your website.

### Actual Behavior
https://i.imgur.com/S7FKz6Q.gifv

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Btw: Forum page doesn't work getting webserver error.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by robpop** [comment]
Can you provide a JSFiddle or CodePen of the issue so that we can recreate the bug? It doesn't have to be from your dev server, just something we can test against.

**Comment by csimpi** [comment]
@robpop I couldn't really reproduce this without the project, I was just hoping maybe you have any idea what even can cause this. I've checked if I override any animations with CSS, checking every single DOM element but it should work well.
Any suggestions, ideas on how to debug this?

**Comment by Jakkkub** [comment]
I had this issue when Swiper was accidentally initialised three times instead of just once. Also, pagination was not working correctly. Once I removed multiple calls to my swiper init function, everything started to work as expected.

**Comment by Elyos59** [comment]
Hi!

I have same bug...

JSFiddle : https://jsfiddle.net/fbd7p40o/1/

Click on next (right arrow) for making one loop (when slide n°1 go back to first position) and then click on prev (left arrow).
Sometimes, swiper go back 3 slides before (slide n°8 at first position) instead of go back of 1 slide (slide n°10 should be at first position)

Sometimes it works fine... sometimes not...
If you don't see the bug, refresh page and retry again and again...

If someone have an idea for this...

**Comment by Elyos59** [comment]
Hi!

I have same bug...

JSFiddle : [https://jsfiddle.net/bg4dejv2/](url)

Click on next (right arrow) for making one loop (when slide n°1 go back to first position) and then click on prev (left arrow).
Sometimes, swiper go back 3 slides before (slide n°8 at first position) instead of go back of 1 slide (slide n°10 should be at first position)

Sometimes it works fine... sometimes not...
If you don't see the bug, refresh page and retry again and again...

If someone have an idea for this...

**Comment by Elyos59** [comment]
Hi!

I have same bug...

JSFiddle : [https://jsfiddle.net/bg4dejv2/](https://jsfiddle.net/bg4dejv2/)

Click on next (right arrow) for making one loop (when slide n°1 go back to first position) and then click on prev (left arrow).
Sometimes, swiper go back 3 slides before (slide n°8 at first position) instead of go back of 1 slide (slide n°10 should be at first position)

Sometimes it works fine... sometimes not...
If you don't see the bug, refresh page and retry again and again...

If someone have an idea for this...

**Comment by Elyos59** [comment]
On click prev arrow
`function slideTo (index, speed, runCallbacks, internal)`
index seems to be "undefined"

**Comment by Elyos59** [comment]
On click prev arrow
`function slidePrev (speed, runCallbacks, internal) {
...
 var prevIndex;
    if (typeof prevSnap !== 'undefined') {
      prevIndex = slidesGrid.indexOf(prevSnap);
      if (prevIndex < 0) { prevIndex = swiper.activeIndex - 1; }
    }`
prevIndex seems to be "undefined"

**Comment by Elyos59** [comment]
On click prev arrow
`function slidePrev (speed, runCallbacks, internal) {`
...
`var currentSnap = snapGrid[normalizedSnapGrid.indexOf(normalizedTranslate)];`
`var prevSnap = snapGrid[normalizedSnapGrid.indexOf(normalizedTranslate) - 1];`

currentSnap => -1
prevSnap => -2

**Comment by Elyos59** [comment]
okay...
On click prev arrow after one loop
`function slidePrev (speed, runCallbacks, internal) {`
translate : 858.996666666666
normalizedTranslate :858
snapGrid :0,286.3333333333333,572.6666666666666,859,1145.3333333333333,1431.6666666666665,1717.9999999999998,2004.333333333333,2290.6666666666665,2577,2863.3333333333335,3149.666666666667,3436.0000000000005,3722.333333333334
normalizedSnapGrid :0,287,573,859,1146,1432,1718,2005,2291,2577,2864,3150,3437,3723
normalizedSlidesGrid :0,287,573,859,1146,1432,1718,2005,2291,2577,2864,3150,3437,3723,4009,4296

translate var equal 858.996666666666 and normalizedTranslate  equal 858

but in normalizedSnapGrid and normalizedSlidesGrid it's 859 not 858

so in the slidePrev function  changing
`function normalize(val) {`
`      if (val < 0) { return -Math.floor(Math.abs(val)); }`
`      return Math.floor(val);`
`    }`
by
`function normalize(val) {`
`      if (val < 0) { return -Math.floor(Math.abs(val)); }`
`      return Math.ceil(val);`
`    }`

seems to debug this...

**Comment by Elyos59** [comment]
It's not working... on my project (not JSFiddle) a second click on prev arrow after one loop reproduces the bug...

**Comment by Elyos59** [comment]
okay... depends on width... sometimes +/- 1 pixel cause the bug....

**Comment by Elyos59** [comment]
In slidePrev function changing
```
var currentSnap = snapGrid[normalizedSnapGrid.indexOf(normalizedTranslate)];
var prevSnap = snapGrid[normalizedSnapGrid.indexOf(normalizedTranslate) - 1];
```
by
```
    var currentSnap = "undefined";
    var prevSnap = "undefined";
	var cSnap = null;
	var pSnap = null;
	for(var index=0;index<normalizedSnapGrid.length;index++){
	  if (cSnap == null || Math.abs(normalizedSnapGrid[index] - normalizedTranslate) < Math.abs(cSnap - normalizedTranslate)) {
		cSnap = normalizedSnapGrid[index];
		currentSnap = snapGrid[index];
	  }
	}
	for(var index=0;index<normalizedSnapGrid.length;index++){
	  if (pSnap == null || Math.abs(normalizedSnapGrid[index] - normalizedTranslate) < Math.abs(pSnap - normalizedTranslate)) {
		pSnap = normalizedSnapGrid[index];
		prevSnap = snapGrid[index-1];
	  }
	}
```

seems to debug this...

**Comment by think2308** [comment]
setting  oundLengths: true, resolved the jump rewind for me

**Comment by tavonline** [comment]
> I had this issue when Swiper was accidentally initialised three times instead of just once. Also, pagination was not working correctly. Once I removed multiple calls to my swiper init function, everything started to work as expected.

**This solved my problem**, thanks @Jakkkub

**Comment by mehmetyavuz** [comment]
> I had this issue when Swiper was accidentally initialised three times instead of just once. Also, pagination was not working correctly. Once I removed multiple calls to my swiper init function, everything started to work as expected.

This helped me too, thanks @Jakkkub
