### ISSUE TITLE
slideThumbActiveClass not triggered on active slide when thumb options are not contains  loop: true

### ISSUE THREAD

**Issue by Korotovsky-Taras** [nolimits4web/swiper#3277]
https://github.com/nolimits4web/swiper/blob/c56d02b5fa440d0f1880b7e14ac4ecbb80c9113d/src/components/thumbs/thumbs.js#L116

```javascript
new Swiper('.swiper', {
		slidesPerView: 1,
		spaceBetween: 6,
		pagination: {
			el: '.swiper-pagination',
			type: 'bullets',
			clickable: true,
		},
		navigation: {
			prevEl: '.swiper-button-prev',
			nextEl: '.swiper-button-next',
		},
		thumbs: {
			swiper: {
				el: '.swiper-thumbs',
				slidesPerView: 5,
				spaceBetween: 12,
				direction: 'vertical',
				navigation: {
					nextEl: '.swiper-button-next',
				},
			}
		}
	})
```

works only with

```javascript
new Swiper('.swiper', {
		slidesPerView: 1,
                 loop: true,
		spaceBetween: 6,
		pagination: {
			el: '.swiper-pagination',
			type: 'bullets',
			clickable: true,
		},
		navigation: {
			prevEl: '.swiper-button-prev',
			nextEl: '.swiper-button-next',
		},
		thumbs: {
			swiper: {
				el: '.swiper-thumbs',
				slidesPerView: 5,
				spaceBetween: 12,
                                 loop: true,
				direction: 'vertical',
				navigation: {
					nextEl: '.swiper-button-next',
				},
			}
		}
	})
```

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by julien-gargot** [comment]
I’ll try:
- Using thumb gallery like in [example](https://swiperjs.com/demos/300-thumbs-gallery.html), if you do not set the param `loop: true` on the galleryThumbs, it does not set or trigger the `slideThumbActiveClass`.
- https://codepen.io/752ar/pen/GRROmBx
