### ISSUE TITLE
coverflow effect not work correctly 

### ISSUE THREAD

**Issue by realrecordzLab** [nolimits4web/swiper#3337]
I have a swiper instance inside my wordpress menù that use the coverflow effect. The menù will open sliding from left to right and will place the swiper on the right column of it, this is the expected layout, but I've noticed that the coverflow effect will not work until I change the height of the browser window, an example is when I attach the chrome console under the window. I'm not sure if the swiper is initialized correctly before the menù open or if this issue is because the swiper will load after the menù is opened. Is there any fix? PS: I've used the code provided into the example of the coverflow demo code

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
