### ISSUE TITLE
`M-o` on `M-x counsel-M-x` does show hydra visual aids anymore

### ISSUE THREAD

**Issue by mrbig033** [nolimits4web/swiper#3381]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### My Environment

- **OS**: MX Linux 19
- **$ uname -r**: 4.19.0-6-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- **i3wm** version 4.16.1 
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- **GNU Emacs** 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-12-23
- [~/.emacs.d](https://github.com/mrbig033/emacs02)
- [ivy use-package declarations](https://github.com/mrbig033/emacs02/blob/master/init.org#ivy) (already tested without those)
- **ivy** 20191217.1242
- **counsel** 20191219.1246
- **swiper** 20191128.1126
- **ivy-hydra** 20191018.1251

### What you did
On `M-x counsel-M-x`, hit `M-o` for extra actions. 

### Expected Behavior
The visual aids should show.

### Actual Behavior
`M-o` does not bring the hydra with the possible options anymore. Instead, the minibuffer is flattened to a single line. The commands I remember still work, but there are no visual aids. 

It looks like this:
![screenshot](https://user-images.githubusercontent.com/36245777/71433869-53d0f180-26c0-11ea-89bc-5d4701f0ee8e.png)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by mrbig033** [comment]
I don't follow. Could you please inform me exactly what is missing from my issue? I seem to have done everything, except this: `Provide live link or JSFiddle/Codepen or website with isssue`, but I'm not sure exactly what you mean by that. AFAIK, the word `issue` refers to [this very post](https://github.com/nolimits4web/swiper/issues/3381). What should I put on JSFiddle/Codepen?

The contribution guideline you linked makes no mention of JSFiddle/Codepen.

Please forgive my ignorance.
