### ISSUE TITLE
slideTo(0) sliding to slider index 1

### ISSUE THREAD

**Issue by keerthanaswarnakumar** [nolimits4web/swiper#3584]
Recently,  have updated swiper version from 3.3.1 to 5.3.7.

I have a functionality, where after the last slide it should jump to the initial slide i.e sliderindex = 0. It was working fine in the older version but after updating the version, when we try to click from the last slide it is skipping the first slide(sliderindex = 0) and moving to second slide(sliderindex = 1).  

When I try to analyze the html element, a class "swiper-slide-prev" is added to the first slide instead of "swiper-slide-active".  How can I remove the "swiper-slide-prev" class to make the slider slide properly.

Thanks in advance.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
