### ISSUE TITLE
Bad "Get started" documentation

### ISSUE THREAD

**Issue by olegKusov** [nolimits4web/swiper#3597]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.1
* Platform/Target and Browser Versions: Windows 10, Chrome 83

It's really big trouble for library if after 15 minutes I can't understand how to work with it. "Get started" documentation doesn't explain what classes must be in my HTML Layout and what classes not nessesary. 
Here is official explanation.
![image](https://user-images.githubusercontent.com/28058268/83045356-2365f880-a04e-11ea-8b31-cf97cdb09c11.png)

Do you really think that a common person can understand what classes required? After 15 minutes I can't make my custom slider start working and it's horrible.

**Comment by olegKusov** [comment]
Is swiper-container requeired? Or maybe swiper-slide is required? Why you can't explain this to all new users. You can make amazing products but without normal explanation it's "work in the void"

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
