### ISSUE TITLE
Here is a solution ： About white flashes on borders when slides changes (real iPad/iPhone)

### ISSUE THREAD

**Issue by CalmDownJ** [nolimits4web/swiper#3641]
https://www.cnblogs.com/zhengyan/p/4719613.html

refer to the above, add css code like as shown below
.swiper-slide{
  -webkit-backface-visibility: hidden;
  -webkit-transform: translate3d(0,0,0);
}
.swiper-wrapper{
  -webkit-transform-style: preserve-3d;
}

**Comment by frontendhomie** [comment]
thank you!

**Comment by vltansky** [comment]
@frontendhomie can you make a screenshot how the bug looks like?
Maybe this should be added to swipers styles by default?

**Comment by frontendhomie** [comment]
of course, i made a video:


https://user-images.githubusercontent.com/20923682/106584994-243d1b80-6547-11eb-8541-9f70d00453e7.mov

**Comment by vltansky** [comment]
thanks!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
