### ISSUE TITLE
6.0.0 ssr mode，server render first SwiperSlide show diff with client render

### ISSUE THREAD

**Issue by su6838354** [nolimits4web/swiper#3656]
6.0.0 ssr mode，server render first SwiperSlide show diff with client render

**Comment by su6838354** [comment]
TS2339: Property 'realIndex' does not exist on type 'Swiper'.  onSlideChange

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by jodietz** [comment]
Same problem here with loop mode. The swiper on SSR shows the duplicated slides first. On SSR there is no css class `swiper-slide-active`. 

I solved this by using css `transform: translateX(???)` at the class `swiper-wrapper`. On the client the translation is overridden by the correct initialized swiper. You have to compute the ??? depending on view size, slides per view and the number of duplicated slides.
And yes this is only a workaround.

I use swiper/react with version 6.1.2.

**Comment by theskillwithin** [comment]
I am experiencing this as well
