### ISSUE TITLE
Swiper 6 - rename files - Anyway to keep the old path of the cdn `https://unpkg.com/swiper/swiper.min.js` (To swiper 5.X)?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [nolimits4web/swiper#3664]
The last update will `break` a lot of sites and codepens/jfiddle and so on (Endless projects) that used the old CDN.

I know its better to declare a specific CDN version to avoid issues like this (But in real-time its easier to copy-paste paths from the docs).

**Comment by Ezra-Siton-UIX** [comment]
??

**Comment by nolimits4web** [comment]
It is a major release assuming breaking changes, according to your (and many who writes the same) logic, Swiper can’t contain any breaking changes in future because you included generic CDN link - which doesn’t make any sense. If you use CDN you should know how, why to use it and what are the downsides. It will not be changed back!
