### ISSUE TITLE
Active slide class

### ISSUE THREAD

**Issue by ArthurShlain** [nolimits4web/swiper#3696]
When total slides count less than `slidesPerView` value (or equal):
- Can't change active slide by click on slide;
- Can't change active slide by navigation buttons (prev, next);
- First slide always active.

options: `{
        direction: 'horizontal',
        loop: false,
        slidesPerView: 3,
        slideToClickedSlide: true
}`

Swiper version is 6.0.3

Same issue https://github.com/nolimits4web/swiper/issues/534 but it's outdated.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by ArthurShlain** [comment]
Пидарас

**Comment by ArthurShlain** [comment]
I think `normalizeSlideIndex` option https://github.com/nolimits4web/Swiper/pull/1766 is not working.
