### ISSUE TITLE
Clicking on a slide moves to next slide (sometimes previous)

### ISSUE THREAD

**Issue by dottodot** [nolimits4web/swiper#3697]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.0.3
* Platform/Target and Browser Versions: macOS, CHROME.

https://swiperjs.com/demos/110-slides-per-view.html

### What you did
The issue I'm seeing is the same as on the demo link.

### Expected Behavior
Clicking the current slide should not move to the next click, only click the next slide should have this behaviour.

### Actual Behavior
Click slide 1 and it navigates to slide 2, when you get to the middle it's then pot luck which way it goes something left sometimes right. Even before the middle it sometimes goes one way or another.

**Comment by nolimits4web** [comment]
It happens because you also do short move with click. This can be configured via params

**Comment by dottodot** [comment]
I see thanks, just anyone else that comes across this.

```
shortSwipes: false
```

**Comment by haotan19** [comment]
I have a similar issue but I use `slidesPerGroup` instead of `shortSwipes` like this:

```
breakpoints: {
    400: {
        slidesPerView: 2,
        slidesPerGroup: 2,
        spaceBetween: 12,
    },
...
}
```

**Comment by shoxton** [comment]
> I have a similar issue but I use slidesPerGroup instead of shortSwipes like this:

hey @haotan19 this is a workaround, but when i want different `slidesPerGroup` than `slidesPerView` the problem persists. 
I have a products slider with 4 slidesPerView, and when click next/button, i want to jump only one slide (`slidesPerGroup: 1`). 

But doing this way, the problem with clicking shows up. On mac/android you cannot click slides with links because it jumps to next slide instead of opening the link. On windows this problem happens when clicking with the mouse wheel button. 

This problem happens if you try to click in any link (except the first one on the leftmost side).
You can see this behavior here https://codesandbox.io/s/swiper-slides-per-view-forked-sbq31x?file=/index.html

How can i make this work in such way that i can have `slidesPerView` and `slidesPerGroup` with different values?

**Comment by shoxton** [comment]
> > I have a similar issue but I use slidesPerGroup instead of shortSwipes like this:
> 
> hey @haotan19 this is a workaround, but when i want different `slidesPerGroup` than `slidesPerView` the problem persists. I have a products slider with 4 slidesPerView, and when click next/button, i want to jump only one slide (`slidesPerGroup: 1`).
> 
> But doing this way, the problem with clicking shows up. On mac/android you cannot click slides with links because it jumps to next slide instead of opening the link. On windows this problem happens when clicking with the mouse wheel button.
> 
> This problem happens if you try to click in any link (except the first one on the leftmost side). You can see this behavior here https://codesandbox.io/s/swiper-slides-per-view-forked-sbq31x?file=/index.html
> 
> How can i make this work in such way that i can have `slidesPerView` and `slidesPerGroup` with different values?

Fixed with [`{ watchSlidesProgress: true }`](https://swiperjs.com/swiper-api#param-watchSlidesProgress)

**Comment by Tashijutt** [comment]
When we click on any link or button, the swiper slide of that button gets active and we see it sliding.  To prevent this , there is an attribute 'a11y', set to false as:

`  {
   slidesPerView: 'auto',
    spaceBetween: 25,
    a11y: false,
}`

**Comment by tiagopedrotpc** [comment]
I am facing this problem, unfortunately none of the above alternatives solved it, I noticed that the slide changes position every time there is a click where the "a" tag has the target="_blank" attribute, I don't know what else to do to solve this problem. I need a new tab to open after the click.

Problem

Slide changes position when clicked

`   var swiper = new Swiper(".swiper-biblioteca", {
        slidesPerView: 1,
        spaceBetween: 10,
        autoHeight: false,
        pagination: false,
        loop:true,
        autoplay:false,
     	shortSwipes:false,
     	simulateTouch:false,
     	a11y:false,
        breakpoints: {
          320: {
           slidesPerView: 2,
           spaceBetween: 10,
           a11y: false,
    	  },
          768: {
            slidesPerView: 6,
            spaceBetween: 10,
            a11y: false,
          },
          1024: {
            slidesPerView: 6,
            spaceBetween: 10,
            a11y: false,
          },
         
        },
        pagination: {
    	  el: '.swiper-pagination',
    	  type: 'bullets',
  		},
        navigation: {
          nextEl: ".btn-biblioteca-next",
          prevEl: ".btn-biblioteca-prev",
        }
      });`

**Comment by JackEdwardLyons** [comment]
Unfortunately, `shortSwipes` doesn't seem like the solution, it's just a workaround. In my case, I want to keep `shortSwipes` as `true` because it's useful. But I have links inside slides and I want them to be clickable.

Not sure what the actual solution is here? Some setting to disable sliders default behaviour (to switch slides) when a slide is clicked?

**Comment by JackEdwardLyons** [comment]
> When we click on any link or button, the swiper slide of that button gets active and we see it sliding. To prevent this , there is an attribute 'a11y', set to false as:
> 
> ` { slidesPerView: 'auto', spaceBetween: 25, a11y: false, }`

Yep, I can confirm that setting `a11y` to `false` works!

**Comment by tiagopedrotpc** [comment]
@nicoschuck , @JackEdwardLyons 

I have applied the solutions reported, and the problem only persists in Google Chrome mobile browser, I have tested in other browsers and it works perfectly.

Behavior in Google Chrome mobile.

When clicking on a slide item it jumps to another slide for a few seconds, (opens a new tab, which is the expected behavior) and then returns to the clicked slide.

**Comment by shoxton** [comment]
None of the above worked for me.

The only thing that solved me problem was settings `watchSlidesProgress: true`
Dont ask me why, it just worked.

Heres the docs about this property

> Enable this feature to calculate each slides progress and visibility (slides in viewport will have additional visible class)

**Comment by joshbernal** [comment]
None of these solutions worked for me, but I found something that did:

noSwipingSelector: 'a',

Makes it so swiping is disabled on links, which makes links inside slides clickable again.

**Comment by gmiz** [comment]
> I'm facing the same issue.
> 
> This works for me: `shortSwipes: false`
> 
> But now it is not really user-friendly. Isn't to provide a default value to short - and/or long swipes? For example:
> 
> `shortSwipes: 20`
> 
> which means that you have to move at least 20% for slide.

@nolimits4web I think this is very important.

I'm having the same issue where `shortSwipes: false` is the way to go, but since I have a vertical swiper with videos taking up the entire screen, the required swiping is very long and makes for a terrible experience. So it would be perfect if there was a parameter to make this configurable. Maybe something like:

`shortSwipeThreshold: 30` which would require 30% of the current slide to be moved before it can go to the next one.

The current behavior feels like my imaginary `shortSwipeThreshold` is set to 50%, which in my case is way too much, especially since I only wanted to get rid of those tiny mouse movements that would cause the swiper to slide straight away. And since every slide in my case is a video, people are going to click on them all the time, so not using `shortSwipes: false` makes things hard.

I hope something like this can be a part of Swiper in the future :)

**Comment by omidsakhi** [comment]
I also confirm setting a11y to false works for me!
