### ISSUE TITLE
Navigation broke after update to 6.0.4

### ISSUE THREAD

**Issue by DennisPrins** [nolimits4web/swiper#3703]
The custom navigation broke after update to 6.0.4

` navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },`

Please fix this.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
