### ISSUE TITLE
facing issue when used custom pagination

### ISSUE THREAD

**Issue by vishnu283** [nolimits4web/swiper#3706]
when i'm switching through custom pagination, i'm facing issue the following issue. I'm using swiper v4.4.1.  Can you guys help me with this. Thanks
![Swiper throowing touchcallback error](https://user-images.githubusercontent.com/39527020/87706991-07d1c100-c766-11ea-8549-18bcff861002.PNG)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
