### ISSUE TITLE
Swiper not change slides in vue.js chrome extension app

### ISSUE THREAD

**Issue by realrecordzLab** [nolimits4web/swiper#3712]
I'm using swiper inside a vue instance. My slides are a rendered list of some text elements rendered using a v-for loop. What is happening is that If I click on the next or prev buttons the slides will not change. My Swiper instance is in the mounted() function of vue lifecycle because the slider is a part of the first part of my app that is rendered. Is there any fix for this?Anyoe had a similar issue?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
