### ISSUE TITLE
dynamicBullets is not refreshing correctly on breakpoint

### ISSUE THREAD

**Issue by smartfox87** [nolimits4web/swiper#3727]
* [x] bug

Swiper 5.3.8
Swiper 6.0.4

samle codepen
https://codepen.io/smartfox87/pen/yLewmJK

Video Sample
https://take.ms/2Qv3f

Windows 10 Google Chrome last version

**Comment by smartfox87** [comment]
I found a solution

breakpoints: {
	320: {
		slidesPerView: 1,
		slidesPerGroup: 1,
		pagination: {
			dynamicBullets: true,
			dynamicMainBullets: 7,
		},
	},
	430: {
		slidesPerView: 2,
		slidesPerGroup: 2,
		pagination: {
			dynamicBullets: false,
		},
	},
},
on: {
	breakpoint: function (swiper) {
		if (swiper.params.pagination.dynamicBullets) {
			swiper.pagination.init()
		} else {
			setTimeout(function () {
				swiper.pagination.el.style.width = '100%'
				swiper.pagination.el.classList.remove('swiper-pagination-bullets-dynamic')
			})
		}
	},
}

**Comment by warudin** [comment]
This problem doesn't seem to be restricted to dynamicBullets but also normal pagination. The number of bullets doesn't change when the number of slidesPerView & slidesPerGroup changes according to a breakpoint.

**Comment by mutoo** [comment]
I have the same issue on v6.4.10

**Comment by ChillerPerser** [comment]
Same problem here.
I need to call swiper.pagination.update() after a resize because the size and position of the pagination is not calculated again.

**Comment by mafudelaptu** [comment]
Same Issue in Swiper 8.0.6

pagination properties dont change on resize, only on reload

**Comment by andreistez** [comment]
Swiper 8.4.6, pagination bullets count is not updating on resize.

**Comment by tmmtech** [comment]
The issue is still present in Swiper 9 and 10. Example https://codesandbox.io/s/swiper-responsive-breakpoints-forked-swhpdq
Make sure the preview shows 3 slides and refresh the preview if needed. 
[example.txt](https://github.com/nolimits4web/swiper/files/12573916/example.txt)

Then it shows 5 bullets instead of 3

**Comment by IgnisVulpe** [comment]
I am have similar issue in swiper 10.2.0: breakpoints with pagination don`t work. I can`t disable dynamic bullets on breakpoint, if i resize screen. Only work after full SPA page reloading.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
