### ISSUE TITLE
LazyLoad displays a broken image icon when has alt text

### ISSUE THREAD

**Issue by retroriff** [nolimits4web/swiper#3747]
Using Chrome, when using LazyLoad on a gallery with alt text, images show a broken image icon before being loaded. When the alt text is empty, the broken image icon is not shown.

**Comment by ygj6** [comment]
@retroriff Could you provide the test code with bugs?

**Comment by theCSSguru** [comment]
This is Chrome reporting a 'broken image' because there's no src="" value thusly resulting in showing the default Alt Tag. 

I've gotten around this by adding in a transparent png src="1x1.png" so it makes chrome happy with an alt tag, but, and there's always a but...If you use something like 'Fancybox' with it, it might try to snag the src instead of the data-src, so there's still some investigating I need to do, I'll report back once I figure something out.

**Comment by theCSSguru** [comment]
Follow up - Fancybox is grabbing the currentSrc of the image tag for the Thumbnails, and since Swiper is Lazy Loading the first two (for my current set up) the images after that are all grabbing the src="1x1.png" because the image hasn't been loaded in yet.

Might be more of Fancybox thing then at this point, but yeah, if you don't need Fanxybox, then the 1x1.png is a neat solution for now.

**Comment by bringher** [comment]
Hi I resolved this problem using pure css:

.swiper-lazy:not(.swiper-lazy-loaded) {
    display: none;
}

so if the element is not loaded nothing is shown ... tested on chrome 83
