### ISSUE TITLE
Ugly horizontal overscroll bounce

### ISSUE THREAD

**Issue by fdgfdgdg** [nolimits4web/swiper#3791]
Hi thanks for this kit just wondering if there is anyway to disable the horizontal overscroll bounce. Found in your demo too. I don't see any option from your documentation. 

Building an app with cordova for ios 10+.

![image](https://user-images.githubusercontent.com/69398149/91783189-44168f00-ebf7-11ea-9695-8e96386e3fab.jpeg)

![image](https://user-images.githubusercontent.com/69398149/91783342-d323a700-ebf7-11ea-82b5-609b06fad357.jpeg)

Kind regards

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by gdfbhjghdfjkhgdfjk** [comment]
fuck you, I gave very clear example, it's happening even in your demo so whatever version you are using there.

I do not need to provide live link retard. Stupid bitch i see how you are very condescending to others, I will just build my swiper.
