### ISSUE TITLE
render function or template not defined in component: Swiper in nuxt.js

### ISSUE THREAD

**Issue by stunnitysoft** [nolimits4web/swiper#3861]
Hello I am using `swiper `in `nuxt.js` I tried to make some codes as I saw them in their documentation 

**my codes**

```
<template>
  <swiper
    :slides-per-view="3"
    :space-between="50"
    navigation
    :pagination="{ clickable: true }"
    :scrollbar="{ draggable: true }"
    @swiper="onSwiper"
    @slideChange="onSlideChange"
  >
    <swiper-slide>Slide 1</swiper-slide>
    <swiper-slide>Slide 2</swiper-slide>
    <swiper-slide>Slide 3</swiper-slide>
    ...
  </swiper>
</template>
<script>
// import Swiper core and required components
import SwiperCore, { Navigation, Pagination, Scrollbar, A11y } from 'swiper';

// Import Swiper Vue.js components
import { Swiper, SwiperSlide } from 'swiper/vue';

// Import Swiper styles
import 'swiper/swiper.scss';
import 'swiper/components/navigation/navigation.scss';
import 'swiper/components/pagination/pagination.scss';
import 'swiper/components/scrollbar/scrollbar.scss';

// install Swiper components
SwiperCore.use([Navigation, Pagination, Scrollbar, A11y]);

// Import Swiper styles
export default {
  components: {
    Swiper,
    SwiperSlide,
  },
  methods: {
    onSwiper(swiper) {
      console.log(swiper)
    },
    onSlideChange() {
      console.log('slide change')
    },
  },
};
</script>
```

**error in browser**

![image](https://user-images.githubusercontent.com/59558329/95452221-35936400-0969-11eb-87ab-aa033e51b369.png)

**warnings in terminal console**

![image](https://user-images.githubusercontent.com/59558329/95452289-52c83280-0969-11eb-9ee4-f1028713929c.png)

**my `package.json`**

![image](https://user-images.githubusercontent.com/59558329/95452349-68d5f300-0969-11eb-8d71-0c66f4535ba1.png)

**Comment by nolimits4web** [comment]
https://swiperjs.com/vue/

> Swiper Vue.js components are compatible only with new Vue.js version 3

**Comment by ntwaricliberi** [comment]
> https://swiperjs.com/vue/
> 
> > Swiper Vue.js components are compatible only with new Vue.js version 3

Hey i already used those codes thats why u am getting the issue, so why are you redirecting me where i have already met bug at

**Comment by mrleblanc101** [comment]
Nuxt use Vue 2, not Vue 3

**Comment by kissu** [comment]
Nuxt2 uses Vue2, Nuxt3 uses Vue3.

**Comment by mrleblanc101** [comment]
Nuxt 3 wasn't even in alpha a year ago when I posted this message 🙃

**Comment by kissu** [comment]
@mrleblanc101 I know. It is still relevant to keep people updated on today's latest releases/capabilities/incompatibilities. ✅ 

I'm not posting that to be rude, but rather as something informative. Today, somebody emailed me personally regarding their difficulties to have a working setup: https://stackoverflow.com/q/74684583/8816585

My answers on Swiper also have around 5k views overall, so I guess that people may still be interested when searching for more info [around here](https://github.com/nolimits4web/swiper/issues?q=is%3Aissue+nuxt) in the upcoming months/years.
I'm mainly keeping the materials updated so people don't lose too much time trying to set up that in their projects.

Especially since I'm not sure that [this part](https://github.com/nolimits4web/swiper/issues/3861#issuecomment-705667062) is still written somewhere. After a quick glance, I couldn't say quickly for sure if the v8 was a Vue3-only thing or not, needed to look around a bit more.

Making that one more simple for newcomers is always a nice thing IMO. 🙌🏻
