### ISSUE TITLE
Support for Vue 2

### ISSUE THREAD

**Issue by simplenotezy** [nolimits4web/swiper#3900]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Swiper should be compatible with Vue 2. Many of us who use Nuxt (SSR for Vue) don't support Vue 3 yet, so there's still quite a large audience for Vue 2.

**Comment by nolimits4web** [comment]
Vue 3 and Vue 2 are not compatible with each other. To much efforts to maintain one more version for Vue 2

**Comment by mrleblanc101** [comment]
@nolimits4web Where can I find the API documentation for Swiper 5 since it's the latest version compatible with Nuxt ?
For exemple, the `slideChange` event does not have `swiper` as first parameter in that version.
I think the documentation website should be versioned so developper can refer to older API version.

**Comment by nolimits4web** [comment]
there is no official swiper-vue components prior to v6

**Comment by mrleblanc101** [comment]
I'm not talking about the vue component. I'm talking about the API. Vue-awesome-swiper require Swiper 5, but when I refer to the Swiper doc, I can only see the v6 API which is different.

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/blob/Swiper5/API.md

**Comment by mrleblanc101** [comment]
Ok, I understand that there is no way to view the v5 API on the documentation website ? Most project have a drop down where you can switch between version (Vue for example)
