### ISSUE TITLE
Reflow when using slidesPerView with more than 1

### ISSUE THREAD

**Issue by 91DarioDev** [nolimits4web/swiper#3911]
Using the parameter slidesPerView with more than 1 it reflows because for the first fraction of seconds it only append 1 image and then other images are added creating a reflow of the page

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
