### ISSUE TITLE
在切换效果为渐变时，多个slide下滚动条无法滚动

### ISSUE THREAD

**Issue by click33** [nolimits4web/swiper#3935]
在切换效果为渐变的时候，如果第二个slide有滚动条的时候，第一个slide的滚动将失效
通过调试发现，渐变效果下，用了 pointer-events: none  属性  
这个属性可以穿透点击事件，但是无法穿透滑动滚动条事件  当我在第一个slide滚动的时候，实际上滚动的还是第二个slide就好像第一个slide的滚动条失效了
这个有解决方案吗？
具体复现案例是在一个后台模板中：https://github.com/click33/sa-admin
此模板集成了swiper做页面切换效果，遇到了这个bug

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by click33** [comment]
我已经完成了三点:  
清楚的描述出了问题所在及其背后原因
已知最新版仍存在这个问题
我已经留下了复现代码链接
为什么要关闭我的问题呢？仅仅是因为我用的中文来描述问题吗？
