### ISSUE TITLE
centeredSlide has no effect.

### ISSUE THREAD

**Issue by wibed** [nolimits4web/swiper#4018]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.5
* Platform/Target and Browser Versions: any
* Live Link or JSFiddle/Codepen or website with isssue: https://codesandbox.io/s/mystifying-visvesvaraya-3z5xw?file=/src/styles.css

### What you did
followed first example on https://youtube.com/watch?v=l4kFO6VQPfA
added `slidesCentered: true`.

### Expected Behavior
slides to center

### Actual Behavior
slides don't centre, after adding `margin: auto` for img, as seen in `style.css`
the slides do center (or at least images). if this is expected there is no entry in the 
documentation, that hints to such behaviour.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper)
for that.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by vltansky** [comment]
If you want to center slide content use CSS as you did.
`slidesCentered: true` centering the `.swiper-slide` in the carousel, not the content inside it.
https://swiperjs.com/api/
> If true, then active slide will be centered, not always on the left side

You need to use slidesPerView in order to see the effect of slidesCentered.
See the difference between the two demos:
https://swiperjs.com/demos/#multiple_slides_per_view
https://swiperjs.com/demos/#centered_slides

**Comment by wibed** [comment]
there may has been a misunderstanding.
thanks for clarification

**Comment by wibed** [comment]
adding 

```css
.swiper-slide {
  width: 500px !important
}
```
illustrates the misunderstanding better. as slides tend to take up 100% of the width, combined with transparency giving the impression to not be centered.
