### ISSUE TITLE
Pagination in version 6.4.9 does not display, and has node elements, but the style sheet does not work

### ISSUE THREAD

**Issue by Ken-Zhao** [nolimits4web/swiper#4163]
- Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
- Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

## What You Did

EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

 https://codesandbox.io/...

## Expected Behavior

EXPLAIN WHAT IS TO BE EXPECTED, HERE.

## Actual Behavior

EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
