### ISSUE TITLE
centeredSlides: true not working on first load

### ISSUE THREAD

**Issue by Cuboctaedro** [nolimits4web/swiper#4165]
- Swiper Version: 6.4.5
- Platform/Target and Browser Versions: Windows, Chrome and Firefox, not Edge

## What You Did
I am using the react version like this:
```
    <Swiper
        spaceBetween={16}
        slidesPerView="auto"
        pagination={{ clickable: true, el: '.slider-control' }}
        centeredSlides={true}
        grabCursor={true}
        freeMode={false}
    >
// slide
</Swiper>
```

You can see it live here: https://www.elameteoratrikala.com/

## Expected Behavior

I have set centeredSlides to true.

## Actual Behavior

When the page loads for the first time (and only then) centeredSlides={true} does not work and the slides are flushed left.
On subsequent page loads centeredSlides={true} works as expected.

**Comment by nolimits4web** [comment]
Please provide an isolated code example (JSFiddle, CodePen, StackBlitz)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by ArcherGu** [comment]
Same problem, I just find when first load, the slider's clientWidth is different with when reload the page. So when I first load, the center offset is not right.

**Comment by Nintex** [comment]
Issue seems to occur when the CSS isn't fully loaded and the Swiper function is called.
I wrapped my Swiper function into a setTimeout function as a workaround and that did the trick.

**Comment by algspd** [comment]
Same here, and nothing to do with the css load. If I call the initializing function manually and "centeredSlides=true", the slides are flushed left.
