### ISSUE TITLE
Carousel items getting blurry after clicking prev/next arrow (Has demo)

### ISSUE THREAD

**Issue by KongCheeHong** [nolimits4web/swiper#4166]
- Swiper Version: 6.4.9 (latest)
- Platform: Mac OS Catelina Version 10.15.6 (19G2021)
- Browser Versions: Goole Chrome Version 88.0.4324.96 (Official Build) (x86_64)

I'm facing an issue which the carousel item are getting blurry after clicking prev/next arrows. It happened where the carousel items are more than 100++, it will getting more blurry if your items are more and more.

Example/Demo: https://codepen.io/kchkch/pen/OJbJbem

**Comment by andrea3aga** [comment]
Me too.
As you add new images to the carousel, the transition becomes increasingly blurred.

**Comment by opiepj** [comment]
Same issue with me.  Seems to only be happening on Chrome. I used "roundLengths", but doesn't work.

**Comment by opiepj** [comment]
I was able to remove the problem by adding this hack to my global styles.

```css
.swiper-slide {
  -webkit-backface-visibility: hidden;
}
```

Lame :/

**Comment by akhatri** [comment]
@opiepj i had the same issue and your fix worked! Could we please get this fixed in the main version as it looks like a common issue. I had this issue with the swiper-react version too

**Comment by saiichihashimoto** [comment]
👍 on the issue, 👍 on @opiepj, 😢 on @nolimits4web closing the PR without a good alternative.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
