### ISSUE TITLE
initialSlide: 0 when pagesPerView != "auto" selects the wrong slide

### ISSUE THREAD

**Issue by mmcossu** [nolimits4web/swiper#4246]
Hi,
you probably have an issue that involves the options: 

  - **initialSlide**: when 0
  - **slidesPerView**: when not set to 'auto'

Infact, if you take any of your demos and set for example:

`<script>
    var swiper = new Swiper('.swiper-container', {
      initialSlide: 0,
      slidesPerView: 3,
      spaceBetween: 30,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
    });
  </script>`

you can see that the element that gets selected is the second in the list, (Slide 2) and you cannot navigate to index 0 (Slide 1).

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by nolimits4web** [comment]
According to your description everything works https://stackblitz.com/edit/tyckxa?file=index.html
Don't need to ignore issue templates
