### ISSUE TITLE
Arrow becomes disabled one slide too early

### ISSUE THREAD

**Issue by glassesUSA** [nolimits4web/swiper#4256]
- Swiper Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
- Platform/Target and Browser Versions: PLATFORM CLIENT YOU ARE TARGETING SUCH AS macOS, Windows, CORDOVA, IOS, ANDROID, CHROME, ETC.

## What You Did

```js
let swiper = new Swiper('.dsmTrustpilot .swiper-container', {
  navigation: {
    nextEl: '#swiperRightArrow',
    prevEl: '#swiperLeftArrow',
  },
  loop: false,
  slidesPerView: 3,
  spaceBetween: 20,
  pagination: {
    el: '.swiper-pagination',
    type: 'bullets',
    clickable: true,
  },
  breakpoints: {
    1024: {
      allowTouchMove: allowTouchMove,
    },
    736: {
      slidesPerView: 2,
    },
    320: {
      allowTouchMove: true,
      slidesPerView: 1,
    },
  },
})
```

## Expected Behavior

At the second last slide the arrow is not disabled

## Actual Behavior

The arrow is disabled on the second last slide

**Comment by nolimits4web** [comment]
Would be good to see live demo on codepen, codesandbox, etc.

**Comment by glassesUSA** [comment]
Hi,

Found this was an issue on my end.

**Comment by adamtomorrow** [comment]
> 

HI @glassesUSA - what was the problem on your end? I'm having this exact same issue.

**Comment by glassesUSA** [comment]
IIRC I was calling swiper twice but this was so long ago that I don't remember

**Comment by brabli** [comment]
I had something similar happen where the "next slide" button was being disabled too early.

It turned out I had another Swiper element further down the page, and both were being affected by each other’s navigation buttons. This meant that when one slider reached the end of its slides, it disabled the "next" button for both sliders, regardless of how far through its slides the other one was.

The solution was to make sure both Swiper instances were using different navigation elements, for example:

```js
// slider-one.js
navigation: {
    nextEl: '.slider-one-next',
},

// slider-two.js
navigation: {
    nextEl: '.slider-two-next',
},
