### ISSUE TITLE
DIsable swiping next prev slide when swiper is zoomed

### ISSUE THREAD

**Issue by Venegrad** [nolimits4web/swiper#4280]
If swiper slide is zoomed, i need to disable prev next slide swiping, cuz thats unreal to use zoom. U try to zoom, but swiper go to next slide. How to disable swiping next prev when swiper is zooming?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
