### ISSUE TITLE
prop param "init:false" passed to <Swiper> component  not working

### ISSUE THREAD

**Issue by EmilioAsteben** [nolimits4web/swiper#4295]
`init:false` works well in sandbox demos, but i can not to use it within CRA project

React tools shows that prop param has accepted successfully, but initialization is still not prevented 

   

```
    <Swiper
      spaceBetween={50}
      slidesPerView={3}
      init={false}
    >
      <SwiperSlide>Slide 1</SwiperSlide>
      <SwiperSlide>Slide 2</SwiperSlide>
      <SwiperSlide>Slide 3</SwiperSlide>
      <SwiperSlide>Slide 4</SwiperSlide>
      ...
    </Swiper>
```

**Comment by nolimits4web** [comment]
Sorry, but it is not supported in components, why you need Swiper in React if you don't want to init it? Then you can just use plain HTML  Swiper layout

**Comment by EmilioAsteben** [comment]
> 
> 
> Sorry, but it is not supported in components, why you need Swiper in React if you don't want to init it? Then you can just use plain HTML Swiper layout

I would like to initialize the swiper depending on the screen width, to response interface.
 Then I will use other solutions, thanks for the feedback.

**Comment by minlare** [comment]
Please could the documentation be updated to explain this? I also wondered why I couldn't disable init in react.

**Comment by gianpesto** [comment]
I also happened upon scenarios in reactive frameworks where i needed to add Modules like Pagination or Next/Prev Buttons to the slider. But as i reused the component multiple times on the same page, i could not rely on the class, so the following params would not work:

```
const swiperConfig = {
  pagination: {
    el: ".swiper-pagination",
    type: "bullets",
  }
};
```

that's why i would set `init: false` and then pass the reference to the pagination element after the component had been mounted and then init the slider:

```
<Swiper>
    <SwiperSlide>
    ....
    </SwiperSlide>
</Swiper>

<div ref="pagination"></div>
```

```
swiper.params.pagination.el = this.$refs.pagination;
swiper.init()
```
