### ISSUE TITLE
Swiper mousewheel not playing nice when effect fade is active

### ISSUE THREAD

**Issue by kevinmu17** [nolimits4web/swiper#4303]
- Swiper Version: 6.4.15
- Platform/Target and Browser Versions: macOS 11.2.2 - CHROME 89.0.4389.72

## What You Did
```
import Swiper, { Navigation, Pagination, Scrollbar, EffectFade, Mousewheel } from 'swiper/core';
Swiper.use([Navigation, Pagination, Scrollbar, EffectFade, Mousewheel]);

const swiper = new Swiper('#js-swiper', {
    slidesPerView: 1,
    effect: 'fade',
    fadeEffect: {
        crossFade: true
    },
    mousewheel: {
        releaseOnEdges: true,
    },
});
```

https://stackblitz.com/edit/swiper-demo-1-default-mwkvgn?file=index.html

## Expected Behavior
Strangly enough in the stackblitz it is working like I would expect it to. But my above code is not, am i missing something here or is the bundling going wrong somewhere?

## Actual Behavior
Slides to slide 2 and then hangs, not possible to get back to slide 1 or 3. Feels like it's frozen.

**Comment by sonjastrieder** [comment]
I had exactly the same issue. I'm importing only the core Swiper styles, adding modules as needed. Turns out I had forgotten to import the stylesheet that's required by the Fade Effect module 🤷🏻‍♀️. Worked just fine after importing it.
`components/effect-fade/effect-fade.min.css`

Full list of stylesheets that are required by all the different Swiper modules can be found here:
https://swiperjs.com/swiper-api#styles
