### ISSUE TITLE
Hiding all signs of carousel if side count < slidesPerView. 

### ISSUE THREAD

**Issue by gkemp94** [nolimits4web/swiper#4321]
**Is your feature request related to a problem? Please describe.**
As a developer I'd love the ability to hide the existence of the carousel UNTIL the window is shrunk small enough where the carousel is required. For example, if I have two items, on a desktop they show centered next to each other, however on mobile they're two big to sit next to each other, I'd love them to be placed into a carousel. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
- Conditionally render the carousel depending on breakpoints

**Additional context**

**Comment by cb2004** [comment]
Same as this I believe just explained differently. Unfortunately the issue was closed with no discussion. Q well needed feature I think.

https://github.com/nolimits4web/swiper/issues/4311

**Comment by justinmedas** [comment]
+1 for dynamic Swiper decisions based on the above, but also in this scenario:

Setting `slidesPerView: auto` in tandem with `loop: true` will always fill the slider with duplicates. There should be 1 broad sweeping solution that looks at visible slides, or the number passed to `slidesPerView` that will trigger swiper not to init. I have implemented a JS class that hooks swiper to fill in these gaps for my use case, but its not ideal since swiper will add the duplicates, then I remove them, and update:

`/// Get the number of slides before we init Swiper
const defaultSlideCount = slider.querySelectorAll('.swiper-slide').length;

/// Init Swiper
const swiperSlider = new Swiper(slider.querySelector(slider.target), slider.sliderOpts);      

/// If the total number of slides is greater than the visible slides, we need to show navigation
if(swiperSlider.visibleSlides != undefined) {
  if(defaultSlideCount > swiperSlider.visibleSlides.length) {
    slider.classList.add("slider-has-init");
  } else {
    slider.classList.remove('slider-has-init');

    /// remove duplicates, swiper will always add duplicates with slidesPerView: auto
    slider.querySelectorAll('.swiper-slide-duplicate').forEach(duplicateSlide => {
      duplicateSlide.remove();
      swiperSlider.update();
    })
  }`

If there is some dynamic decision making based on this, there wouldn't likely need an option to destroy at certain sizes... My guess is that most use cases for this request is because some items are in a grid at large desktop/device sizes, but switch into a slider for mobile.
