### ISSUE TITLE
 Thumbs Gallery Loop not working

### ISSUE THREAD

**Issue by muhamadarsaludin** [nolimits4web/swiper#4383]
I had a probblem when using  Thumbs Gallery Loop not working, and then I checked on the swiper demo it wasn't working 

console.log mesage:

Uncaught TypeError: Cannot read property 'toString' of null
    at Object.slugify (history.js:79)
    at t.scrollToSlide (history.js:91)
    at t.init (history.js:18)
    at t.init (history.js:123)
    at events-emitter.js:95
    at Array.forEach (<anonymous>)
    at events-emitter.js:94
    at Array.forEach (<anonymous>)
    at t.emit (events-emitter.js:87)
    at t.r.init (core-class.js:499)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
