### ISSUE TITLE
slides-per-view = "auto" not working

### ISSUE THREAD

**Issue by Klylylydeee** [nolimits4web/swiper#4399]
Swiper cannot identify its child (swiper-slide class) custom width since slides-per-view is not working.

Warning message:
Property "auto" was accessed during render but is not defined on instance. 
  at <ProjectApp onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at < RouterView> 
  at < App>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
