### ISSUE TITLE
How to link two swiper slideshows?

### ISSUE THREAD

**Issue by stratboy** [nolimits4web/swiper#4412]
Hi, is there a way to link to swiper slideshows? I need to build a tabs widget where each tab click moves two sliders/slideshows. It it possible with swiper?

Thank you

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
