### ISSUE TITLE
Angular 11 - Swiper's Modules (Navigation/Pagination...) no more available in prod build ?

### ISSUE THREAD

**Issue by ecappa** [nolimits4web/swiper#4423]
- Swiper 6.5.0 / Angular 11.2.5
- Platform/Target and Browser Versions: Tested on Chrome/Ubuntu - Chrome/W10

My build prod version of my app does not show navigation and pagination anymore. - Work like a charm in dev build mode...
Didn't change anything, using ng build --prod as required....
I red about this issue : https://github.com/nolimits4web/swiper/issues/4326, but my build command did not change at all : node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --source-map

## What You Did

Worked like a charm yesterday... Did nothing, I know it is strange, but it is real...
Work great in local-dev env/build

Imported exactly as explain :
```
import {SwiperComponent} from 'swiper/angular';
import SwiperCore, {
  Navigation,
  Pagination,
  Keyboard,
  Scrollbar,
  A11y,
} from 'swiper/core';
//
// install Swiper modules
//
SwiperCore.use([Navigation, Pagination, Keyboard, Scrollbar, A11y]);
```

## Expected Behavior

Same behavior as in build dev...

## Actual Behavior

Build prod seems broken. :(

**Comment by vltansky** [comment]
@nolimits4web looks like this happens due to https://github.com/nolimits4web/swiper/commit/32092ae9544b0ba3ecc6c3b65346afa546d0547d

called from here:
https://github.com/nolimits4web/swiper/blob/master/src/angular/src/swiper.component.ts#L161

you can reproduce the issue by running `ng s --prod` in swiper repo

**Comment by ecappa** [comment]
Thanks @vltansky .
Will try to force 6.5.2 version for the moment.
Wait and see if this could be fixed.

**Comment by vltansky** [comment]
Although reverting https://github.com/nolimits4web/swiper/commit/32092ae9544b0ba3ecc6c3b65346afa546d0547d somehow did help me, but eventually, the problem was due to this commit:

https://github.com/nolimits4web/swiper/commit/f96db02f50a8067eff8241817681615b8b26b81d#diff-bfa627463b910d30122bd97c77f46167402610e987ac7922fb67145fb0104525

**Comment by ecappa** [comment]
@vltansky I had to downgrade to 6.5.0 to have it back in prod.
Not really a workaround. But thanks for putting me on the road ;)
