### ISSUE TITLE
I can't install the project.

### ISSUE THREAD

**Issue by raylyanway** [nolimits4web/swiper#4425]
`npm i` shows this.
<img width="1595" alt="Screen Shot 2021-04-09 at 00 20 57" src="https://user-images.githubusercontent.com/35544150/114099027-d9cf7680-98ca-11eb-9fb8-e473fe5c4dc8.png">

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
