### ISSUE TITLE
(Continue) Swipper "eating" the mousedown and mouseup events #4266

### ISSUE THREAD

**Issue by facundocenizo** [nolimits4web/swiper#4496]
Hello everyone, 

I'm having the same problem in this [Issue](https://github.com/nolimits4web/swiper/issues/4266) and I could't solve with 'capture'. It would be useful if I wanted to use 'pointerdown' but I want to use 'mousedown'.

I'm attaching a mousedown listener to the body. It works excellent on the others DOM elements but on the swipper elements it doesn't.

Can you help me please?

Thanks.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
