### ISSUE TITLE
When on loop mode initial slide has real index on 1 instead of 0

### ISSUE THREAD

**Issue by Saltibarsciai** [nolimits4web/swiper#4568]
Workaround:

```
if(slide.realIndex !== slide.activeIndex) {
     this.slideCounter = slide.realIndex + 1
 }
```

reproduction:

```
<swiper @slideChange="sliderChange"  :loop="true">
```

the slideChange will fire on initial load and will give realIndex 1, when it should be 0

version:

```
"swiper": "^6.5.7"
```

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
