### ISSUE TITLE
Angular - updating ngFor model after rendering the swiper does not update slides

### ISSUE THREAD

**Issue by thabisomofokeng** [nolimits4web/swiper#4593]
I am generating the first set of slides in Angular as follows:

`<ng-template swiperSlide *ngFor="let product of products">`

But if I update products array nothing happens to the slider:

```
onSlideChange(swiper) {
    if (swiper.isEnd) {
      this.productsService.find<ProductList>(page, size, '').subscribe(
        products => {
          this.products = this.products.concat(products);
          swiper.update();
      });
    }
}
````

**Comment by logan-jobzmall** [comment]
What I did to help things out:

`@ViewChild(SwiperComponent) swiper: SwiperComponent;` at the top of your component, and then call `this.swiper.slidesEl.notifyOnChanges()` after your appends

**Comment by BuffyTheCat** [comment]
Any news?

**Comment by vltansky** [comment]
Hi, this behavior is by design as all events are emitted outside of NgZone for performance reasons.
You should use `ngzone.run` or ChangeDetector.
I've added a section about this to docs & a demo
https://github.com/nolimits4web/swiper-website/pull/167
https://github.com/nolimits4web/swiper/pull/4832
