### ISSUE TITLE
vue非工程项目，异步swiper，暂停不下来

### ISSUE THREAD

**Issue by l1078228451** [nolimits4web/swiper#4597]
在vue非工程项目，watch监听异步获取的数据并对数据进行轮播，调用暂停轮播暂停不下来。

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
