### ISSUE TITLE
Index not correctly updated on swipe

### ISSUE THREAD

**Issue by linonetwo** [nolimits4web/swiper#4653]
- Swiper Version: v6.7.0
- Platform/Target and Browser Versions: MacOS Edge

## What You Did

I swipe it hard, and index is not updated. (See log), and after this hard and index not updated swipe, I slightly swipe it, then the index will update...

See this video or use stackblitz here https://stackblitz.com/edit/swiperjs-index-update-bug 

https://user-images.githubusercontent.com/3746270/120986625-5db0bc80-c7af-11eb-8382-cc6fdc10e88a.mov

## Expected Behavior

I hope I can get the correct index, no need to use any hack.

## Actual Behavior

Firstly I have to hack for `realIndex`

```js
    const {
      isBeginning,
    } = this;
    let { realIndex } = this;
    // fix a bug that index is 0 for first and second one
    if (!isBeginning) {
      realIndex += 1;
    }
```

Secondly, index won't change on hard swipe.

**Comment by linonetwo** [comment]
```
    if (!isBeginning) {

      realIndex += 1;

      // if you don't want last image slide out

      realIndex = Math.min(realIndex, slides.length - 1);

    }
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
