### ISSUE TITLE
swiper/vue virtual addSlidesAfter not effect

### ISSUE THREAD

**Issue by ranxiaoli** [nolimits4web/swiper#4659]
<swiper
        slides-per-view="1.6"
        :loop="false"
        :space-between="20"
        :centeredSlides="true"
        :virtual="virtualObj"
        @swiper="onSwiper"
        @slideChange="onSlideChange"
        @transitionEnd="onTransitionEnd"
        @touchStart="onTouchStart"
        v-if="resourceList.length > 0"
      >

  const virtualObj = {
        addSlidesAfter: 3,
        addSlidesBefore: 3,
        slides: resourceList.value, // 需要添加的虚拟slide的内容
}

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by Azurox** [comment]
Hi @nolimits4web , can we reopen this issue ?
It seems that on Vue it's not possible to access the `swiper` instance and programmatically trigger any function listed in the documentation (SlideTo, addSlidesAfter, etc...). I think we used to use ` this.$refs.swiper.$swiper.functionToExecute()` but now `$swiper` is not defined anymore and there is no hint in the documentation on how to retrieve it. 

I looked in the demo and for the same use case [Dynamic slides](https://swiperjs.com/demos#dynamic-slides) the Vue version is incomplete [Angular](https://codesandbox.io/s/mgye1?file=/src/app/app.component.ts:1486-1498) vs [Vue](https://codesandbox.io/s/6mmpv)  (Prepend/Append button are not here) and does not show how to execute function on the swiper instance

Thanks !

**Comment by nolimits4web** [comment]
@Azurox about instance in Vue, read the first paragraph here https://swiperjs.com/vue#swiper-events
