### ISSUE TITLE
Cannot read property 'addClass' of undefined

### ISSUE THREAD

**Issue by sbh96** [nolimits4web/swiper#4808]
![image 1](https://user-images.githubusercontent.com/6720334/126284386-d9230d4e-8114-493f-bf24-8953cfd53476.png)

I have the same error with NextJS + Swiper (6.7.0)
When a page is re-rendered with the slider, it breaks and gives the following message above.

I have downgraded to older versions, no luck..

_Originally posted by @GHVMZ in https://github.com/nolimits4web/swiper/issues/3056#issuecomment-883187834_

**Comment by sbh96** [comment]
please send any useful feedback i read all issues but over application on production we need fast help

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by muhaymin-bin-mehmood** [comment]
![image](https://user-images.githubusercontent.com/72308336/161567610-39a20731-db70-4c74-bfed-9ba92593af2e.png)
