### ISSUE TITLE
Swiperjs 6.8.1: Type SwiperModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by spicemix** [nolimits4web/swiper#4809]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://sorry.dont.have.time/

### Bug description

Upgrading swiper to 6.8.1 using latest angular gives

```
Uncaught Error: Type SwiperModule does not have 'ɵmod' property.
```

Backing off to 6.8.0 fixes the problem.

Followed all instructions on the website to the letter and have had zero problems otherwise. Thanks!

### Swiper version

6.8.1

### Platform/Target and Browser Versions

Angular 12

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
