### ISSUE TITLE
vue 3.0 按官网案例使用 6.8.4 版本的swiper   modules传值 [object Object]

### ISSUE THREAD

**Issue by zgnation** [nolimits4web/swiper#4890]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/vue#swiper-props

### Bug description

[](https://swiperjs.com/vue#swiper-props)
vue3.0 + ts  项目 按上述的案例来使用 在 swiper 传值 modules  页面渲染 为 modules="[object Object]“

### Swiper version

6.8.4

### Platform/Target and Browser Versions

Edge

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by zgnation** [comment]
`<template>
  <div class="phbHomeWrap">
    <div class="phbRecomend">
      <swiper :modules="modules" :space-between="20">
        <swiper-slide><RecommendDXItem></RecommendDXItem></swiper-slide>
        <swiper-slide><RecommendDXItem></RecommendDXItem></swiper-slide>
        <swiper-slide><RecommendDXItem></RecommendDXItem></swiper-slide>
        <swiper-slide><RecommendDXItem></RecommendDXItem></swiper-slide>
      </swiper>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { Swiper, SwiperSlide } from 'swiper/vue'
import { Pagination } from 'swiper'
import RecommendDXItem from './components/RecommendDXItem.vue'
import { init } from './controller/phbHome'
export default defineComponent({
  name: 'PhbHome',
  setup() {
    const { state, onChange } = init()
    return { state, onChange, modules: [Pagination] }
  },
  components: {
    RecommendDXItem,
    Swiper,
    SwiperSlide,
  },
})
</script>
<style scoped lang="scss">
@import './scss/phbHome.scss';
</style>`

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
