### ISSUE TITLE
Thumbnais and prev/next button doesn't work with web-components (Lit-element)

### ISSUE THREAD

**Issue by NickdeK** [nolimits4web/swiper#4903]
### Clear and concise description of the problem

As a developer using Lit-element I want to use Swiper in my webcomponents to the full extend. Much of it already works out of the box, but the thumbnails and prev/next buttons (based from the [core demo](https://codesandbox.io/s/gbtvt?file=/index.html)) don't work.

Please see this demo for the issue: https://codesandbox.io/s/inspiring-frost-uuw83?file=/src/media-gallery.ts

### Suggested solution

This seems to be caused by the shadowRoot layer in the web-component that the swiper javascript can't reach. shadowRoot should be supported with the selectors in the config as it has [major support](https://caniuse.com/?search=shadow%20dom).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
