### ISSUE TITLE
Transfer new effects from Swiper 7 to Swiper 6

### ISSUE THREAD

**Issue by ktim816** [nolimits4web/swiper#4912]
Hey! Thanks for the awesome slider guys. I wanted to know if it is possible to transfer new effects from Swiper 7 such as EffectCards, EffectCreative to the previous version of Swiper 6? Or, how could I implement these effects through the native api?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
