### ISSUE TITLE
Can't [Effect creative] share a spaceBetween?

### ISSUE THREAD

**Issue by songminzy** [nolimits4web/swiper#4921]
https://codepen.io/songminzy/pen/ZEyBGRp

Please check the link above.

Space is required between the sliders.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
