### ISSUE TITLE
Swiper is causing maximum DOM nesting problem and making website performance slow, can you tell me what causing it?

### ISSUE THREAD

**Issue by Rahultadmybrand** [nolimits4web/swiper#4941]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

NA

### Bug description

NA

### Expected Behavior

NA

### Actual Behavior

NA

### Swiper version

7.0.0

### Platform/Target and Browser Versions

Google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
