### ISSUE TITLE
Grab cursor not working between slides

### ISSUE THREAD

**Issue by jvhellemondt** [nolimits4web/swiper#4942]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#grab-cursor

### Bug description

I'm using Chrome and integrated the React swiper. However this also seems to happen on the demo page, so I assume it's also in the core. 

The grab cursor functionality only works on the spacing between items which are in view initially. If you swipe to slide 4, and you hover between slide 4 and slide 5 (and following), you can see that the grab cursor and functionality is not there.

https://user-images.githubusercontent.com/47124570/132834165-0297c249-0400-490e-94f8-89cc48b00d62.mov

### Expected Behavior

That the grab cursor is shown and functions even outside the initial view

### Actual Behavior

The grab cursor and functionality only works within the initial view.

### Swiper version

7.0.2

### Platform/Target and Browser Versions

macOS Big Sur 11.4, Chrome 93.0.4577.63

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
You can change touchEventsTarget to `container` then it will work on whole container https://swiperjs.com/swiper-api#param-touchEventsTarget

**Comment by jvhellemondt** [comment]
Awesome. That works. Any cons on setting the touch events to container?

**Comment by dangelion** [comment]
Hi @nolimits4web 
tried `touchEventsTarget: 'container'` and it works **only** after you drag the initial position. Also, after dragging, returning to initial position it doesn't drag again. Here a capture:

https://user-images.githubusercontent.com/4182418/136183950-3ad301fe-1bba-4d2c-a6b4-09756e6ccf42.mp4

Is this normal? Consider that on mobile with real usage this behavior happens.

Another question: why not use 'container' as default, since that it's normal usage of carousels.
