### ISSUE TITLE
Swiper not working in multiple pages

### ISSUE THREAD

**Issue by hilout** [nolimits4web/swiper#4956]
### Discussed in https://github.com/nolimits4web/swiper/discussions/4952

<div type='discussions-op-text'>

<sup>Originally posted by **hilout** September 13, 2021</sup>
Hello,
I'm using the swiper in multiple pages. The first swiper works fine, but I navigate to the second page, the swiper doesn't swipe.

Here is the demo: https://codesandbox.io/s/swiper-navigation-angular-forked-fp2o8

Any idea?

Thank you.

"swiper": "^6.8.4",
"@ionic/angular": "^5.5.2",</div>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
