### ISSUE TITLE
Errors with Vue latest edition on a liquid file

### ISSUE THREAD

**Issue by lguerra10** [nolimits4web/swiper#5042]
This code generates errors in the console and the slider does not work. 
If you delete the Vue code the slider works fine.  

<div id='product-card'>
......
</div>

<script>

  
  new Swiper(".swiper-{{- product.id -}}", {
    slidesPerView: 1,
    centeredSlides: true,
    spaceBetween: 0,
    loop: true,
    initialSlide: 0,
    breakpoints: {
      600: {
        allowTouchMove: false,
        speed:0,
        navigation: {
          nextEl: ".swiper-button-next-{{- product.id -}}",
          prevEl: ".swiper-button-prev-{{- product.id -}}"
        }
      }
    }

  })
  
const prodCard=Vue.createApp({
  delimiters: ['${','}'],
  data() {
    return {
      cartData: store.state.cartState
    }
    },
    created() {
      store.getCart()
    },
    methods: {

     addToCart(evente,variantId) {
      store.addToCart(variantId)
     }
     

    },
    
      
    }
  
}).mount('#product-card')

</script>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
