### ISSUE TITLE
centeredSlides = 'true' and .swiper-slide { width: auto; } make the slider start at the last image with missing images to the right

### ISSUE THREAD

**Issue by Stanzi1791** [nolimits4web/swiper#5076]
### Discussed in https://github.com/nolimits4web/swiper/discussions/5075

<div type='discussions-op-text'>

<sup>Originally posted by **Stanzi1791** October  9, 2021</sup>
Hi,

When I'm using centeredSlides = 'true' in combination with .swiper-slide { width: auto; }
the slider starts with the last image centered, images to the right of the centered image are missing.

After the first autoplay "move", the first image is centered and the images to the right are loaded,
this is the state I would have expected Swiper to start in.

Fiddle here (the first image is the green one):
https://jsfiddle.net/wq7j8Lep/2/ (you may have to refresh the page to see the behaviour above)

The fiddle uses Swiper 7.0.8, but I've also seen this behaviour in Swiper version 5.3.6.

If I turn off autoplay and look at the html, it looks like the "swiper-slide-active" class is getting assigned to the wrong slide (the last one) when the page first loads. 

Kind regards,
Marleen</div>

Added loopedSlides to the Fiddle, as per documentation, problem persists: https://jsfiddle.net/ojmp0fv4/
Tested on Firefox 93.0, Chrome 94.0.4606.71 and Edge 94.0.992.38, screenshots:

<a href="https://ibb.co/tJD8v9y"><img src="https://i.ibb.co/kSXQwtY/Screenshot-2021-10-10-125717.png" alt="Screenshot-2021-10-10-125717" border="0"></a>
<a href="https://ibb.co/dr5p34x"><img src="https://i.ibb.co/NsyNk2b/Screenshot-2021-10-10-125723.png" alt="Screenshot-2021-10-10-125723" border="0"></a>

**Comment by nolimits4web** [comment]
No need to ignore issue form, it is there for a reason.

Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
