### ISSUE TITLE
slide-next briefly blinks after animation is finished in Safar

### ISSUE THREAD

**Issue by lebmouse** [nolimits4web/swiper#5090]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-creative-forked-5nkrr?file=/index.html

### Bug description

'.swiper-slide-next' briefly blinks after animation is finished in Safar

https://user-images.githubusercontent.com/26789506/137297806-78709c6c-5dbc-4367-b185-f9e8da26c43a.mov

i.

### Expected Behavior

I hope the '.swiper-slide-next' doesn't blinks.

### Swiper version

7.0.8

### Platform/Target and Browser Versions

macOS safari

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by bobmagicii** [comment]
i am seeing similar but more rapid flashes in iOS safari too, which is also messing with the positioning a bit while you drag it back and forth.

**Comment by ramtinq** [comment]
Same here on Safari 14.0.3 on Mac OS 11.2.1 and swiper version 7.0.8.

**Comment by semyonkrutolevich** [comment]
> 

Did you resolve it?

**Comment by bobmagicii** [comment]
> Did you resolve it?

for me this was a symptom of #5091

**Comment by tohvanah** [comment]
Seems a solution is here: https://github.com/nolimits4web/swiper/issues/3641

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
