### ISSUE TITLE
Swiper7 sideEffects flag

### ISSUE THREAD

**Issue by sayowayah** [nolimits4web/swiper#5168]
Hello! I’m can’t seem to get tree shaking working with swiper 7 and webpack 5. I think I’ve identified the problem as a lack of a `sideEffects` flag in package.json. I see that v6.8 had this flag set and configured, but v7 doesn’t have it. Was this just an oversight or intentional and I should be doing things differently? Thanks!

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
