### ISSUE TITLE
Filter slides

### ISSUE THREAD

**Issue by Boris591** [nolimits4web/swiper#5290]
### Clear and concise description of the problem

There is currently no functionality to filter slides through tabs. You have to write your own functions, which is very inconvenient.

### Suggested solution

It is necessary to implement filtering slides by removing unnecessary ones and adding the necessary slides.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
> filter slides through tabs

what is "tabs"?

> You have to write your own functions, which is very inconvenient.

what exactly inconvenient?

**Comment by chandlerwilcox88** [comment]
Hi, I'm here to resurface this feature request as this is a common feature that I use with Slick Carousel.

Here is a link with what I think captures the concept:

https://codepen.io/alj_dev/pen/Wxjwpr

Here is a screen shot to slick sliders version of filtering:

https://kenwheeler.github.io/slick/
<img width="896" alt="Screen Shot 2022-12-21 at 9 16 29 PM" src="https://user-images.githubusercontent.com/7296169/209040623-d0ac175e-f82f-4b42-a42d-a831cef2d2be.png">

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
