### ISSUE TITLE
To have both "vertical" and "horizontal" direction option for the "cards" effect

### ISSUE THREAD

**Issue by Hugo01** [nolimits4web/swiper#5309]
### Clear and concise description of the problem

Hello  
First of all thank you for this awesome lib, such an amazing work! I'm speechless!
I was playing around with the "cards" effects and I noticed that you can only pick direction "vertical" or "horizontal" It would be amazing if you could actually have both, more or less like tinder

### Suggested solution

Add new property for both directions on the "cards" effect

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Sorry, but due to the nature how Swiper works it won't be possible to have both directions work at the same time

**Comment by falk-stefan** [comment]
@nolimits4web I've been looking at the cards-effect myself in order to get a tinder-like gesture for a question-answer or yes-no behavior.

I have no idea how SwiperJS works internally but wouldn't it be possible to just interpret left & right swiping as "goto next slide" and just propagete the actual direction via events?

The Tinder-swipe mechanism can be so useful sometimes. It's a pitty SwiperJS doesn't support this ..
