### ISSUE TITLE
slidesPerGroupAuto only works when sliding in the "previous" direction

### ISSUE THREAD

**Issue by Reinpal** [nolimits4web/swiper#5493]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-slidespergroupauto-51ox6i?file=/index.html

### Bug description

When setting slidesPerGroupAuto to true, the slides are only progressing correctly when navigating in the "previous" direction. when clicking in the "next" direction, the slides progress one by one.

### Expected Behavior

the slides should progress the same way no matter what direction you choose to slide.

### Actual Behavior

the slides progress differently depending on the direction you slide. when going backwards, it works correctly. when going forward it seems to ignore the setting or maybe calculate the slides that are in view incorrectly.

### Swiper version

8.0.6

### Platform/Target and Browser Versions

macOS Chrome, Safari, Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by masi** [comment]
The ticket has become stale because by not working on it. The provided link shows the described behaviour.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
