### ISSUE TITLE
`slideThumbActiveClass` class not applying correctly

### ISSUE THREAD

**Issue by rtabulov** [nolimits4web/swiper#5501]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/admiring-sound-4itrll

### Bug description

`slideThumbActiveClass` class just disappears 

- when thumb swiper automatically scrolls to keep active thumb visible 
- when you scroll through thumb swiper manually  

help pls!!!!!

### Swiper version

8.0.6

### Platform/Target and Browser Versions

chrome, firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by rtabulov** [comment]
just tried the same demo with react - the problem still occurs
https://codesandbox.io/s/vigorous-satoshi-vm2lkw

**Comment by everythinginjs** [comment]
same issue on v10.0.4.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
