### ISSUE TITLE
React Swiper Pause Autoplay on Mouse Hover

### ISSUE THREAD

**Issue by burhan333** [nolimits4web/swiper#5543]
### Discussed in https://github.com/nolimits4web/swiper/discussions/5537

<div type='discussions-op-text'>

<sup>Originally posted by **burhan333** March 10, 2022</sup>
Is there anyway i can pause autoplay on mouse hover and start autoplay on mouse out in react swiper
pauseOnMouseEnter Event is not working
</div>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
