### ISSUE TITLE
When changing the transition effect, the swiper slides an error

### ISSUE THREAD

**Issue by smebe** [nolimits4web/swiper#5570]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-cube-vue-forked-7sjdky?file=/src/App.vue

### Bug description

我想通过点击一个按钮来改变swiper的切换效果（effect），但是当改变之后，swiper再滑动的时候就会出现错误，并且样式也不太符合预期。这在所有的切换效果中都会出现此问题。

### Expected Behavior

可以正常的改变切换效果.

### Actual Behavior

改变后swiper变得不正常了。

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
