### ISSUE TITLE
React/Typescript/NextJs: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by tanyaburlakova** [nolimits4web/swiper#5587]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no link unfortunately 

### Bug description

Hello team!

this is a code of my component for the Carousel (we use yarn, not npm):

```
import * as React from "react"
import {Swiper, SwiperSlide} from "swiper/react"
import {Navigation} from "swiper"
import "swiper/css"
import "swiper/css/navigation"

export type CarouselProps = {
  navigation ?: boolean
  spaceBetween ?: number
  slidesPerView ?: number
  data : string[]
}

export function Carousel(props : CarouselProps) : JSX.Element {
  const {
    navigation = true,
    spaceBetween = 50,
    slidesPerView = 3,
    data,
  } = props
  return <Swiper
    navigation={navigation}
    modules={[Navigation]}
    spaceBetween={spaceBetween}
    slidesPerView={slidesPerView}
  >
    {data.map((content : string, key : number) => <SwiperSlide key={key}><>{content}</></SwiperSlide>)}
  </Swiper>
}
```

this is an example how I call it in the page 

```
import * as React from "react"
import {Link, Carousel} from "components"
import * as S from "styleguide"

const CarouselContent = [
  "<h3>Slide 1</h3>",
  "<h3>Slide 2</h3>",
  "<h3>Slide 3</h3>",
  "<h3>Slide 4</h3>",
]

export default function Layout() : JSX.Element {
  return <S.StyleguideLayout title="Simple Carousel">
    <S.Suite title="Basic">
      <div>Resources:</div>
      <Link href="https://github.com/tjallingt/react-youtube">https://github.com/tjallingt/react-youtube</Link>
      <Link href="https://www.npmjs.com/package/@types/youtube">https://www.npmjs.com/package/@types/youtube</Link>
      <BasicCases/>
    </S.Suite>
  </S.StyleguideLayout>
}

function BasicCases() {
  return <>
    <S.Case title={`YouTube Player with URL providing`}>
      <Carousel
        data={CarouselContent}
        spaceBetween={30}
        slidesPerView={3}
      />
    </S.Case>
  </>
}
```

If I import the swiper to the page as it described in the doc, without component, props etc. It works. 

### Expected Behavior

The Swiper is working.

### Actual Behavior

When I run the page I see this error

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Thank you.

### Swiper version

latest

### Platform/Target and Browser Versions

Google Chrome latest version, Mac

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by realamirhe** [comment]
I experienced the same problem.
In my situation, it is caused by tss-react.

The swiper module worked fine at the topmost level of import in the application hierarchy, however, it threw an error when I used Swiper within a component chain that used the 'tss-react' in some parent layer.

I updated the `'tss-react'` and `'mui'` packages to the latest versions, and everything appears to be fine in the initial render of my next app (actually, it was necessary to remove the '.next' directory first) all of the following has happened in the latest version of every mentioned package except `next`, which was '11.1.2'

In my latest upgrade to the `next` 12, it seems to be okay, but you need to disable 
experimental features flag
