### ISSUE TITLE
Dynamic bullets on resize

### ISSUE THREAD

**Issue by mmaaarten** [nolimits4web/swiper#5590]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://de-troubadour-outlet.webshopapp.com/

### Bug description

We have a instagram slider with pagination on desktop we want just normal bullets without the dynamic classes, when we go below our 991px it should add the new parameters of the dynamic bullets but somehow its not adding the dynamic bullet classes it should do, when we do a refresh it works fine.

### Expected Behavior

We expect that the classes are added to the bullets so it changes to dynamic bullets on resize but it does not work that way.

### Actual Behavior

It does not add the classes to the bullets on resize. it only adds it when you refresh on that screen size.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

MacOs, Windows 10, Google chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by mmaaarten** [comment]
BUMP?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
