### ISSUE TITLE
Facebook like swiper,  with first slide aligned left and all following are centered.

### ISSUE THREAD

**Issue by anton-ecom** [nolimits4web/swiper#5595]
### Clear and concise description of the problem

Following example of a swiper in Facebook,the first slide is aligned left, while second and all others are centered. 

### Suggested solution

We can add additional option "Align" or centeredSlidesAlign, with center as default, and left as an option,

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
