### ISSUE TITLE
Prevented event for click and mouse down if swipe started

### ISSUE THREAD

**Issue by gitRacoon** [nolimits4web/swiper#5603]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://kinderheldin.de/kursuebersicht

### Bug description

Open dropdown. It closes on the "click" event on the document. A check is made, if target does not match this dropdown, then the dropdown is closed.

If you open the dropdown and swipe on the swiper, the dropdown will not close.

I output the event hung on the document to the console. But it doesn't output anything to the console. I also tried to use the "mousedown" event, but it doesn't work even on a simple click on the swiper.

### Expected Behavior

Prompt a suitable event or correct the current one for clicking on the swiper.

### Actual Behavior

The click/mousedown event does not work when swiping.

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
