### ISSUE TITLE
Zoom: Configuring the zoom toggle event

### ISSUE THREAD

**Issue by odgalvin** [nolimits4web/swiper#5605]
### Clear and concise description of the problem

I'd like to be able to configure which event triggers the zoom toggle, rather than use the hard coded `doubleTap` event. For example to use a single tap, pressing a button, etc.

### Suggested solution

In [Carnoisseur/swiper](https://github.com/Carnoisseur/swiper), I used the existing `toggle` parameter. It keeps compatibility with existing code, but also allows specifying a string with an event name. If you'd be happy with that I can open a PR.

### Alternative

I wasn't sure whether to use the existing `toggle` parameter, or add a new parameter.
Also, initially I was going to let the parameter be set to "single" or "double", and then set the event to be "tap" or "doubleTap" respectively. But I thought why not just let the user specify an arbitrary event?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by inquiztr** [comment]
Couldn't you just fire the zoom in method on a click event?
`swiperGallery.on('click', function () {
        this.zoom.in();
    });`

**Comment by Nickonimus** [comment]
Actually i tried this first, but it zooming in center of the image, not to the cursor position. Am i missing something?

projectPage.on('click', function () { this.zoom.toggle(); });

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
