### ISSUE TITLE
Swiper overflows parent

### ISSUE THREAD

**Issue by opr-inzn** [nolimits4web/swiper#5623]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/modern-flower-wvz6kh?file=/src/pages/index.js

### Bug description

For some reason, my slideshow is cropped at the side. The parent div has a side padding and the swiper container inherits the padding and sets its width accordingly, however, as you can see in the image, the smaller slides overflow and get cropped. Not exactly sure where the issue is here.

On a side note: useSwiper and useSwiperSlide currently do not work and return undefined/null.

<img width="1512" alt="Screenshot 2022-04-11 at 12 16 34 AM" src="https://user-images.githubusercontent.com/80823111/162642282-b517bd8f-770e-47f1-aba1-427d329b19f4.png">

### Swiper version

8.0.6

### Platform/Target and Browser Versions

macOS Safari 15.4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Razunter** [comment]
Not sure about v8.0.6, but in recent versions Swiper uses `overflow: clip` which isn't supported on Safari...

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
