### ISSUE TITLE
slidesOffsetAfter option doesn't work with grid.rows > 1

### ISSUE THREAD

**Issue by vladgalafm** [nolimits4web/swiper#5633]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/hidden-bush-45z4s7

### Bug description

When Swiper has options `slidesPerView: 'auto'`, `grid.rows: 2`, and slides have their width and margins set via CSS, like in the codesandbox example - a `slidesOffsetAfter: -30` doesn't really remove that 30px from the wrapper width.
But the feature works fine, if `grid.rows === 1`...
It was not mentioned in the API that **slidesOffsetAfter** doesn't work for _grid.rows > 1_ - so I suppose this is a bug

### Swiper version

8.1.0

### Platform/Target and Browser Versions

Windows 10 Chrome v100

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by natemking** [comment]
I am experiencing the same using the most recent as of writing this, v8.1.5. 

My best guess is because the actual last slide is not getting marked active. The last slide to be marked active is the 2nd to last on the first row. I have tried many work arounds and have yet to figure out a solution

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
