### ISSUE TITLE
Track initiator for slideChange event

### ISSUE THREAD

**Issue by jjstanton** [nolimits4web/swiper#5659]
### The problem

When the `slideChange` event is triggered, I am unable to determine what triggered the event, be it the swiper `slideTo` event or an actual touch event etc. 

### Suggested solution

Track the state of what triggers the `slideChange` event.

### Additional context

Previous issue (stale/closed): https://github.com/nolimits4web/swiper/issues/4346

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
