### ISSUE TITLE
Swiper/vue RTL To LTR issue

### ISSUE THREAD

**Issue by chirumist** [nolimits4web/swiper#5690]
### LTR TO RTL BUG

- [x] I confirm

### Reproduction link

https://codesandbox.io/s/funny-water-ddz3lk?file=/src/App.vue

### Bug description

when i change rtl to ltr slider not working properly.

### Expected Behavior

Need to update slider as per direction or else give some method for reinit so we can reinit manually.

### Actual Behavior

LTR to RTL swiper not updated.

### Swiper version

8.1.4

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by upyo-ankit** [comment]
I am also facing the same issue in **next js**

**Comment by BlackCrowxyz** [comment]
Have the same issue, any suggestion?

**Comment by BlackCrowxyz** [comment]
> Have the same issue, any suggestion?
By simply removing the `:dir="rtl ? 'rtl' : 'ltr'"` line from `swiper` the code works correctly! but in my case, I had to add `dir` attr to make it work 🤦‍♂️

**Comment by jesspinklet** [comment]
There is a [changeLanguageDirection](https://swiperjs.com/swiper-api#method-swiper-changeLanguageDirection) method for this issue which helps, but still it doesn't calculate the positions correctly. Any news?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
