### ISSUE TITLE
Swipper navigation

### ISSUE THREAD

**Issue by FarhanRafid97** [nolimits4web/swiper#5728]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/v8xmc3?file=/src/App.jsx:436-832

### Bug description

i copy your code from your web "https://codesandbox.io/s/v8xmc3?file=/src/App.jsx:436-832"
 "swiper-navigation-react" on your codesandbox when u click once it only swipe 1 slide, but in my react app when i click once its swipe 2 slide ( im not using typescript)

### Expected Behavior

1 click next slide  swipe

### Actual Behavior

1 click next slide  2 swipe

### Swiper version

v8.1.5

### Platform/Target and Browser Versions

chrome(macOS)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
