### ISSUE TITLE
Cannot find module "swiper/vue" on Jest

### ISSUE THREAD

**Issue by AlibekGit** [nolimits4web/swiper#5729]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

not

### Bug description

When running tests, jest throwing error Cannot find module 'swiper/vue' from "myComponent.vue"

### Swiper version

8.1.5

### Platform/Target and Browser Versions

latest chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by 9527Robin** [comment]
`
  import { Swiper, SwiperSlide } from 'swiper/vue/swiper-vue';
`

**Comment by fabis94** [comment]
Thanks for the workaround, but is there any way to properly resolve this issue? It seems to be an issue in Node itself, not properly reading the "exports" fields in the package.json of the "swiper" package, because I'm guessing Jest just relies on the default Node module resolution algorithm. I've no idea why tho, because Node does seem to support the "exports" field.

**Comment by fabis94** [comment]
Ok turns out that it actually has something to do with Jest, and the new version of Jest - v28, finally supports the exports field. After upgrading, I get an entirely new error tho and this one might actually have something to do with how swiper is configured/built:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/938316/169492857-b7eac0db-3d61-47b7-89ea-354657beecdb.png">

It might be because swiper-vue.js isn't configured to be an ES module, but I'm not sure

**Comment by fabis94** [comment]
Ok, turns out my `transformIgnorePatterns` was too restrictive and didn't allow Babel to transform the swiper package. After adjusting it to allow Babel to transform swiper and all of its dependencies, and also mocking swiper/css with a fake module, I got it to work.

```
transformIgnorePatterns: [
    '/node_modules/(?!(nuxt|unenv|swiper|ssr-window|dom7)/).*$',
    '\\.pnp\\.[^\\/]+$'
  ]
```

It's still not clear to me why these packages need to be transformed in the first place. Why can't Jest import & load these modules without any transforms, when their package.json fields correctly specify "type: module" and they have ESM syntax in them?

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/swiper/issues/4871

**Comment by brickgale** [comment]
@fabis94 how did you mock the swiper? i'm still getting the same error.

**Comment by jonah-butler** [comment]
@brickgale, yes, i'm wondering the same thing. this has been plaguing me for several days and with swiper being used in so many places, the required stack causes all unit tests to fail when it meets that swiper import.

**Comment by savifon** [comment]
I have the same problem
