### ISSUE TITLE
Sliders don't move together, using the Thumbs module

### ISSUE THREAD

**Issue by dangelion** [nolimits4web/swiper#5750]
Before of Thumbs module we used Controller module but on Swiper 8 doesn't work as expected: **thumbnails are not moving as moving the main slider** and active thumbnails is not always centered.

[Here](https://codepen.io/intotheprogram/pen/PowvWeX) is an example how worked before. Compare with the actual [Thumbs demo](https://swiperjs.com/demos#thumbs-gallery-loop)

Thumbs module should works in the same way as Controller

Any way to solve this at this moment?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
