### ISSUE TITLE
Freemode associated with Coverflow creates weird transitions on touch events

### ISSUE THREAD

**Issue by quentin-f451** [nolimits4web/swiper#5779]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/focused-fire-5vcjet

### Bug description

When using FreeMode and Coverflow modules together, the momentum creates really strange transitions. It seems that the selected slide at the end of the momentum is already selected at the end of the touch event, and bypass the momentum.

### Expected Behavior

We would expect the touch Freemode to work mostly like the mousewheel module, where the transitions are applied to the slides as you scroll.

### Swiper version

v8.2.2

### Platform/Target and Browser Versions

iOS 15.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
