### ISSUE TITLE
onSlidePrevTransitionStart doesn't work as expected

### ISSUE THREAD

**Issue by israelTeamme** [nolimits4web/swiper#5822]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-react-demo-forked-6q0y63?file=/src/App.js

### Bug description

When using onSlidePrevTransitionStart the event is called only when the transition already happened and in that case onSlidePrevTransitionStart doesn't have any difference from onSlidePrevTransitionEnd.

### Expected Behavior

onSlidePrevTransitionStart should be called when the transition started

### Actual Behavior

onSlidePrevTransitionStart  called when the transition already happened (ended)

### Swiper version

8.0.7

### Platform/Target and Browser Versions

Chrome 102.0.5005.115

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
