### ISSUE TITLE
Slide disappear

### ISSUE THREAD

**Issue by soheilhassanjani** [nolimits4web/swiper#5831]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/react-ts-axwghp?file=App.tsx

### Bug description

I read some issues and I have tried to increase loopedSlides/loopAdditionalSlides parameters. But Still I get same issue when I swipe. i use version 8.2.5 and It often happens when we have a slide . this is example of my problem https://stackblitz.com/edit/react-ts-axwghp?file=App.tsx

### Swiper version

8.2.5

### Platform/Target and Browser Versions

macOS Monterey , Chrome 102.0.5005.115

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
