### ISSUE TITLE
A11y - disable span.swiper-notification

### ISSUE THREAD

**Issue by Gulmira-K** [nolimits4web/swiper#5844]
### Clear and concise description of the problem

Swiper [notificationClass](https://swiperjs.com/swiper-api#param-a11y-notificationClass) generates an empty span:

`<span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span>`

Demo link: https://codepen.io/ingvoo/pen/oyjgEp

There are no updates occurring in this container, its [purpose is unclear](https://github.com/nolimits4web/swiper/discussions/5837) and [BITV-Tests](https://webtest.bitv-test.de/index.php?a=di&iid=295) are invalid.

### Suggested solution

In order to pass BITV-Tests this span should be removed by (optionally) disabling [notificationClass](https://swiperjs.com/swiper-api#param-a11y-notificationClass)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by PSMJonas** [comment]
got the same issue.

**Comment by pedromlsreis** [comment]
Same here.

**Comment by jleeui** [comment]
I am seeing this markup show up on my project as well

**Comment by Karatt** [comment]
Hi! If you want to disable A11y notification, set parameter a11y: false

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by megatux** [comment]
I'm having same a11y issue with Swiper version 12.0.3 , need to remove it without disabling a11y module. Will use an init event handler but ideally there should be a config. option.
