### ISSUE TITLE
SwiperJs "focusableElements" parameter not working

### ISSUE THREAD

**Issue by Fox333-Lab** [nolimits4web/swiper#5911]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-space-between-react-forked-8xh819?file=/src/App.jsx

### Bug description

The focusableElements parameter is not working as expected and i am not able to focus on the specific element.
I am not able to find code example documentation relating to this parameter on swiperjs.com.

### Expected Behavior

when specific list of elements are provided in "focusableElements" parameter of swiper js these particular elemnts should be focused when clicked and should not be able to change slide through them

### Actual Behavior

Even after setting the focusableElements parameter with <ul> and <li> in my case i am not able to focus them 

### Swiper version

8.1.3

### Platform/Target and Browser Versions

chrome 103

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by tom-radikal** [comment]
I'm having the same issue

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
