### ISSUE TITLE
Updating state array (carouseImages: Array[]) fetching from API and appending/updating carouselImages state produces glitch on UI. How to resolve this glitch?

### ISSUE THREAD

**Issue by ShahzaibRiaz** [nolimits4web/swiper#5984]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

none

### Bug description

At initial load of the website I'm showing 3 images inside the carousel.
When user logs in based on his recommendations or buying experience on the website I'm updating the carousel with his interested images and appending those images at the end of the array.

When I update the state (array) with new fetched images from API the carousel produces glitch how to handle that situation.

### Swiper version

"swiper": "^8.3.2",

### Platform/Target and Browser Versions

Chrome Latest Version

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
