### ISSUE TITLE
Mouse Wheel Intertia/Momentum

### ISSUE THREAD

**Issue by ceri-waterscreative** [nolimits4web/swiper#6015]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#mousewheel-control

### Bug description

When scrolling, no matter how quickly or much you scroll it will only ever do one slide at a time. 

### Expected Behavior

Scroll an amount (or number of slides) proportional to the amount of scrolling/speed that you did. 

### Actual Behavior

Only scrolls a slide at a time (waiting for the transition), in free mode it's not smooth at all. 

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Windows 11 Chrome 104.0.5112.102 (and all other browsers..)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
