### ISSUE TITLE
vue3 @slideChange 函数，获取activeIndex 位置不对，模块放了两个，打印有3个

### ISSUE THREAD

**Issue by litaoyuan** [nolimits4web/swiper#6028]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

不需要地址

### Bug description

 <swiper @swiper="onswiper" :slidesPerView="1" :navigation="true" :loop="true" :autoplay="autoplayOptions"
                :pagination="{ clickable: true }" :modules="modules" @slideChange="slideChangePage">

//这里就是更新后的路径，以前是import { Swiper, SwiperSlide } from 'swiper/vue'
import { Swiper, SwiperSlide } from 'swiper/vue/swiper-vue'
import { Pagination, A11y, Autoplay, Navigation } from 'swiper'
//这里就是更新后的路径，以前是import 'swiper/css'
import 'swiper/swiper.min.css'
import 'swiper/swiper.scss'
import 'swiper/swiper-bundle.css'
import 'swiper/swiper-bundle.min.css'
import 'swiper/swiper-vars.scss'

//自动轮播的配置
const autoplayOptions = {
    delay: 5000,
    disableOnInteraction:false
}

const onswiper = (e)=>{
    const swipe1  = e;
    console.log("onswiper==",swipe1);
}

const slideChangePage = (e)=>{
    console.log("slideChangePage==",e.activeIndex);
}

const modules = [Pagination, A11y, Autoplay, Navigation]

### Expected Behavior

<img width="1440" alt="截屏2022-09-03 上午9 49 09" src="https://user-images.githubusercontent.com/16474407/188251281-701df7e0-32ca-49a7-87d4-24029fe38359.png">

### Actual Behavior

想实时监听位置

### Swiper version

  "swiper": "^8.3.2",

### Platform/Target and Browser Versions

Chrome 版本 104.0.5112.101（正式版本） (x86_64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
