### ISSUE TITLE
uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by ash-hashtag** [nolimits4web/swiper#6093]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Swiper.updateSize (updateSize.js:9:13)
    at Swiper.update (core.js:358:12)
    at index.js:16:477
```

vanilla js using swiper from cdn

```
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css">
    <script type="module">
      import Swiper from 'https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.esm.browser.min.js'
      const swiper = new Swiper(".swiper", {
        loop: true,
      });
      window.swiper = swiper;
    </script>
```

I kinda misunderstood something

how to update swiper to make newly added elements swipeable?

should I intialize swiper everytime I add new Elements?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
