### ISSUE TITLE
Swiper Is not Working 

### ISSUE THREAD

**Issue by MahendraBishnoi29** [nolimits4web/swiper#6094]
My Swiper is not working in React. Here's Code:
![code](https://user-images.githubusercontent.com/74294202/192145112-e60ef5b5-4fc7-4042-9aac-dd8a299a202e.png)

Imports 
![codedsf](https://user-images.githubusercontent.com/74294202/192145122-54e655a1-8c9d-4767-8929-b26e1eecdbef.png)

**Comment by MahendraBishnoi29** [comment]
@robpop @nolimits4web

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
