### ISSUE TITLE
Mousewheel only works once

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [nolimits4web/swiper#6096]
When adding mousewheel feature it only allows you to scroll down once and then it doesn't work again unless you drag the scrollbar

using latest swiper version: 8.4.2

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
