### ISSUE TITLE
Even with official demos, SwiperJS on mobile is really laggy.

### ISSUE THREAD

**Issue by albertoziveri** [nolimits4web/swiper#6163]
Look at this video: https://user-images.githubusercontent.com/8330244/197607387-cd5e891a-b3aa-4bd2-afbf-02893ee4f444.MP4 
I am attaching a video to express the issue which is clearly visibile even on official swiper js demos.
It's simply "laggy" when swiping, it's not smooth.

I noticed it once I visited nytimes.com and noticed how nytimes could make very smooth swipers containing high quality pictures.
Why Swiper JS is not at that level?
Regards

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
