### ISSUE TITLE
rtl mode spaceBetween bug

### ISSUE THREAD

**Issue by c-sun-0** [nolimits4web/swiper#6200]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codepen.io/highlight091016/pen/NWzpPow

### Bug description

spaceBetween is set to 24 and when the direction of the slide is 'rlt', 
24px is applied to the margin-left and margin-right, so the alignment becomes strange from the second slide.

### Expected Behavior

.swiper-slide {margin-left: 24px;}

### Actual Behavior

.swiper-slide {margin-left: 24px; margin-right: 24px;}

### Swiper version

8 (8,4,4)

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by jesspinklet** [comment]
Same here, any updates?

**Comment by windcrack** [comment]
Good day. Moreover, there is a problem on the last slide, there is also a margin right. Please remove the margin from the last slide.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
