### ISSUE TITLE
centeredSlidesBounds in controlled swiper sets wrong index as active

### ISSUE THREAD

**Issue by Dominic-Marcelino** [nolimits4web/swiper#6225]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-thumbs-gallery-forked-vpvr32?file=/index.html:5500-5520

### Bug description

When creating two sliders, one controlled by another and enable `centeredSlidesBounds` on the thumb-slider the centered slide will be active instead of the first one

Maybe related to #6224

### Expected Behavior

I'd expect the first slide to be active until we reach the centered slide and then keep the centered slide active.

### Actual Behavior

![Bildschirmfoto 2022-11-17 um 16 20 54](https://user-images.githubusercontent.com/46492597/202486293-d872b189-2d4e-451b-8e26-238689bd305f.png)

### Swiper version

8.4.4

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by DanielStout5** [comment]
I'm also seeing this issue on Swiper 9.1.1

**Comment by danielritter** [comment]
I have the same issue, is there any update to this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
