### ISSUE TITLE
Virtual mode doesn't play well with effects

### ISSUE THREAD

**Issue by zhaozhemin** [nolimits4web/swiper#6227]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-effect-cards-react-forked-ey5mux?file=/src/App.jsx

### Bug description

Virtual mode doesn't play well with some of the effects, for example, the cards effect. The actual behavior is hard to describe. Below is a screen recording which demonstrates the bug.

The `realIndex` is also wrong. At beginning of the recording, I change from slide 0 to slide 2, and then back to slide 0. Notice that it printed "2 2 0" instead of "2 1 0".

You should move the slides in a quick and short manner. If you slide slowly, it kinda works.

https://user-images.githubusercontent.com/10150604/202657287-9d8fbae5-96bb-4015-ab01-949bd132aa37.mov

### Swiper version

8.4.4

### Platform/Target and Browser Versions

macOS Firefox 106

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by marcoslor** [comment]
+1 for this!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
