### ISSUE TITLE
Fixed by 628a048

### ISSUE THREAD

**Issue by Yasaman-k** [nolimits4web/swiper#6246]
Fixed by 628a048

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/2359#issuecomment-347561009_
      
touchReleaseOnEdges works for me well but pagination does not work properly , when I am scrolling just the text scroll and pagination does not change depends on each item change on slider. when i deactive touchReleaseOnEdges pagination bullets works well.
any idea how to solve this? thanks.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
