### ISSUE TITLE
Flickering when using "direction: 'vertical'" in Firefox on minimal example

### ISSUE THREAD

**Issue by bertvandepoel** [nolimits4web/swiper#6247]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

http://bert.ulyssis.be/swiperjs_flicker/

### Bug description

I've been experiencing weird issues creating a simple slider in Swiper. I've been isolating the source of the issue, and have narrowed it down to the vertical direction. When using Firefox (tested both on Mac and Linux), a basic example of images and a vertical slider results in constant flickering of the "ghosts" of the slides not currently shown. In Chromium and Safari this doesn't happen. I've stripped out all other options and it exclusively happens when I add the direction vertical option.

### Expected Behavior

No flickering

### Actual Behavior

Flickering

### Swiper version

8.4.5

### Platform/Target and Browser Versions

Firefox 107

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by rijvanmohd** [comment]
@bertvandepoel have you found any solution for that?

**Comment by rijvanmohd** [comment]
`autoHeight={true} ` solves the issue for me. Maybe someone finds that useful.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
