### ISSUE TITLE
TypeError : Cannot read properties of undefined (reading 'autoplay')

### ISSUE THREAD

**Issue by hackftz** [nolimits4web/swiper#6261]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/green-thunder-19u5fv?file=/src/App.js

### Bug description

this is a typescript error

<img width="1984" alt="image" src="https://user-images.githubusercontent.com/33424860/206129571-ad1eedc9-ba56-41d6-818d-e245402bd362.png">

### Swiper version

8.4.5

### Platform/Target and Browser Versions

Version 106.0.5249.119 (Official Build) (arm64)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by IlanKro** [comment]
I am getting the same issue, tried to track it, it seems the swiper object is "destroyed" when it arrives at the "clearTimeout" function
The demo doesn't seem to reproduce the issue, I don't see the error there.
it falls on a null check since a destroyed swiper has no "paras". or "auto play"
maybe adding a null check before the error will help?
 if(!swiper.params) return;

**Comment by jeroenhoebe** [comment]
I'm having the same issue. With angular though.

**Comment by oleghalin** [comment]
Getting same error here, when i destroy swiper in Vue destroy hook after timeout pass it throws same error, swiper instance already destroyed, but it tries to execute swiper params
