### ISSUE TITLE
React SwiperSlider gaps  Issue on autoplay and loop mode

### ISSUE THREAD

**Issue by Kamasah-Dickson** [nolimits4web/swiper#6303]
I realized there are gaps in the swiperSlider when in loop and autoplay mode on page reload. even though I consider on page reload sliders can be blank because components are mounting but when I click the next button I get all sliders alright but I get gaps at the end of the last slider before the  loop kicks in to the first slider.

![localhost_5173_](https://user-images.githubusercontent.com/86136379/213979129-1f7f18e7-86d5-42e9-94ae-b0600cc6b94e.png)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
