### ISSUE TITLE
Can't drag swiper with spaceBetween and slidesPerView: auto in out-of-viewport gap area

### ISSUE THREAD

**Issue by stormgain-dev** [nolimits4web/swiper#6321]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos#slides-per-view

### Bug description

Open demo https://swiperjs.com/demos#slides-per-view, swipe right, start drag on gap between Slide 4 and Slide 5

### Expected Behavior

Slider dragging

### Actual Behavior

Slider not dragging

### Swiper version

8.4.7

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by stormgain-dev** [comment]
Workaround: add

        .swiper-wrapper {
            width: fit-content;
        }

**Comment by demiavaliani** [comment]
@nolimits4web you've done a great library, but with over 200 issues open, it's very hard to find the right issue, especially when the symptom `spaceBetween` does not match the cause `touchEventsTarget`.

Mind providing an actual URL to the issue instead of the same, countless unhelpful replies? Would be much easier for your users to find the issue and eventually save time for you. This is the 3rd issue I'm opening btw, only now finding anything remotely helpful - _it is related to `touchEventsTarget`_, and yet have to continue searching.
