### ISSUE TITLE
Swiper 9.0.2 + React 18.2.0 in StrictMode - Cannot read properties of undefined (reading 'slideClass')

### ISSUE THREAD

**Issue by ScorpAL** [nolimits4web/swiper#6340]
Swiper 9.0.2 + React 18.2.0 in StrictMode

```
Uncaught TypeError: Cannot read properties of undefined (reading 'slideClass')
    at slideSelector (process-lazy-preloader.js:2:1)
    at processLazyPreloader (process-lazy-preloader.js:3:1)
    at HTMLImageElement.<anonymous> (core.js:484:1)
```

_Originally posted by @ScorpAL in https://github.com/nolimits4web/swiper/issues/5398#issuecomment-1415952085_

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
