### ISSUE TITLE
Loop doesn't work on v-for

### ISSUE THREAD

**Issue by r-kocjan** [nolimits4web/swiper#6397]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-vue-infinite-loop-forked-mffppj?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A12%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A12%2C%22startLineNumber%22%3A14%7D%5D

### Bug description

I'm trying to add loop to swiper in vue, but I can't figure it out, I forked an example from your page, and tried to add v-for and 4 slides per view, but the loop just won't work, it doesn't work at all when trying to go to the next slide, and some weird jumping of slides happen when I try to go to the previous slide

### Swiper version

9.0.3

### Platform/Target and Browser Versions

macOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by DannyKr43mer** [comment]
As mentioned in the migration guide from version 8 to 9 loop mode won't work properly when the number of slides is not at least double the slidesPerView value. I already opened an issue, as I think that this is a use case that one will encounter often. The Issue was closed as it seems just a new limitation one should live with. 

https://swiperjs.com/migration-guide-v9

**Comment by r-kocjan** [comment]
Thank you for answe
