### ISSUE TITLE
swiper-button-next stopping the loop

### ISSUE THREAD

**Issue by maucherOnline** [nolimits4web/swiper#6448]
Expected behavior:
When I click on the 'next' button, the slider should go to the next slide without stopping at the last slide.

Observed behaviour:
When I click on the 'next' button, the slider goes to the next slide. At the last slide it stops and the button is deavtivated.
The back button, hovewer, is working as expected.

Here's the code:

`import $ from 'jquery';
import Swiper, {Navigation} from 'swiper';

$(document).ready(function() {

    const $grwp_swiper_container = $('.reviews_embedder_slider');
    if ( $grwp_swiper_container.length ) {

        $grwp_swiper_container.each(function (i, slider) {

            const grwp_swiper = new Swiper(slider, {
                modules: [ Navigation ],
                spaceBetween: 15,
                autoplay: false,
                loop: true,
                breakpointsBase: 'container',
                breakpoints: {
                    690: {
                        slidesPerView: 2,
                    },
                    1024: {
                        slidesPerView: 3,
                    },
                    1200: {
                        slidesPerView: 4,
                    }
                },
                // Navigation arrows
                navigation: {
                    nextEl: '.grwp-swiper-button-next',
                    prevEl: '.grwp-swiper-button-prev',
                },
            });
        });
    }
});`

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
