### ISSUE TITLE
[Bug] Swiper navigation not working with HTMLElement

### ISSUE THREAD

**Issue by saint777** [nolimits4web/swiper#6517]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/swiper-demo-2-navigation-ccrkhc?file=index.html

### Bug description

Accroding to documentation you put an HTML Element on nextEl, prevEl

But it doesn't work at all

Im very dissapointed, that it doesn't work with this simple configuration

<html>
<body>

nextEl | null \| HTMLElement \| CSSSelector | null | String with CSS selector or HTML element of the element that will work like "next" button after click on it
-- | -- | -- | --
prevEl | null \| HTMLElement \| CSSSelector | null | String with CSS selector or HTML element of the element that will work like "prev" button after click on it

</body>
</html>

### Expected Behavior

At least svg icons to appear

### Actual Behavior

No navigation elements

### Swiper version

9.1.1 (latest)

### Platform/Target and Browser Versions

WIndows 10, Chrome 111.0.5563.66

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the shitty [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Apparently you need to add these elements to DOM

Kind regards,
Vladimir Kharlampidi
________________________________
From: Aleksandr ***@***.***>
Sent: Thursday, March 23, 2023 3:15:43 PM
To: nolimits4web/swiper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nolimits4web/swiper] [Bug] Swiper navigation not working with HTMLElement (Issue #6517)


Check that this is really a bug

  *    I confirm

Reproduction link

https://stackblitz.com/edit/swiper-demo-2-navigation-ccrkhc?file=index.html

Bug description

Accroding to documentation you put an HTML Element on nextEl, prevEl

But it doesn't work at all

nextEl  null | HTMLElement | CSSSelector        null    String with CSS selector or HTML element of the element that will work like "next" button after click on it
prevEl  null | HTMLElement | CSSSelector        null    String with CSS selector or HTML element of the element that will work like "prev" button after click on it
Expected Behavior

At least svg icons to appear

Actual Behavior

No navigation elements

Swiper version

9.1.1 (latest)

Platform/Target and Browser Versions

WIndows 10, Chrome 111.0.5563.66

Validations

  *    Follow our Code of Conduct<https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md>
  *    Read the docs<https://swiperjs.com/swiper-api>.
  *    Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
  *    Make sure this is a Swiper issue and not a framework-specific issue

Would you like to open a PR for this bug?

  *    I'm willing to open a PR

**Comment by saint777** [comment]
> Apparently you need to add these elements to DOM

oh really, how would i know? Documentation doesn't even mention this.

How can i fix/edit documentation? I have a link.

https://swiperjs.com/swiper-api#navigation
