### ISSUE TITLE
First slide not visible when swiper is in the back of a rotating card (Firefox only)

### ISSUE THREAD

**Issue by nikolakov** [nolimits4web/swiper#6528]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/swiper-firefox-first-slide-issue-s54ch5

### Bug description

Create a rotating card by utilizing `transform-style: preserve-3d;`,  `transform: rotateY(180deg);` and `backface-visibility: hidden;`.

Render a React Swiper on the back of the card with a few slides in it. When the card is rotated, the first slide is not visible. While transitioning between slides however, the slide is visible. This issue is reproducible on Firefox only. 

Setting a custom style `backface-visibility: initial;` to the first slide seems like a hacky fix, but I don't know what it might break.

A codesandbox isolating the issue is provided.

### Expected Behavior

The first slide should be visible

### Actual Behavior

The first slide is not visible

### Swiper version

9.1.1

### Platform/Target and Browser Versions

Win 10 Pro; Browser: Mozilla FF latest v111

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
