### ISSUE TITLE
centeredSlides + centeredSlidesBounds + slideToClickedSlide is bugged

### ISSUE THREAD

**Issue by Hanskrogh** [nolimits4web/swiper#6591]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-react-centered-auto-forked-indc7w?file=%2Fsrc%2FApp.jsx&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A32%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A32%7D%5D

### Bug description

When there are insufficient slides and watch overflow is on and you click the last slide, it moves all of the slides to the other side. 

If you remove centeredSlidesBounds it is working as it is supposed to, but if you enable it it behaves very wierd.

### Expected Behavior

The slider should stay in place.

### Actual Behavior

Moves the whole slider move to the right, but only on last slide click

### Swiper version

9.2.2

### Platform/Target and Browser Versions

chrome 112.0.5615.49

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by LanGvest** [comment]
I have the same problem.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
