### ISSUE TITLE
Last slide cut of when using vertical slidesperview auto

### ISSUE THREAD

**Issue by pkihlberg** [nolimits4web/swiper#6693]
Hello, 

Im createing an simple SPA and I'm using swiper as for my sections on my scroll page. My footer (the last slide) gets cut off. I see you had this problem before, but I belive that the issue still exists for vertical direction

Layout component
```
type Props = {
  children?: ReactNode[];
};

export const Layout = (props: Props) => {
  const { children } = props;

  useEffect(() => {}, []);

  return (
    <div className={CS.Layout}>
      {/* Navbar is position absolute top */}
      <Navbar></Navbar>

      {/* Swiper used as full height scrollpage */}
      <Swiper
        slidesPerView={'auto'}
        direction={'vertical'}
        mousewheel={true}
        scrollbar={{ draggable: true }}
        autoHeight={true}
        modules={[Mousewheel, Scrollbar]}
        className='mySwiper'
      >
        {children &&
          children.map((child, i) => (
            <SwiperSlide key={'slide-' + i}>{child}</SwiperSlide>
          ))}
      </Swiper>
    </div>
  );
};
```

Main page component
```
export const MainPage = () => {
  const _pageTitleService = new PageTitleService();

  useEffect(() => {
    _pageTitleService.updateTitle();
  }, []);

  return (
    <Layout>
      <Header></Header>
      <Feature></Feature>
      <About></About>
      <Social socialList={['facebook', 'instagram', 'linkedIn', 'youtube']}></Social>
      <Footer></Footer>
    </Layout>
  );
};
```

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
