### ISSUE TITLE
Virtual slide not working with ngFor loop ANGULAR

### ISSUE THREAD

**Issue by gaurav050996** [nolimits4web/swiper#6795]
```
 <swiper-container class="swiper-container" virtual="true" slides-per-view="1" navigation="true">
          <swiper-slide class="swiper-slide">Slide 3</swiper-slide>
          <swiper-slide class="swiper-slide">Slide 1</swiper-slide>
          <swiper-slide class="swiper-slide">Slide 2</swiper-slide>
          <swiper-slide class="swiper-slide">Slide 3</swiper-slide>
          <swiper-slide class="swiper-slide">Slide 1</swiper-slide>
          <swiper-slide class="swiper-slide">Slide 2</swiper-slide>
          <swiper-slide class="swiper-slide">Slide 3</swiper-slide>
          ......
</swiper-container>
```
**The above code is working but when I am using virtual slide with ngFor it not working and load the entire DOM**

```
<swiper-container class="swiper-container" virtual="true" slides-per-view="1" navigation="true">
          <swiper-slide class="swiper-slide" *ngFor="let slide of slides; let i = index;">Slide {{i}}</swiper-slide>
</swiper-container>
```

**The above mentioned code is not working**

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
