### ISSUE TITLE
swiper-slide loop  for in

### ISSUE THREAD

**Issue by zqzy** [nolimits4web/swiper#6844]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no

### Bug description

 <swiper-container class="mySwiper" navigation="true" slides-per-view="5" sliders-per-group="5" direction="vertical"
      autoplay="true">
      <swiper-slide *ngFor="let item of params.dataSet">Slide 1</swiper-slide>
      <swiper-slide>Slide 2</swiper-slide>
      <swiper-slide>Slide 3</swiper-slide>
      <swiper-slide>Slide 4</swiper-slide>
      <swiper-slide>Slide 5</swiper-slide>
      <swiper-slide>Slide 6</swiper-slide>
      <swiper-slide>Slide 7</swiper-slide>
      <swiper-slide>Slide 8</swiper-slide>
      <swiper-slide>Slide 9</swiper-slide>
    </swiper-container> 

### Expected Behavior

      <swiper-slide *ngFor="let item of params.dataSet">Slide 1</swiper-slide>

无法自动播放

### Swiper version

9.0

### Platform/Target and Browser Versions

macos

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
