### ISSUE TITLE
Custom touch events emitted by Swiper are breaking 3rd party libraries listeners.

### ISSUE THREAD

**Issue by greg-md** [nolimits4web/swiper#6878]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/angular-7mwuay

### Bug description

When you want to listen for touch events of the parent's swiper container, you will get a few `CustomEvent` events which does not follow the native event's format and could break the business logic of the 3rd party libraries.

In this specific case, seems like the `touchstart` custom events breaks Ionic's gesture functionality. See https://github.com/ionic-team/ionic-framework/issues/27819 for more details why this seems to be a bug on the Swiper's side, because are using a `CustomEvent` instead of `TouchEvent` for triggering a `touchstart` event.

### Expected Behavior

Custom events emited by Swiper should not affect 3rd party libraries.

### Swiper version

10.0.4

### Platform/Target and Browser Versions

any

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Use events-prefix https://swiperjs.com/element#events

Kind regards,
Vladimir Kharlampidi
________________________________
From: Grigorii Duca ***@***.***>
Sent: Wednesday, July 26, 2023 5:11:35 PM
To: nolimits4web/swiper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nolimits4web/swiper] Custom touch events are breaking 3rd party libraries listeners. (Issue #6878)


Check that this is really a bug

  *    I confirm

Reproduction link

https://stackblitz.com/edit/angular-7mwuay

Bug description

When you want to listen for touch events of the parent's swiper container, you will get a few CustomEvent events which does not follow the native event's format and could break the business logic of the 3rd party libraries.

In this specific case, seems like the touchstart custom events breaks Ionic's gesture functionality. See ionic-team/ionic-framework#27819<https://github.com/ionic-team/ionic-framework/issues/27819> for more details why this seems to be a bug on the Swiper's side, because are using a CustomEvent instead of TouchEvent for triggering a touchstart event.

Expected Behavior

Custom events emited by Swiper should not affect 3rd party libraries.

Actual Behavior

No response

Swiper version

10.0.4

Platform/Target and Browser Versions

any

Validations

  *    Follow our Code of Conduct<https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md>
  *    Read the docs<https://swiperjs.com/swiper-api>.
  *    Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
  *    Make sure this is a Swiper issue and not a framework-specific issue

Would you like to open a PR for this bug?

  *    I'm willing to open a PR
