### ISSUE TITLE
There was a problem installing pnpm! , I tried all the ways , I think the error is from swiper.js

### ISSUE THREAD

**Issue by theramm** [nolimits4web/swiper#6952]
> Do you want to ask a question? Are you looking for support? [Stack Overflow](http://stackoverflow.com/questions/tagged/swiper) or [Swiper Discussions](https://github.com/nolimits4web/swiper/discussions) is the best places for getting support

> Please, don't use GitHub issues for questions

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/6951#issuecomment-1684352380_

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
