### ISSUE TITLE
Swiper slides become invisible during swipe

### ISSUE THREAD

**Issue by matinkg** [nolimits4web/swiper#6961]
### Discussed in https://github.com/nolimits4web/swiper/discussions/6926

<div type='discussions-op-text'>

<sup>Originally posted by **matinkg** August 13, 2023</sup>
Hi,
I don't have much experience using Swiper. I just implemented this and slides become invisible during long-distance swipe.
I think it's swiper issue. could you guys take a look?

https://codesandbox.io/p/sandbox/swiper-react-default-forked-jrk5wg?file=%2Fsrc%2FApp.jsx%3A13%2C1
 </div>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
