### ISSUE TITLE
Nothing hacky, just check the amount of slides and set/unset `justify-content: center;` prop when required

### ISSUE THREAD

**Issue by ilyas-hadi** [nolimits4web/swiper#6965]
Nothing hacky, just check the amount of slides and set/unset `justify-content: center;` prop when required

_Originally posted by @nolimits4web in https://github.com/nolimits4web/swiper/issues/2520#issuecomment-373675747_
           
           that is not a good way to resolve this issue because more issues comes up on mobile devices

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
