### ISSUE TITLE
Uncaughting Swiper

### ISSUE THREAD

**Issue by AtakanBacaksiz** [nolimits4web/swiper#7109]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/atakan-webflow-lds8lv?file=/script.js

### Bug description

Uncaught error with CDN install. You can find the Reproduction link at line 226 via the link I provided

### Swiper version

v10.3.1

### Platform/Target and Browser Versions

Windows Chrome 117

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by AtakanBacaksiz** [comment]
![Screenshot 2023-10-13 203149](https://github.com/nolimits4web/swiper/assets/32418624/28af812a-1dbc-475f-95a6-2f781b4d570c)
![Screenshot 2023-10-13 163239](https://github.com/nolimits4web/swiper/assets/32418624/130f2bf3-2404-46d1-b3b3-d9cc763aeb5f)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
