### ISSUE TITLE
:enabled props bug

### ISSUE THREAD

**Issue by neonarc4** [nolimits4web/swiper#7123]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

sadasdwdaawdawdaw

### Bug description

:enabled="true"    on  const condition = ref(false)    // enabled is not reactive it remain constant until a force re-render 

### Expected Behavior

```js

<button @click="condition = !condition" >   {{condition}} </button>
       <swiper
    :slides-per-view="1"
    :spaceBetween="2"
    :pagination="true"
    :modules="modules"
    :enabled="condition"
    class="mySwiper"
       :breakpoints="{
      '640': {
        slidesPerView: 2,
        spaceBetween: 20,
      },
      '768': {
        slidesPerView: 4,
        spaceBetween: 40,
      },
      '1024': {
        slidesPerView: 5,
        spaceBetween: 50,
      },
    }"
  >

      <swiper-slide>Slide 1</swiper-slide>
    <swiper-slide>Slide 2</swiper-slide><swiper-slide>Slide 3</swiper-slide>
    <swiper-slide>Slide 4</swiper-slide><swiper-slide>Slide 5</swiper-slide>
    <swiper-slide>Slide 6</swiper-slide><swiper-slide>Slide 7</swiper-slide>
    <swiper-slide>Slide 8</swiper-slide><swiper-slide>Slide 9</swiper-slide>
  </swiper>
```

### Actual Behavior

:enabled="condition "    on  const condition = ref(false)    //  not effecting the enabled actual props value 

### Swiper version

latest

### Platform/Target and Browser Versions

chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
