### ISSUE TITLE
Swiper cube sides hidden in Safari 17.1

### ISSUE THREAD

**Issue by Beauseph** [nolimits4web/swiper#7167]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiper-3d-pagination.uiinitiative.com/

### Bug description

We've just updated to Safari 17.1 on macOS. 
After updating, using the swipers cube effect, some sides do not display. From what i've seen, using a cube with 4 sides, the first and third show, the other ones don't, and sometimes they all appear to be experiencing some weird non-showing behaviour. 

I did not fork, as the issue is also present in the demo. I am experiencing the same issues in my project. 

https://github.com/nolimits4web/swiper/assets/107640465/988365f6-a335-4154-90ed-91c20ce0f536

### Expected Behavior

I expect that all sides show as intended, when scrolling as well as using swipe gestures.

### Actual Behavior

Some sides of the cube effect appear to render with a delay and often not show at all.

### Swiper version

11.0.3

### Platform/Target and Browser Versions

macOS Safari 17.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by Beauseph** [comment]
Apologies if i made any mistakes in the report, this is the first time i post on github (:

**Comment by nolimits4web** [comment]
https://swiperjs.com/blog/slide-slots-in-v10-1-0

**Comment by Beauseph** [comment]
Thank you for the provided resources, but the fixed version presented in the bottom of the blog post you mention exhibits the same bug still. 

Perhaps the workaround no longer works in 17.1? 
Could you confirm that the workaround using slots is no longer working? As when i view it it still shows the same issues,

**Comment by Beauseph** [comment]
Hi @nolimits4web 

I have tested across several versions of safari and mac OS, and with fix e005b69, it works on:
- MacOS Sanomo (14) with Safari 17.1 
- MacOS Monterey (12) with Safari 17.1

However, it seems that it still doesn't work for MacOS Ventura (13) on Safari 17.1.

**Comment by nolimits4web** [comment]
> Hi @nolimits4web 
> 
> 
> 
> I have tested across several versions of safari and mac OS, and with fix e005b69, it works on:
> 
> - MacOS Sonoma (14) with Safari 17.1 
> 
> - MacOS Monterey (12) with Safari 17.1
> 
> 
> 
> However, it seems that it still doesn't work for MacOS Ventura (13) on Safari 17.1.

Issue is not related to Swiper, you can open it in Safari tracker

**Comment by Beauseph** [comment]
Hi @nolimits4web,

Thank you for your reply. 

So if i understand correctly it's a problem with that Safari / OS with handling certain CSS transformations?
Nothing that can be done about this either? May i ask you what you mean with Safari tracker?

Thanks for your time and endless efforts.

Best regards

**Comment by Beauseph** [comment]
Hi team,

fyi, a user reported that this issue is not only present in Safari but also when using the swiper in an his (IOS). 
Perhaps it's worth considering to make fix e005b69 apple / ios wide and not just for safari, as it seems to not just be contained to Safari.

Thanks for your consideration

**Comment by Beauseph** [comment]
following up on this as i think it's a possible solution for this problem.

**Comment by Beauseph** [comment]
following up on this problem again. this fix, if i understand correctly, should also be implemented to webview containers on IOS devices.

I think this would fix that issue:
![image](https://github.com/nolimits4web/swiper/assets/107640465/b9b88744-92f1-448c-9a27-b8cc27660d76)

**Comment by deniss-ee** [comment]
Issue is not resolved. If there are more than 4 slides and slider is looped, cube is still bugged on Safari.

**Comment by jiggy1965** [comment]
I've got the solution but swiper.js should update their swiper-bundle.min.js file for this. I'm using Safari 17 on Ventura and have the same issue with 3d cubes in general. Turns out Safari on Ventura has a problem with sides that are **exactly** rotated 90 degrees. For those of you working on Ventura you'll probably won't see the left and right sides of this cube as well.

[https://codepen.io/coder1965/pen/oNRggjb](url)

Unless you turn all those 90deg and -90deg's to something other than exactly 90/-90. Like 90.01/-90.01. Then all sides appear again. There's a bug of some kind in Safari running on Ventura where when elements are exactly rotated 90 degrees Safari regards them as hidden afterwards. 

In order for swiper.js to work the swiper-bundle.min.js file should be adjusted so that on every rotateX and rotateY something like an extra '0.01' should be added to the 'deg' value. It will still rotate the elements 90 degrees (as the browser will round the 90.01 down to 90), but Safari won't consider objects initially rotated 90.01 as hidden anymore.

Hopefully the swiper.js developers will pick up on this so our cubes will run normally again on Safari Ventura?

**Comment by jiggy1965** [comment]
https://github.com/nolimits4web/swiper/issues/7532#issuecomment-2117376107

My updated swiper-bundle.min.js file is the fix. It adds '0.01' to every occurrence of rotateX and rotateY. The bug.zip file shows the current not working version for Safari/Ventura users. It uses the standard CDN. The fix.zip file uses the updated swiper-bundle.min.js file. Here on Ventura 13 all sides are visible as they should be.
