### ISSUE TITLE
Swiper Element breakpoints doesn't work until responsive

### ISSUE THREAD

**Issue by dunfe** [nolimits4web/swiper#7258]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://934rv3-3000.csb.app/

### Bug description

The bug in SwiperJS occurs when slidesPerView in breakpoints fails to function until the responsive behavior is triggered. Leading to inconsistent behavior in the layout of the swiper element

### Expected Behavior

I expected the slidesPerView in breakpoints in SwiperJS to be effective immediately after Swiper initialize

### Actual Behavior

Swiper shows the default slidesPerView on load regardless of what is slidesPerView in the breakpoints setting, only apply breakpoints slidesPerView when changing window width

### Swiper version

11.0.5

### Platform/Target and Browser Versions

Windows 11 Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Look for issue on your side (as i can't see the source code of the demo). As you can see here https://codesandbox.io/p/sandbox/vy6xkz it works perfectly fine

**Comment by dunfe** [comment]
> Look for issue on your side (as i can't see the source code of the demo). As you can see here https://codesandbox.io/p/sandbox/vy6xkz it works perfectly fine

Sorry, I missed codesandbox link. It's here: https://codesandbox.io/p/devbox/swiper-element-breakpoint-doesnt-work-934rv3

I'm using the Swiper element in NextJS in my case, can you recheck?

**Comment by draghia-andrei** [comment]
@dunfe If still interested, I managed to debug this issue as I had it too. Seems to be React specific if you set things like in the demo.
First of all it seems the order of properties in the `params` object you pass, do matter. In the example it is working fine because the `slidesPerView` is set before `breakpoints`. If you reverse the order it breaks.

When you call `Object.assign(swiperRef.current, params);` in useEffect it triggers `updateSwiperOnPropChange` which takes the props and calls `setBreakpoints()` function when the `breakpoints` param is set and for each param assigned afterwards. In setBreakpoints() there is a guard to only run it if the current breakpoints value changed. "breakpoints" get applied the first time by the `breakpoints` prop which sets the cached breakpoint, then if the order is wrong, `slidesPerView` param gets applied which changes the number of slides to display. Since the breakpoint was already applied and cached it doesn't get corrected anymore by setBreakpoints().

Another case is, in React during development, useEffect gets called 2 times. This means `Object.assign(swiperRef.current, params);` will get called 2 times. The second time, the `breakpoints` prop is already set, `currentBreakpoint` is already cached so every prop will overwrite what you set in breakpoints.

The same thing would happen if you update the settings under a specific breakpoint let's say from 2 slides to 3, since the `swiper.currentBreakpoint` is not invalidated, the change will not be applied. In my case the problem happened during navigation as the already initialized component was retained and updated.

I managed to solve it by manually invalidating the cache before Object.assign. Hopefully no side-effects.
`  useIsomorphicLayoutEffect(() => {
    if (swiperRef.current) {
      if (swiperRef.current?.swiper?.currentBreakpoint) {
        swiperRef.current.swiper.currentBreakpoint = null;
      }
      Object.assign(swiperRef.current, params);
    }
  }, [slidesPerView, navigation, pagination, breakpoints, loop]); // put here your dependencies that can change "params"

  useIsomorphicLayoutEffect(() => {
    swiperRef.current.initialize();
  }, []);;`
`register();` I called it outside the component. Doesn't make much difference as long as it's called early.

**Comment by max481516** [comment]
@draghia-andrei I am really interested since I have the same issue, but I am a beginner and I don't really understand how to implement your code, can you explain how to properly do it? Here is my slider:

`import {
  HomeCarouselPhoto1,
  HomeCarouselPhoto2,
  HomeCarouselPhoto3,
  HomeCarouselPhoto4,
} from "../media/HomeCarousel/HomeCarouselPhotos.js";
import { useEffect, useRef } from "react";
import { register } from "swiper/element/bundle";
register();

const MySwiper = () => {
  const swiperRef = useRef(null);

  useEffect(() => {
    const swiperContainer = swiperRef.current;
    const params = {
      slidesPerView: 1,
      navigation: true,
      pagination: {
        clickable: true,
      },
      breakpoints: {
        1100: {
          slidesPerView: 3,
          spaceBetween: 20,
        },
      },
      injectStyles: [
        `
          .swiper-button-next,
          .swiper-button-prev {
            cursor: pointer;
            color: var(--color-green);
            transition: color 0.6s ease;
          }

          .swiper-button-next:hover,
          .swiper-button-prev:hover {
            color: hsl(0, 0%, 20%);;
          }

          .swiper-pagination-bullet{
            height: 8px;
            width: 8px;
            cursor: pointer;
            background-color: var(--color-pink);
            transition: background-color 0.6s ease;
          }

          .swiper-pagination-bullet:hover {
            background-color: var(--color-dark-green);
          }
      `,
      ],
    };

    Object.assign(swiperContainer, params);
    swiperContainer.initialize();
  }, []);

  return (
    <swiper-container ref={swiperRef} init="false" auto-height="true">
      <swiper-slide>
        <img src={HomeCarouselPhoto1} alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src={HomeCarouselPhoto2} alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src={HomeCarouselPhoto3} alt="" />
      </swiper-slide>
      <swiper-slide>
        <img src={HomeCarouselPhoto4} alt="" />
      </swiper-slide>
    </swiper-container>
  );
};

export default MySwiper;
`

**Comment by max481516** [comment]
@draghia-andrei I finally managed to do it myself, but thank you very much for your solution, you are a life saver!

**Comment by notflip** [comment]
@dunfe Did you manage to find a solution?

**Comment by notflip** [comment]
@max481516 What method did you use to fix ths?
