### ISSUE TITLE
Scroll sometimes stops working in autoHeight mode

### ISSUE THREAD

**Issue by step135** [nolimits4web/swiper#7295]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

No code

### Bug description

I have images of different heights and I set up `autoHeight: true`. What happens is that when next image is higher, it scrolls a little bit down to see it. But when I start going backwards and then again forwards, this feature breaks and doesn't work anymore.

Also feature request to improve that scroll effect is to scroll at least so that the button of each photo is visible and if photo height is bigger than the screen height, than it should keep fixed its vertical middle in screen verival middle.

### Swiper version

Latest

### Platform/Target and Browser Versions

Chrome on Android

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
