### ISSUE TITLE
 [Vue warn]: Component emitted event "_freeModeStaticRelease" but it is neither declared in the emits option nor as an "on_freeModeStaticRelease" prop.

### ISSUE THREAD

**Issue by FastGUI** [nolimits4web/swiper#7413]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/devbox/swiper-freemode-vue-forked-6vkn4d?file=%2Fsrc%2FApp.vue%3A3%2C1-11%2C40

### Bug description

![img](https://github.com/nolimits4web/swiper/assets/35055114/4fcd0b23-1244-44bf-882a-b5f6f43f159c)
`
  <Swiper :slides-per-view="'auto'" :free-mode="true" :modules="[FreeMode]">
    <SwiperSlide
      v-for="(subItem, index) in list"
      :key="index"
    >
      {{ subItem.meta.title }}
    </SwiperSlide>
  </Swiper>
...
<script setup>
import { Swiper, SwiperSlide } from "swiper/vue";
import { FreeMode } from "swiper/modules";
import "swiper/css";
import "swiper/css/effect-fade";
....
`

Simulate pressing and sliding on the mobile end

### Expected Behavior

Do not prompt and fix issues

### Actual Behavior

Simulate pressing and sliding on the mobile end

### Swiper version

11.0.7

### Platform/Target and Browser Versions

Windows11 & Google Chrome 122.0.6261.129

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
