### ISSUE TITLE
how to stop swiper change the width of the swiper-slide?

### ISSUE THREAD

**Issue by calidion** [nolimits4web/Swiper#742]
i have style the swiper-slide to my need.

but after i inited the swiper, the swiper-slide's width is changed.

to the following.

<div class="swiper-slide swiper-slide-visible" style="width: 297.5px; height: 160px;">
        </div>

how can i avoid width changes in swiper?

**Comment by MoAsmar** [comment]
Hi guys, I have read this beautiful conversation and thanks to both of you I was able to solve the issue with swiper slide width using swiper API in SharePoint 2013, but still have a problem with making the swiper slide automatically; after adding slidesPerView:'auto', visibilityFullFit: true, & autoResize: false, it stopped.

I'm using this js code:

    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        spaceBetween: 0,
        autoplay: 4500,
        autoplayDisableOnInteraction: true,
        speed: 1400,
	slidesPerView:'auto',
	visibilityFullFit: true,
	autoResize: false,
	initialSlide : 2,
	loop : true,
	loopedSlides : 20,
    });

for width issue I have added width inline on the div with class="swiper-slider";
<div class="swiper-slide" style="width: 1349px!important;background-image:url('/Style Library/images/slider.png')">

this is the first time I use swiper API and it seams that it add styles to the html using jquery because there is transform:translate(3d) whish I cannot control in being rendered on div with class="swiper-wrapper" on top of "swiper-slide".

I hope we can find a better solution.
Thanks
