### ISSUE TITLE
SwierJS now autoplaying in mobile view ReactJS

### ISSUE THREAD

**Issue by daniLdutra** [nolimits4web/swiper#7488]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

-

### Bug description

Swiper is working properly on desktop view, switching images automatically (autoplay).
As soon as I switch to mobile view it gets stuck in one the first image and doesn't switch no matter what.

import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/pagination';
import { Autoplay, Pagination } from 'swiper/modules';
import { images } from './images';

<Swiper
        direction={'vertical'}
        pagination={{
          clickable: true,
        }}
        autoplay={{
          delay: 2500,
          disableOnInteraction: false,
        }}
        modules={[Autoplay, Pagination]}
      >
        {images.map((image, index) => (
          <SwiperSlide key={index}>
            <img
              src={image}
              alt={`Slide ${index + 1}`}
              className="h-96 w-auto object-cover md:h-full md:w-full"
            />
          </SwiperSlide>
        ))}
</Swiper>

### Expected Behavior

Autoplay on mobile view.

### Actual Behavior

Get's stuck in the first image.

### Swiper version

11.1.1

### Platform/Target and Browser Versions

Xubuntu 22.04.4 Google Chrome 124.0.6367.60

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
