### ISSUE TITLE
We observed that route changes are blocked on web views when navigating to a page containing the Swiper component.

### ISSUE THREAD

**Issue by BackdoorTech** [nolimits4web/swiper#7648]
### Check that this is really a bug

- [x] I confirm

### Reproduction link

none

### Bug description

when i visite a page that contains Swiper component in my ionic angular app, it cause the app to have a hard time change route(path) and page this only happens on running on webview on chrome it runs just fine.

### Expected Behavior

when i visite a page with swiper component i can navigate to other page at easy

### Actual Behavior

cant go to other page when i visite a page with swiper container

after i edited this file node_module/swiper/shared/update-swiper.mjs i fixed it
i have added a try and catch block to the function destroyModule

```javascript
const destroyModule = mod => {
  if (!swiper[mod]) return;
  swiper[mod].destroy();
  if (mod === 'navigation') {
    if (swiper.isElement) {
      
      try { // ==== added
        swiper[mod].prevEl.remove();
        swiper[mod].nextEl.remove();
      } catch (e) { // ==== added
        // Error handling if removal fails.
      } // ==== added
    }
    currentParams[mod].prevEl = undefined;
    currentParams[mod].nextEl = undefined;
    swiper[mod].prevEl = undefined;
    swiper[mod].nextEl = undefined;
  } else {
    if (swiper.isElement) {
      swiper[mod].el.remove();
    }
    currentParams[mod].el = undefined;
    swiper[mod].el = undefined;
  }
};
```

### Swiper version

11.0.5

### Platform/Target and Browser Versions

Webview

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
