### ISSUE TITLE
App gets blank while using swiper

### ISSUE THREAD

**Issue by Vikiraj008** [nolimits4web/swiper#7671]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

missing demo

### Bug description

In my project, I have a menu page, a product page, and a bag page. When I click an item on the menu page, it redirects to the product details page, which features multiple swipers with images of the product and its subitems. The workflow is as follows: when I click on the CTA of a subitem, it displays swiper-1 with the details of subitem 1. After selecting that subitem, it slides to swiper-2 with the details of subitem 2. Upon selecting that, it slides to swiper-3, and so on. 
 

### Expected Behavior

Whenever I add the same product after selecting its subitems, it should be added to the bag without any issues.

### Actual Behavior

However, I can add the same product to the bag 3 to 4 times without any issues. But during the 4th or 5th attempt of adding the same item, when interacting with the subitem swipers (clicking or sliding), my app screen goes blank and redirects to the menu page.
Also, I can't get this issue on the web and Android. This is only happening in iOS (Apps).
Note: I searched for similar issues but couldn't find a solution, so I'm raising this issue as it occurs while interacting with the swipers.

### Swiper version

6.8.4

### Platform/Target and Browser Versions

iOS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/nolimits4web/Swiper/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
