### ISSUE TITLE
Problem with Canvas in Slider

### ISSUE THREAD

**Issue by Hitami** [nolimits4web/Swiper#796]
Hi,
i've got a problem with two Canvas in the Slider.. i show up a chart in both slider pages, the first one gets drawn, the second not.. and here's the disorder:
If i swipe on the left, the canvas gets drawn, if i swipe on the right not..

Can anybody help me / any ideas?

**Comment by wojjas** [comment]
@nolimits4web Many thanks you are so right!
I use swiper's call-back onInit() to draw on canvases from there. 
Also note that the duplicates will have the same id in HTML!
I had to use getElementsByClassName instead of getElementById (which only gave me the first match and I still didn't draw to the duplicates)
