### ISSUE TITLE
Randomize slides order

### ISSUE THREAD

**Issue by coldpumpkin** [nolimits4web/Swiper#893]
Hi there,

Is it possible to randomize slides order?

Say, they have a specific HTML order though I want the slider to randomize it.

Thanks.

**Comment by loorlab** [comment]
:-1: We try to implement this by ordering the HTML does not work correctly in the : Safari-Chrome on a Mac .

:-1: We had to stop using Swiper therefore not having a random for slides, it would be good especially considering the developments that we need to show products randomly.

:1234: TIP : We created this test http://jsfiddle.net/jBzB4/118/

**Comment by nolimits4web** [comment]
@loorlab Can't see any problems with it. Is it hard for you to add 2 lines of custom code before you init Swiper to get random slides, really?

**Comment by loorlab** [comment]
@nolimits4web And we implement this validation you described to sort the slides but we works perfect for Chrome - Firefox (PC) but not in MAC (Safari - Chrome), jQuery changed version and also does not give a result, and validate various options either.

**Comment by allrude** [comment]
Very Old ISSUE I Know,

But since I couldn't find a proper solution I solved it like this.

I made a **$maxSlides = 0**

inside my foreach I placed **$maxSlides++**

inside the script I placed

**initialSlide: <?= mt_rand(0, ($maxSlides - 1)) ?>,**

Now I have a rondom slider, I sure this can be done better and pure with JS and no PHP

So who has a better solution ;-)
