### ISSUE TITLE
width and height using percentage

### ISSUE THREAD

**Issue by mnifakram** [nolimits4web/Swiper#896]
Hey I want to make something that mix between responsive and partial, I set the swiper-container{ width:100%; height:100%} and the swiper-slide{width:90%; height:100%} but in the output I get the swiper-slide width 100% (the same as the container) how I can correct this.
Check the demo  http://jsfiddle.net/fnhb137d/

**Comment by zapatoche** [comment]
But if we know the width of the parent (on page load) can't we define the width of the slider-wrapper depending one the number of item, then set their  width in % of the slider-wrapper width?
I'm asking because I have a project with "fluid" typography, and when I increase the font size on the body, the slider breaks in IE10/11 (because the swipes width is in pixel).
