### ISSUE TITLE
White stripe ghost

### ISSUE THREAD

**Issue by manuelpaulo** [nolimits4web/Swiper#939]
Hi. I am using the Swiper on horizontal mode and had no issues on iPhone, iPad and Androids Tablets.  However, on Android phones, I get this strange behaviour:

Load one, two, three, four slides going back(swipe left) and forward(swipe right) no issue. However from slide 15 onward, I get a flicker white stripe on the direction I am navigating that fills 10% to 50% of the screen for a fraction of second. Now when I do back (left) works fine till the 8th slide from there below, the same white stripe glitch, now on the left, I turn back right again and it work fine 8 slides forward....

Is this a memory issue? I have tried with different memory free and it always starts at slide 15 

Thanks for any clue, and thanks for the script!

**Comment by larsbo** [comment]
I wonder if you can easily modify the example of @manuelpaulo for freemode. I have a slideshow with freemode enabled and lots of images (50+). Instead of preloading all the images a lazy loading solution would be great that appends additional images at the end.

I experimented with ```onSetWrapperTransform``` instead of ```onSlideChangeEnd``` but it looks not trivial to compute the correct solution if there are images with different widths. 

Any ideas? :)
